-- Events DDL for domain: indoor-air-quality (CAs + detection)
-- Generated by ndp-gold-ddl
-- Mode: sync
-- NOTE: Table/indexes/retention/unified view are in init-script 010-events-hypertable.sql

CREATE SCHEMA IF NOT EXISTS gold;

-- Hourly events continuous aggregate (create if not exists)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM timescaledb_information.continuous_aggregates
        WHERE view_schema = 'gold'
          AND view_name = 'events_hourly'
    ) THEN
                CREATE MATERIALIZED VIEW gold.events_hourly
        WITH (timescaledb.continuous) AS
        SELECT
            time_bucket('1 hour', event_time) AS bucket,
            COUNT(*) AS total_events,
            COUNT(*) FILTER (WHERE event_type = 'state_transition') AS state_transition_count,
            COUNT(*) FILTER (WHERE event_type = 'threshold_crossing') AS threshold_crossing_count,
            COUNT(DISTINCT entity_id) AS distinct_entities_with_events
        FROM gold.events
        GROUP BY bucket
        WITH NO DATA;
        RAISE NOTICE 'Created continuous aggregate: gold.events_hourly';
    ELSE
        RAISE NOTICE 'gold.events_hourly already exists, skipping';
    END IF;
END $$;

-- Refresh policy for events hourly aggregate (remove+add ensures correct offsets on redeploy)
SELECT remove_continuous_aggregate_policy('gold.events_hourly', if_exists => TRUE);
SELECT add_continuous_aggregate_policy('gold.events_hourly',
    start_offset => INTERVAL '365 days',
    end_offset => INTERVAL '1 hour',
    schedule_interval => INTERVAL '15 minutes'
);

-- Index for time range queries
CREATE INDEX IF NOT EXISTS idx_events_hourly_bucket
    ON gold.events_hourly (bucket DESC);

-- Backfill: materialize any events outside the rolling refresh window
CALL refresh_continuous_aggregate('gold.events_hourly', NULL, NULL);

-- Hourly events by entity continuous aggregate (create if not exists)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM timescaledb_information.continuous_aggregates
        WHERE view_schema = 'gold'
          AND view_name = 'events_hourly_by_entity'
    ) THEN
                CREATE MATERIALIZED VIEW gold.events_hourly_by_entity
        WITH (timescaledb.continuous) AS
        SELECT
            time_bucket('1 hour', event_time) AS bucket,
            entity_id,
            stream_id,
            COUNT(*) AS total_events,
            COUNT(*) FILTER (WHERE event_type = 'state_transition') AS state_transition_count,
            COUNT(*) FILTER (WHERE event_type = 'threshold_crossing') AS threshold_crossing_count
        FROM gold.events
        GROUP BY bucket, entity_id, stream_id
        WITH NO DATA;
        RAISE NOTICE 'Created continuous aggregate: gold.events_hourly_by_entity';
    ELSE
        RAISE NOTICE 'gold.events_hourly_by_entity already exists, skipping';
    END IF;
END $$;

-- Refresh policy for events hourly by entity aggregate (remove+add ensures correct offsets on redeploy)
SELECT remove_continuous_aggregate_policy('gold.events_hourly_by_entity', if_exists => TRUE);
SELECT add_continuous_aggregate_policy('gold.events_hourly_by_entity',
    start_offset => INTERVAL '365 days',
    end_offset => INTERVAL '1 hour',
    schedule_interval => INTERVAL '15 minutes'
);

-- Indexes for events hourly by entity
CREATE INDEX IF NOT EXISTS idx_events_hourly_by_entity_bucket
    ON gold.events_hourly_by_entity (bucket DESC);

CREATE INDEX IF NOT EXISTS idx_events_hourly_by_entity_entity_bucket
    ON gold.events_hourly_by_entity (entity_id, bucket DESC);

-- Backfill: materialize any events outside the rolling refresh window
CALL refresh_continuous_aggregate('gold.events_hourly_by_entity', NULL, NULL);

-- Event detection procedure (runs as TimescaleDB job)
-- Delete dependent jobs and DROP procedure to avoid "cannot remove parameter defaults" error
DO $$
DECLARE
    _job_id INTEGER;
BEGIN
    FOR _job_id IN
        SELECT job_id FROM timescaledb_information.jobs
        WHERE proc_schema = 'gold' AND proc_name = 'detect_events'
    LOOP
        PERFORM delete_job(_job_id);
        RAISE NOTICE 'Deleted job % (gold.detect_events) before procedure replacement', _job_id;
    END LOOP;
END $$;

DROP PROCEDURE IF EXISTS gold.detect_events(integer, jsonb);

CREATE OR REPLACE PROCEDURE gold.detect_events(job_id INT, config JSONB)
LANGUAGE plpgsql AS $$
DECLARE
    last_run TIMESTAMPTZ;
    state_events_inserted INT := 0;
    crossing_events_inserted INT := 0;
BEGIN
    -- Get last successful run time
    SELECT last_successful_finish INTO last_run
    FROM timescaledb_information.job_stats
    WHERE timescaledb_information.job_stats.job_id = detect_events.job_id;

    -- Default to 2 hours ago if first run
    last_run := COALESCE(last_run, NOW() - INTERVAL '2 hours');

    -- =========================================================
    -- STATE TRANSITIONS
    -- =========================================================
    -- Insert new state transition events from Silver layer
    WITH new_transitions AS (
        SELECT
            s.event_time AS event_time,
            'home-assistant-state' AS stream_id,
            s.ndp_id AS entity_id,
            'state_transition' AS event_type,
            LAG(s.state) OVER (PARTITION BY s.ndp_id ORDER BY s.event_time) AS from_state,
            s.state AS to_state,
            EXTRACT(EPOCH FROM (s.event_time - LAG(s.event_time) OVER (PARTITION BY s.ndp_id ORDER BY s.event_time))) * 1000 AS duration_ms
        FROM silver.state_events s
        WHERE s.event_time > last_run
    ),
    actual_transitions AS (
        SELECT * FROM new_transitions
        WHERE from_state IS NOT NULL
          AND from_state IS DISTINCT FROM to_state
    )
    INSERT INTO gold.events (
        event_time, stream_id, entity_id, event_type,
        from_state, to_state, duration_in_state_ms,
        context, details
    )
    SELECT
        t.event_time,
        t.stream_id,
        t.entity_id,
        t.event_type,
        t.from_state,
        t.to_state,
        t.duration_ms::BIGINT,
        -- Context from aligned view at event's hourly bucket
        COALESCE(
            (SELECT jsonb_build_object(
                'indoor_co2', a.indoor_co2_mean,
                'indoor_humidity_pct', a.indoor_humidity_pct_mean,
                'indoor_nox_index', a.indoor_nox_index_mean,
                'indoor_pm10', a.indoor_pm10_mean,
                'indoor_pm25', a.indoor_pm25_mean,
                'indoor_temperature_c', a.indoor_temperature_c_mean,
                'indoor_tvoc_index', a.indoor_tvoc_index_mean,
                'outdoor_aqi_aqi_epa', a.outdoor_aqi_aqi_epa_mean,
                'outdoor_aqi_aqi_owm', a.outdoor_aqi_aqi_owm_mean,
                'outdoor_aqi_co_ugm3', a.outdoor_aqi_co_ugm3_mean,
                'outdoor_aqi_no2_ugm3', a.outdoor_aqi_no2_ugm3_mean,
                'outdoor_aqi_o3_ugm3', a.outdoor_aqi_o3_ugm3_mean,
                'outdoor_aqi_pm10', a.outdoor_aqi_pm10_mean,
                'outdoor_aqi_pm25', a.outdoor_aqi_pm25_mean,
                'outdoor_aqi_so2_ugm3', a.outdoor_aqi_so2_ugm3_mean,
                'outdoor_cloud_cover_pct', a.outdoor_cloud_cover_pct_mean,
                'outdoor_feels_like_c', a.outdoor_feels_like_c_mean,
                'outdoor_humidity_pct', a.outdoor_humidity_pct_mean,
                'outdoor_precipitation_mm', a.outdoor_precipitation_mm_mean,
                'outdoor_pressure_pa', a.outdoor_pressure_pa_mean,
                'outdoor_temperature_c', a.outdoor_temperature_c_mean,
                'outdoor_visibility_m', a.outdoor_visibility_m_mean,
                'outdoor_wind_speed_kmh', a.outdoor_wind_speed_kmh_mean,
                'state_state', a.state_state_count
            ) FROM gold.indoor_air_quality_aligned a
            WHERE a.bucket = time_bucket('1 hour', t.event_time)),
            '{}'::JSONB
        ),
        '{}'::JSONB
    FROM actual_transitions t
    ON CONFLICT DO NOTHING;

    GET DIAGNOSTICS state_events_inserted = ROW_COUNT;

    -- =========================================================
    -- THRESHOLD CROSSINGS
    -- =========================================================
    -- Insert new threshold crossing events
    -- (Uses objectives from domain config and compares consecutive observations)
    WITH hourly_obs AS (
        SELECT
            bucket,
            ndp_id AS entity_id,
            'air-quality'::TEXT AS stream_id,
            co2_mean AS co2_value,
            LAG(co2_mean) OVER (PARTITION BY ndp_id ORDER BY bucket) AS co2_prev,
            pm25_mean AS pm25_value,
            LAG(pm25_mean) OVER (PARTITION BY ndp_id ORDER BY bucket) AS pm25_prev,
            humidity_pct_mean AS humidity_pct_value,
            LAG(humidity_pct_mean) OVER (PARTITION BY ndp_id ORDER BY bucket) AS humidity_pct_prev,
            temperature_c_mean AS temperature_c_value,
            LAG(temperature_c_mean) OVER (PARTITION BY ndp_id ORDER BY bucket) AS temperature_c_prev
        FROM gold.air_quality_hourly
        WHERE bucket > last_run - INTERVAL '1 hour'
    ),
    healthy_co2_crossings AS (
        SELECT
            bucket AS event_time,
            stream_id,
            entity_id,
            'threshold_crossing' AS event_type,
            'co2' AS metric,
            800.0 AS threshold_value,
            CASE
                WHEN co2_prev < 800.0 AND co2_value >= 800.0 THEN 'rising'
                WHEN co2_prev >= 800.0 AND co2_value < 800.0 THEN 'falling'
            END AS crossing_direction,
            co2_value AS metric_value,
            co2_prev AS previous_metric_value,
            'healthy_co2' AS objective_id
        FROM hourly_obs
        WHERE bucket > last_run
          AND co2_prev IS NOT NULL
          AND co2_value IS NOT NULL
          AND (
              (co2_prev < 800.0 AND co2_value >= 800.0)
              OR (co2_prev >= 800.0 AND co2_value < 800.0)
          )
    ),
    healthy_pm25_crossings AS (
        SELECT
            bucket AS event_time,
            stream_id,
            entity_id,
            'threshold_crossing' AS event_type,
            'pm25' AS metric,
            12.0 AS threshold_value,
            CASE
                WHEN pm25_prev < 12.0 AND pm25_value >= 12.0 THEN 'rising'
                WHEN pm25_prev >= 12.0 AND pm25_value < 12.0 THEN 'falling'
            END AS crossing_direction,
            pm25_value AS metric_value,
            pm25_prev AS previous_metric_value,
            'healthy_pm25' AS objective_id
        FROM hourly_obs
        WHERE bucket > last_run
          AND pm25_prev IS NOT NULL
          AND pm25_value IS NOT NULL
          AND (
              (pm25_prev < 12.0 AND pm25_value >= 12.0)
              OR (pm25_prev >= 12.0 AND pm25_value < 12.0)
          )
    ),
    comfortable_humidity_min_crossings AS (
        SELECT
            bucket AS event_time,
            stream_id,
            entity_id,
            'threshold_crossing' AS event_type,
            'humidity_pct' AS metric,
            40.0 AS threshold_value,
            CASE
                WHEN humidity_pct_prev < 40.0 AND humidity_pct_value >= 40.0 THEN 'rising'
                WHEN humidity_pct_prev >= 40.0 AND humidity_pct_value < 40.0 THEN 'falling'
            END AS crossing_direction,
            humidity_pct_value AS metric_value,
            humidity_pct_prev AS previous_metric_value,
            'comfortable_humidity_min' AS objective_id
        FROM hourly_obs
        WHERE bucket > last_run
          AND humidity_pct_prev IS NOT NULL
          AND humidity_pct_value IS NOT NULL
          AND (
              (humidity_pct_prev < 40.0 AND humidity_pct_value >= 40.0)
              OR (humidity_pct_prev >= 40.0 AND humidity_pct_value < 40.0)
          )
    ),
    comfortable_humidity_max_crossings AS (
        SELECT
            bucket AS event_time,
            stream_id,
            entity_id,
            'threshold_crossing' AS event_type,
            'humidity_pct' AS metric,
            60.0 AS threshold_value,
            CASE
                WHEN humidity_pct_prev < 60.0 AND humidity_pct_value >= 60.0 THEN 'rising'
                WHEN humidity_pct_prev >= 60.0 AND humidity_pct_value < 60.0 THEN 'falling'
            END AS crossing_direction,
            humidity_pct_value AS metric_value,
            humidity_pct_prev AS previous_metric_value,
            'comfortable_humidity_max' AS objective_id
        FROM hourly_obs
        WHERE bucket > last_run
          AND humidity_pct_prev IS NOT NULL
          AND humidity_pct_value IS NOT NULL
          AND (
              (humidity_pct_prev < 60.0 AND humidity_pct_value >= 60.0)
              OR (humidity_pct_prev >= 60.0 AND humidity_pct_value < 60.0)
          )
    ),
    comfortable_temperature_min_crossings AS (
        SELECT
            bucket AS event_time,
            stream_id,
            entity_id,
            'threshold_crossing' AS event_type,
            'temperature_c' AS metric,
            20.0 AS threshold_value,
            CASE
                WHEN temperature_c_prev < 20.0 AND temperature_c_value >= 20.0 THEN 'rising'
                WHEN temperature_c_prev >= 20.0 AND temperature_c_value < 20.0 THEN 'falling'
            END AS crossing_direction,
            temperature_c_value AS metric_value,
            temperature_c_prev AS previous_metric_value,
            'comfortable_temperature_min' AS objective_id
        FROM hourly_obs
        WHERE bucket > last_run
          AND temperature_c_prev IS NOT NULL
          AND temperature_c_value IS NOT NULL
          AND (
              (temperature_c_prev < 20.0 AND temperature_c_value >= 20.0)
              OR (temperature_c_prev >= 20.0 AND temperature_c_value < 20.0)
          )
    ),
    comfortable_temperature_max_crossings AS (
        SELECT
            bucket AS event_time,
            stream_id,
            entity_id,
            'threshold_crossing' AS event_type,
            'temperature_c' AS metric,
            24.0 AS threshold_value,
            CASE
                WHEN temperature_c_prev < 24.0 AND temperature_c_value >= 24.0 THEN 'rising'
                WHEN temperature_c_prev >= 24.0 AND temperature_c_value < 24.0 THEN 'falling'
            END AS crossing_direction,
            temperature_c_value AS metric_value,
            temperature_c_prev AS previous_metric_value,
            'comfortable_temperature_max' AS objective_id
        FROM hourly_obs
        WHERE bucket > last_run
          AND temperature_c_prev IS NOT NULL
          AND temperature_c_value IS NOT NULL
          AND (
              (temperature_c_prev < 24.0 AND temperature_c_value >= 24.0)
              OR (temperature_c_prev >= 24.0 AND temperature_c_value < 24.0)
          )
    ),
    all_crossings AS (
        SELECT * FROM healthy_co2_crossings
        UNION ALL
        SELECT * FROM healthy_pm25_crossings
        UNION ALL
        SELECT * FROM comfortable_humidity_min_crossings
        UNION ALL
        SELECT * FROM comfortable_humidity_max_crossings
        UNION ALL
        SELECT * FROM comfortable_temperature_min_crossings
        UNION ALL
        SELECT * FROM comfortable_temperature_max_crossings
    )
    INSERT INTO gold.events (
        event_time, stream_id, entity_id, event_type,
        metric, threshold_value, crossing_direction,
        metric_value, previous_metric_value, objective_id,
        context, details
    )
    SELECT
        c.event_time,
        c.stream_id,
        c.entity_id,
        c.event_type,
        c.metric,
        c.threshold_value,
        c.crossing_direction,
        c.metric_value,
        c.previous_metric_value,
        c.objective_id,
        -- Context from aligned view at crossing time
        COALESCE(
            (SELECT jsonb_build_object(
                'indoor_co2', a.indoor_co2_mean,
                'indoor_humidity_pct', a.indoor_humidity_pct_mean,
                'indoor_nox_index', a.indoor_nox_index_mean,
                'indoor_pm10', a.indoor_pm10_mean,
                'indoor_pm25', a.indoor_pm25_mean,
                'indoor_temperature_c', a.indoor_temperature_c_mean,
                'indoor_tvoc_index', a.indoor_tvoc_index_mean,
                'outdoor_aqi_aqi_epa', a.outdoor_aqi_aqi_epa_mean,
                'outdoor_aqi_aqi_owm', a.outdoor_aqi_aqi_owm_mean,
                'outdoor_aqi_co_ugm3', a.outdoor_aqi_co_ugm3_mean,
                'outdoor_aqi_no2_ugm3', a.outdoor_aqi_no2_ugm3_mean,
                'outdoor_aqi_o3_ugm3', a.outdoor_aqi_o3_ugm3_mean,
                'outdoor_aqi_pm10', a.outdoor_aqi_pm10_mean,
                'outdoor_aqi_pm25', a.outdoor_aqi_pm25_mean,
                'outdoor_aqi_so2_ugm3', a.outdoor_aqi_so2_ugm3_mean,
                'outdoor_cloud_cover_pct', a.outdoor_cloud_cover_pct_mean,
                'outdoor_feels_like_c', a.outdoor_feels_like_c_mean,
                'outdoor_humidity_pct', a.outdoor_humidity_pct_mean,
                'outdoor_precipitation_mm', a.outdoor_precipitation_mm_mean,
                'outdoor_pressure_pa', a.outdoor_pressure_pa_mean,
                'outdoor_temperature_c', a.outdoor_temperature_c_mean,
                'outdoor_visibility_m', a.outdoor_visibility_m_mean,
                'outdoor_wind_speed_kmh', a.outdoor_wind_speed_kmh_mean,
                'state_state', a.state_state_count
            ) FROM gold.indoor_air_quality_aligned a
            WHERE a.bucket = c.event_time),
            '{}'::JSONB
        ),
        jsonb_build_object('condition', '<', 'unit', CASE c.metric WHEN 'co2' THEN 'ppm' WHEN 'pm25' THEN 'ug/m3' WHEN 'humidity_pct' THEN 'percent' WHEN 'humidity_pct' THEN 'percent' WHEN 'temperature_c' THEN 'celsius' WHEN 'temperature_c' THEN 'celsius' ELSE '' END)
    FROM all_crossings c
    ON CONFLICT DO NOTHING;

    GET DIAGNOSTICS crossing_events_inserted = ROW_COUNT;

    RAISE NOTICE 'Event detection: % state transitions, % threshold crossings',
        state_events_inserted, crossing_events_inserted;

    COMMIT;
END;
$$;

COMMENT ON PROCEDURE gold.detect_events IS
    'Detects state transitions and threshold crossings, inserts into gold.events with context snapshots.';

-- Schedule the detection job (every 15 minutes)
SELECT add_job(
    'gold.detect_events'::regproc,
    '15 minutes'::INTERVAL,
    config => '{}'::JSONB
);
