//! Trading strategies module
//! 
//! This module provides various trading strategies that can be
//! configured and executed by the autonomous trading agents.

pub mod momentum;

use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use thiserror::Error;

#[derive(Error, Debug)]
pub enum StrategyError {
    #[error("Configuration error: {0}")]
    Configuration(String),
    
    #[error("Execution error: {0}")]
    Execution(String),
    
    #[error("Insufficient data: {0}")]
    InsufficientData(String),
    
    #[error("Risk limit exceeded: {0}")]
    RiskLimitExceeded(String),
}

/// Trading signal generated by strategies
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum Signal {
    Buy {
        confidence: f64,
        size: f64,
        reason: String,
    },
    Sell {
        confidence: f64,
        size: f64,
        reason: String,
    },
    Hold {
        reason: String,
    },
}

/// Position information
#[derive(Debug, Clone)]
pub struct Position {
    pub symbol: String,
    pub side: PositionSide,
    pub size: f64,
    pub entry_price: f64,
    pub current_price: f64,
    pub unrealized_pnl: f64,
    pub timestamp: i64,
}

#[derive(Debug, Clone)]
pub enum PositionSide {
    Long,
    Short,
}

/// Market context for strategy execution
#[derive(Debug, Clone)]
pub struct MarketContext {
    pub symbol: String,
    pub current_price: f64,
    pub bid: f64,
    pub ask: f64,
    pub volume_24h: f64,
    pub volatility: f64,
    pub timestamp: i64,
}

/// Strategy configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StrategyConfig {
    pub name: String,
    pub enabled: bool,
    pub risk_limit: f64,
    pub position_size: f64,
    pub parameters: HashMap<String, serde_json::Value>,
}

/// Common trait for all trading strategies
#[async_trait]
pub trait TradingStrategy: Send + Sync {
    /// Get strategy name
    fn name(&self) -> &str;
    
    /// Initialize strategy with configuration
    async fn initialize(&mut self, config: StrategyConfig) -> Result<(), StrategyError>;
    
    /// Generate trading signal based on market context
    async fn generate_signal(
        &self,
        context: &MarketContext,
        position: Option<&Position>,
    ) -> Result<Signal, StrategyError>;
    
    /// Update strategy parameters
    async fn update_parameters(
        &mut self,
        parameters: HashMap<String, serde_json::Value>,
    ) -> Result<(), StrategyError>;
    
    /// Get current strategy metrics
    fn get_metrics(&self) -> HashMap<String, f64>;
    
    /// Validate if strategy can execute in current conditions
    fn can_execute(&self, context: &MarketContext) -> Result<bool, StrategyError>;
}

/// Strategy factory for creating strategy instances
pub struct StrategyFactory;

impl StrategyFactory {
    /// Create a strategy instance from configuration
    pub fn create_strategy(config: &StrategyConfig) -> Result<Box<dyn TradingStrategy>, StrategyError> {
        match config.name.as_str() {
            "momentum" => Ok(Box::new(momentum::MomentumStrategy::new())),
            // Add more strategies here
            _ => Err(StrategyError::Configuration(format!(
                "Unknown strategy: {}",
                config.name
            ))),
        }
    }
}

/// Strategy performance metrics
#[derive(Debug, Clone, Default)]
pub struct StrategyMetrics {
    pub total_trades: u64,
    pub winning_trades: u64,
    pub losing_trades: u64,
    pub total_pnl: f64,
    pub sharpe_ratio: f64,
    pub max_drawdown: f64,
    pub win_rate: f64,
}

impl StrategyMetrics {
    /// Update metrics with a completed trade
    pub fn update_trade(&mut self, pnl: f64) {
        self.total_trades += 1;
        if pnl > 0.0 {
            self.winning_trades += 1;
        } else if pnl < 0.0 {
            self.losing_trades += 1;
        }
        self.total_pnl += pnl;
        self.win_rate = self.winning_trades as f64 / self.total_trades as f64;
    }
}