//! Sync planner for idempotent continuous aggregate deployment
//!
//! The SyncPlanner checks database state and generates only the DDL
//! that needs to be executed, making deployments truly idempotent.

use crate::gold::config::{AggregatesConfig, GoldEtlConfig, RefreshPolicyConfig, StreamConfig};
use crate::gold::db::CaChecker;
use crate::gold::error::{GoldDdlError, Result};
use crate::gold::generators::ContinuousAggregateGenerator;
use crate::gold::validation::granularity_to_suffix;

/// Action to take for a continuous aggregate
#[derive(Debug, Clone, PartialEq)]
pub enum CaAction {
    /// Create new CA (doesn't exist)
    Create,
    /// Skip (already exists)
    Skip,
    /// Recreate (drop and create - for schema changes)
    Recreate,
}

/// Plan for a single continuous aggregate
#[derive(Debug, Clone)]
pub struct CaPlan {
    pub schema: String,
    pub name: String,
    pub granularity: String,
    pub action: CaAction,
    pub create_ddl: Option<String>,
    pub policy_ddl: Option<String>,
    pub needs_policy: bool,
}

/// Complete sync plan for a stream's Gold layer
#[derive(Debug)]
pub struct SyncPlan {
    pub stream_id: String,
    pub schema_ddl: String,
    pub ca_plans: Vec<CaPlan>,
}

impl SyncPlan {
    /// Generate the final DDL to execute
    ///
    /// Only includes DDL for CAs that need to be created
    pub fn to_ddl(&self) -> String {
        let mut parts = Vec::new();

        // Header
        parts.push(format!("-- Gold layer DDL for stream: {}", self.stream_id));
        parts.push("-- Generated by ndp-gold-ddl".to_string());
        parts.push(String::new());

        // Schema creation (always safe to run)
        parts.push(self.schema_ddl.clone());
        parts.push(String::new());

        // Process each CA
        for plan in &self.ca_plans {
            match plan.action {
                CaAction::Create => {
                    parts.push(format!(
                        "-- Creating {}.{} (does not exist)",
                        plan.schema, plan.name
                    ));
                    if let Some(ddl) = &plan.create_ddl {
                        parts.push(ddl.clone());
                    }
                    parts.push(String::new());

                    // Add policy if needed
                    if plan.needs_policy {
                        if let Some(policy) = &plan.policy_ddl {
                            parts.push(policy.clone());
                            parts.push(String::new());
                        }
                    }
                }
                CaAction::Skip => {
                    parts.push(format!(
                        "-- Skipping {}.{} (already exists)",
                        plan.schema, plan.name
                    ));

                    // Still add policy if missing
                    if plan.needs_policy {
                        if let Some(policy) = &plan.policy_ddl {
                            parts.push(format!(
                                "-- Adding refresh policy for {}.{}",
                                plan.schema, plan.name
                            ));
                            parts.push(policy.clone());
                        }
                    }
                    parts.push(String::new());
                }
                CaAction::Recreate => {
                    parts.push(format!(
                        "-- Recreating {}.{} (schema change)",
                        plan.schema, plan.name
                    ));
                    parts.push(format!(
                        "DROP MATERIALIZED VIEW IF EXISTS {}.{} CASCADE;",
                        plan.schema, plan.name
                    ));
                    parts.push(String::new());
                    if let Some(ddl) = &plan.create_ddl {
                        parts.push(ddl.clone());
                    }
                    parts.push(String::new());

                    // Re-add policy after recreate
                    if let Some(policy) = &plan.policy_ddl {
                        parts.push(policy.clone());
                        parts.push(String::new());
                    }
                }
            }
        }

        parts.join("\n")
    }

    /// Check if any work needs to be done
    pub fn has_work(&self) -> bool {
        self.ca_plans
            .iter()
            .any(|p| p.action != CaAction::Skip || p.needs_policy)
    }

    /// Get summary of planned actions
    pub fn summary(&self) -> String {
        let creates = self
            .ca_plans
            .iter()
            .filter(|p| p.action == CaAction::Create)
            .count();
        let skips = self
            .ca_plans
            .iter()
            .filter(|p| p.action == CaAction::Skip)
            .count();
        let recreates = self
            .ca_plans
            .iter()
            .filter(|p| p.action == CaAction::Recreate)
            .count();
        let policies = self.ca_plans.iter().filter(|p| p.needs_policy).count();

        format!(
            "Stream '{}': {} to create, {} to skip, {} to recreate, {} policies to add",
            self.stream_id, creates, skips, recreates, policies
        )
    }
}

/// Planner for sync mode deployment
pub struct SyncPlanner<'a, C: CaChecker> {
    checker: &'a C,
    stream_config: &'a StreamConfig,
}

impl<'a, C: CaChecker> SyncPlanner<'a, C> {
    pub fn new(checker: &'a C, stream_config: &'a StreamConfig) -> Self {
        Self {
            checker,
            stream_config,
        }
    }

    /// Create a sync plan by checking database state
    pub async fn plan(&self, gold_etl: &GoldEtlConfig) -> Result<SyncPlan> {
        let aggregates =
            gold_etl
                .aggregates
                .as_ref()
                .ok_or_else(|| GoldDdlError::MissingRequiredField {
                    field: "gold_etl.aggregates".to_string(),
                    context: format!("stream '{}'", self.stream_config.stream_id),
                })?;

        let generator = ContinuousAggregateGenerator::from_stream_config(self.stream_config)?;

        let mut ca_plans = Vec::new();

        for granularity in &aggregates.granularities {
            let plan = self
                .plan_for_granularity(
                    &generator,
                    aggregates,
                    granularity,
                    gold_etl.refresh_policy.as_ref(),
                )
                .await?;
            ca_plans.push(plan);
        }

        Ok(SyncPlan {
            stream_id: self.stream_config.stream_id.clone(),
            schema_ddl: "CREATE SCHEMA IF NOT EXISTS gold;".to_string(),
            ca_plans,
        })
    }

    async fn plan_for_granularity(
        &self,
        generator: &ContinuousAggregateGenerator,
        aggregates: &AggregatesConfig,
        granularity: &str,
        refresh_policy: Option<&RefreshPolicyConfig>,
    ) -> Result<CaPlan> {
        let suffix = granularity_to_suffix(granularity);
        let view_name = format!(
            "{}_{}",
            self.stream_config.stream_id.replace('-', "_"),
            suffix
        );
        let schema = "gold";

        // Check if CA exists
        let ca_exists = self
            .checker
            .ca_exists(schema, &view_name)
            .await
            .map_err(|e| GoldDdlError::DatabaseError(e.to_string()))?;

        // Check if policy exists
        let policy_exists = if ca_exists {
            self.checker
                .refresh_policy_exists(schema, &view_name)
                .await
                .map_err(|e| GoldDdlError::DatabaseError(e.to_string()))?
        } else {
            false
        };

        // Generate DDL (we need it for create/recreate)
        let create_ddl = generator.generate_ca_ddl_only(aggregates, granularity)?;
        let policy_ddl = generator.generate_policy_ddl_only(granularity, refresh_policy)?;

        let action = if ca_exists {
            CaAction::Skip
        } else {
            CaAction::Create
        };

        Ok(CaPlan {
            schema: schema.to_string(),
            name: view_name,
            granularity: granularity.to_string(),
            action,
            create_ddl: Some(create_ddl),
            policy_ddl: Some(policy_ddl),
            needs_policy: !policy_exists,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::gold::config::{FieldMetricsConfig, SilverEtlConfig, TimestampConfig};
    use crate::gold::db::CaInfo;
    use crate::gold::error::GoldDdlError;
    use async_trait::async_trait;
    use std::collections::HashMap;

    // Mock CaChecker for testing
    struct MockCaChecker {
        existing_cas: HashMap<String, bool>,
        existing_policies: HashMap<String, bool>,
    }

    impl MockCaChecker {
        fn new() -> Self {
            Self {
                existing_cas: HashMap::new(),
                existing_policies: HashMap::new(),
            }
        }

        fn with_ca(mut self, schema: &str, name: &str) -> Self {
            self.existing_cas
                .insert(format!("{}.{}", schema, name), true);
            self
        }

        fn with_policy(mut self, schema: &str, name: &str) -> Self {
            self.existing_policies
                .insert(format!("{}.{}", schema, name), true);
            self
        }
    }

    #[async_trait]
    impl CaChecker for MockCaChecker {
        async fn ca_exists(
            &self,
            schema: &str,
            name: &str,
        ) -> std::result::Result<bool, GoldDdlError> {
            Ok(self
                .existing_cas
                .contains_key(&format!("{}.{}", schema, name)))
        }

        async fn get_ca_info(
            &self,
            _schema: &str,
            _name: &str,
        ) -> std::result::Result<Option<CaInfo>, GoldDdlError> {
            Ok(None)
        }

        async fn list_cas_in_schema(
            &self,
            _schema: &str,
        ) -> std::result::Result<Vec<CaInfo>, GoldDdlError> {
            Ok(vec![])
        }

        async fn refresh_policy_exists(
            &self,
            schema: &str,
            name: &str,
        ) -> std::result::Result<bool, GoldDdlError> {
            Ok(self
                .existing_policies
                .contains_key(&format!("{}.{}", schema, name)))
        }
    }

    fn create_test_stream_config() -> StreamConfig {
        StreamConfig {
            stream_id: "air-quality".to_string(),
            stream_type: None,
            fields: vec![],
            silver_etl: Some(SilverEtlConfig {
                target_table: "silver.air_quality_observations".to_string(),
                timestamp: Some(TimestampConfig {
                    target_field: "observation_time".to_string(),
                }),
            }),
            gold_etl: Some(GoldEtlConfig {
                enabled: true,
                aggregates: Some(AggregatesConfig {
                    granularities: vec!["1 hour".to_string(), "1 day".to_string()],
                    fields: {
                        let mut map = HashMap::new();
                        map.insert(
                            "pm25".to_string(),
                            FieldMetricsConfig {
                                metrics: vec!["mean".to_string(), "max".to_string()],
                            },
                        );
                        map
                    },
                }),
                features: None,
                refresh_policy: None,
            }),
        }
    }

    #[tokio::test]
    async fn test_plan_creates_both_cas_when_none_exist() {
        let checker = MockCaChecker::new();
        let stream_config = create_test_stream_config();
        let gold_etl = stream_config.gold_etl.as_ref().unwrap();

        let planner = SyncPlanner::new(&checker, &stream_config);
        let plan = planner.plan(gold_etl).await.unwrap();

        assert_eq!(plan.ca_plans.len(), 2);
        assert_eq!(plan.ca_plans[0].action, CaAction::Create);
        assert_eq!(plan.ca_plans[1].action, CaAction::Create);
        assert!(plan.has_work());
    }

    #[tokio::test]
    async fn test_plan_skips_existing_ca() {
        let checker = MockCaChecker::new()
            .with_ca("gold", "air_quality_hourly")
            .with_policy("gold", "air_quality_hourly");

        let stream_config = create_test_stream_config();
        let gold_etl = stream_config.gold_etl.as_ref().unwrap();

        let planner = SyncPlanner::new(&checker, &stream_config);
        let plan = planner.plan(gold_etl).await.unwrap();

        assert_eq!(plan.ca_plans.len(), 2);
        // Hourly should be skipped
        assert_eq!(plan.ca_plans[0].name, "air_quality_hourly");
        assert_eq!(plan.ca_plans[0].action, CaAction::Skip);
        assert!(!plan.ca_plans[0].needs_policy); // Policy exists

        // Daily should be created
        assert_eq!(plan.ca_plans[1].name, "air_quality_daily");
        assert_eq!(plan.ca_plans[1].action, CaAction::Create);
    }

    #[tokio::test]
    async fn test_plan_adds_missing_policy() {
        let checker = MockCaChecker::new().with_ca("gold", "air_quality_hourly");
        // Note: CA exists but policy doesn't

        let stream_config = create_test_stream_config();
        let gold_etl = stream_config.gold_etl.as_ref().unwrap();

        let planner = SyncPlanner::new(&checker, &stream_config);
        let plan = planner.plan(gold_etl).await.unwrap();

        // Hourly should be skipped but needs policy
        assert_eq!(plan.ca_plans[0].action, CaAction::Skip);
        assert!(plan.ca_plans[0].needs_policy);
        assert!(plan.has_work()); // Still has work due to missing policy
    }

    #[tokio::test]
    async fn test_plan_no_work_when_all_exists() {
        let checker = MockCaChecker::new()
            .with_ca("gold", "air_quality_hourly")
            .with_policy("gold", "air_quality_hourly")
            .with_ca("gold", "air_quality_daily")
            .with_policy("gold", "air_quality_daily");

        let stream_config = create_test_stream_config();
        let gold_etl = stream_config.gold_etl.as_ref().unwrap();

        let planner = SyncPlanner::new(&checker, &stream_config);
        let plan = planner.plan(gold_etl).await.unwrap();

        assert!(!plan.has_work());
        assert_eq!(plan.ca_plans[0].action, CaAction::Skip);
        assert_eq!(plan.ca_plans[1].action, CaAction::Skip);
    }

    #[tokio::test]
    async fn test_to_ddl_includes_creates() {
        let checker = MockCaChecker::new();
        let stream_config = create_test_stream_config();
        let gold_etl = stream_config.gold_etl.as_ref().unwrap();

        let planner = SyncPlanner::new(&checker, &stream_config);
        let plan = planner.plan(gold_etl).await.unwrap();
        let ddl = plan.to_ddl();

        assert!(ddl.contains("CREATE SCHEMA IF NOT EXISTS gold"));
        assert!(ddl.contains("Creating gold.air_quality_hourly"));
        assert!(ddl.contains("Creating gold.air_quality_daily"));
        assert!(ddl.contains("CREATE MATERIALIZED VIEW"));
    }

    #[tokio::test]
    async fn test_to_ddl_includes_skips() {
        let checker = MockCaChecker::new()
            .with_ca("gold", "air_quality_hourly")
            .with_policy("gold", "air_quality_hourly");

        let stream_config = create_test_stream_config();
        let gold_etl = stream_config.gold_etl.as_ref().unwrap();

        let planner = SyncPlanner::new(&checker, &stream_config);
        let plan = planner.plan(gold_etl).await.unwrap();
        let ddl = plan.to_ddl();

        assert!(ddl.contains("Skipping gold.air_quality_hourly"));
        assert!(ddl.contains("Creating gold.air_quality_daily"));
    }

    #[test]
    fn test_summary_format() {
        let plan = SyncPlan {
            stream_id: "test".to_string(),
            schema_ddl: String::new(),
            ca_plans: vec![
                CaPlan {
                    schema: "gold".to_string(),
                    name: "test_hourly".to_string(),
                    granularity: "1 hour".to_string(),
                    action: CaAction::Create,
                    create_ddl: None,
                    policy_ddl: None,
                    needs_policy: true,
                },
                CaPlan {
                    schema: "gold".to_string(),
                    name: "test_daily".to_string(),
                    granularity: "1 day".to_string(),
                    action: CaAction::Skip,
                    create_ddl: None,
                    policy_ddl: None,
                    needs_policy: false,
                },
            ],
        };

        let summary = plan.summary();
        assert!(summary.contains("1 to create"));
        assert!(summary.contains("1 to skip"));
        assert!(summary.contains("1 policies to add"));
    }
}
