-- Events hypertable DDL for domain: indoor-air-quality
-- Generated by ndp-gold-ddl
-- Mode: recreate

CREATE SCHEMA IF NOT EXISTS gold;

-- Drop existing events infrastructure
DROP VIEW IF EXISTS gold.events_unified CASCADE;
DROP MATERIALIZED VIEW IF EXISTS gold.events_hourly_by_entity CASCADE;
DROP MATERIALIZED VIEW IF EXISTS gold.events_hourly CASCADE;
DROP TABLE IF EXISTS gold.events CASCADE;

-- Events hypertable
CREATE TABLE gold.events (
    -- Identity
    event_id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    event_time TIMESTAMPTZ NOT NULL,

    -- Event classification
    stream_id TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    event_type TEXT NOT NULL,

    -- State transition fields (NULL for threshold crossings)
    from_state TEXT,
    to_state TEXT,
    duration_in_state_ms BIGINT,

    -- Threshold crossing fields (NULL for state transitions)
    metric TEXT,
    threshold_value DOUBLE PRECISION,
    crossing_direction TEXT,
    metric_value DOUBLE PRECISION,
    previous_metric_value DOUBLE PRECISION,
    objective_id TEXT,

    -- Context snapshot at event time (for correlation)
    context JSONB NOT NULL DEFAULT '{}'::JSONB,

    -- Extensible details
    details JSONB NOT NULL DEFAULT '{}'::JSONB
);

-- Convert to hypertable
SELECT create_hypertable('gold.events', 'event_time',
    chunk_time_interval => INTERVAL '7 days',
    if_not_exists => TRUE
);

COMMENT ON TABLE gold.events IS
    'Events hypertable: state transitions and threshold crossings with context snapshots. For V1.2 Pattern Detection.';

-- Indexes for V1.2 query patterns
CREATE INDEX IF NOT EXISTS idx_events_time
    ON gold.events (event_time DESC);

CREATE INDEX IF NOT EXISTS idx_events_type_time
    ON gold.events (event_type, event_time DESC);

CREATE INDEX IF NOT EXISTS idx_events_entity_time
    ON gold.events (entity_id, event_time DESC);

CREATE INDEX IF NOT EXISTS idx_events_objective
    ON gold.events (objective_id, event_time DESC)
    WHERE event_type = 'threshold_crossing';

CREATE INDEX IF NOT EXISTS idx_events_context
    ON gold.events USING GIN (context);

CREATE INDEX IF NOT EXISTS idx_events_details
    ON gold.events USING GIN (details);

-- Retention policy (1 year)
SELECT add_retention_policy('gold.events', INTERVAL '1 year', if_not_exists => TRUE);

-- Unified events view for V1.2 API compatibility
CREATE OR REPLACE VIEW gold.events_unified AS
SELECT
    event_id,
    event_time,
    stream_id,
    entity_id,
    event_type,
    -- Build details JSONB for backward compatibility
    CASE event_type
        WHEN 'state_transition' THEN
            jsonb_build_object(
                'from_state', from_state,
                'to_state', to_state,
                'duration_in_previous_ms', duration_in_state_ms
            )
        WHEN 'threshold_crossing' THEN
            jsonb_build_object(
                'metric', metric,
                'threshold', threshold_value,
                'direction', crossing_direction,
                'value', metric_value,
                'previous_value', previous_metric_value,
                'objective_id', objective_id
            )
        ELSE details
    END AS details,
    context
FROM gold.events
ORDER BY event_time, event_type, event_id;

COMMENT ON VIEW gold.events_unified IS
    'V1.2 API view on events hypertable. Provides backward-compatible schema.';

-- Hourly events continuous aggregate (recreate)
DROP MATERIALIZED VIEW IF EXISTS gold.events_hourly CASCADE;

CREATE MATERIALIZED VIEW gold.events_hourly
WITH (timescaledb.continuous) AS
SELECT
    time_bucket('1 hour', event_time) AS bucket,
    COUNT(*) AS total_events,
    COUNT(*) FILTER (WHERE event_type = 'state_transition') AS state_transition_count,
    COUNT(*) FILTER (WHERE event_type = 'threshold_crossing') AS threshold_crossing_count,
    COUNT(DISTINCT entity_id) AS distinct_entities_with_events
FROM gold.events
GROUP BY bucket
WITH NO DATA;

-- Refresh policy for events hourly aggregate
SELECT add_continuous_aggregate_policy('gold.events_hourly',
    start_offset => INTERVAL '3 hours',
    end_offset => INTERVAL '1 hour',
    schedule_interval => INTERVAL '15 minutes',
    if_not_exists => TRUE
);

-- Index for time range queries
CREATE INDEX IF NOT EXISTS idx_events_hourly_bucket
    ON gold.events_hourly (bucket DESC);

-- Hourly events by entity continuous aggregate (recreate)
DROP MATERIALIZED VIEW IF EXISTS gold.events_hourly_by_entity CASCADE;

CREATE MATERIALIZED VIEW gold.events_hourly_by_entity
WITH (timescaledb.continuous) AS
SELECT
    time_bucket('1 hour', event_time) AS bucket,
    entity_id,
    stream_id,
    COUNT(*) AS total_events,
    COUNT(*) FILTER (WHERE event_type = 'state_transition') AS state_transition_count,
    COUNT(*) FILTER (WHERE event_type = 'threshold_crossing') AS threshold_crossing_count
FROM gold.events
GROUP BY bucket, entity_id, stream_id
WITH NO DATA;

-- Refresh policy for events hourly by entity aggregate
SELECT add_continuous_aggregate_policy('gold.events_hourly_by_entity',
    start_offset => INTERVAL '3 hours',
    end_offset => INTERVAL '1 hour',
    schedule_interval => INTERVAL '15 minutes',
    if_not_exists => TRUE
);

-- Indexes for events hourly by entity
CREATE INDEX IF NOT EXISTS idx_events_hourly_by_entity_bucket
    ON gold.events_hourly_by_entity (bucket DESC);

CREATE INDEX IF NOT EXISTS idx_events_hourly_by_entity_entity_bucket
    ON gold.events_hourly_by_entity (entity_id, bucket DESC);

-- Event detection procedure (runs as TimescaleDB job)
-- Delete dependent jobs and DROP procedure to avoid "cannot remove parameter defaults" error
DO $$
DECLARE
    _job_id INTEGER;
BEGIN
    FOR _job_id IN
        SELECT job_id FROM timescaledb_information.jobs
        WHERE proc_schema = 'gold' AND proc_name = 'detect_events'
    LOOP
        PERFORM delete_job(_job_id);
        RAISE NOTICE 'Deleted job % (gold.detect_events) before procedure replacement', _job_id;
    END LOOP;
END $$;

DROP PROCEDURE IF EXISTS gold.detect_events(integer, jsonb);

CREATE OR REPLACE PROCEDURE gold.detect_events(job_id INT, config JSONB)
LANGUAGE plpgsql AS $$
DECLARE
    last_run TIMESTAMPTZ;
    state_events_inserted INT := 0;
    crossing_events_inserted INT := 0;
BEGIN
    -- Get last successful run time
    SELECT last_successful_finish INTO last_run
    FROM timescaledb_information.job_stats
    WHERE job_id = detect_events.job_id;

    -- Default to 2 hours ago if first run
    last_run := COALESCE(last_run, NOW() - INTERVAL '2 hours');

    -- =========================================================
    -- STATE TRANSITIONS
    -- =========================================================
    -- Insert new state transition events from Silver layer
    WITH new_transitions AS (
        SELECT
            s.event_time AS event_time,
            'home-assistant-state' AS stream_id,
            s.ndp_id AS entity_id,
            'state_transition' AS event_type,
            LAG(s.state) OVER (PARTITION BY s.ndp_id ORDER BY s.event_time) AS from_state,
            s.state AS to_state,
            EXTRACT(EPOCH FROM (s.event_time - LAG(s.event_time) OVER (PARTITION BY s.ndp_id ORDER BY s.event_time))) * 1000 AS duration_ms
        FROM silver.home_assistant_state s
        WHERE s.event_time > last_run
    ),
    actual_transitions AS (
        SELECT * FROM new_transitions
        WHERE from_state IS NOT NULL
          AND from_state IS DISTINCT FROM to_state
    )
    INSERT INTO gold.events (
        event_time, stream_id, entity_id, event_type,
        from_state, to_state, duration_in_state_ms,
        context, details
    )
    SELECT
        t.event_time,
        t.stream_id,
        t.entity_id,
        t.event_type,
        t.from_state,
        t.to_state,
        t.duration_ms::BIGINT,
        -- Context from aligned view at event's hourly bucket
        COALESCE(
            (SELECT jsonb_build_object(
                'indoor_co2', a.indoor_co2_mean,
                'indoor_pm25', a.indoor_pm25_mean,
                'indoor_temp', a.indoor_temperature_c_mean,
                'outdoor_temp', a.outdoor_temperature_c_mean,
                'outdoor_pm25', a.outdoor_aqi_pm25_mean,
                'window_state', a.state_state_last
            ) FROM gold.indoor_air_quality_aligned a
            WHERE a.bucket = time_bucket('1 hour', t.event_time)),
            '{}'::JSONB
        ),
        '{}'::JSONB
    FROM actual_transitions t
    ON CONFLICT DO NOTHING;

    GET DIAGNOSTICS state_events_inserted = ROW_COUNT;

    -- =========================================================
    -- THRESHOLD CROSSINGS
    -- =========================================================
    -- Insert new threshold crossing events
    -- (Uses objectives from domain config and compares consecutive observations)
    WITH hourly_obs AS (
        SELECT
            bucket,
            ndp_id AS entity_id,
            'air-quality'::TEXT AS stream_id,
            co2_mean AS co2_value,
            LAG(co2_mean) OVER (PARTITION BY ndp_id ORDER BY bucket) AS co2_prev,
            pm25_mean AS pm25_value,
            LAG(pm25_mean) OVER (PARTITION BY ndp_id ORDER BY bucket) AS pm25_prev
        FROM gold.air_quality_hourly
        WHERE bucket > last_run - INTERVAL '1 hour'
    ),
    co2_crossings AS (
        SELECT
            bucket AS event_time,
            stream_id,
            entity_id,
            'threshold_crossing' AS event_type,
            'co2' AS metric,
            800.0 AS threshold_value,
            CASE
                WHEN co2_prev < 800 AND co2_value >= 800 THEN 'rising'
                WHEN co2_prev >= 800 AND co2_value < 800 THEN 'falling'
            END AS crossing_direction,
            co2_value AS metric_value,
            co2_prev AS previous_metric_value,
            'healthy_co2' AS objective_id
        FROM hourly_obs
        WHERE bucket > last_run
          AND co2_prev IS NOT NULL
          AND co2_value IS NOT NULL
          AND (
              (co2_prev < 800 AND co2_value >= 800)
              OR (co2_prev >= 800 AND co2_value < 800)
          )
    ),
    pm25_crossings AS (
        SELECT
            bucket AS event_time,
            stream_id,
            entity_id,
            'threshold_crossing' AS event_type,
            'pm25' AS metric,
            12.0 AS threshold_value,
            CASE
                WHEN pm25_prev < 12 AND pm25_value >= 12 THEN 'rising'
                WHEN pm25_prev >= 12 AND pm25_value < 12 THEN 'falling'
            END AS crossing_direction,
            pm25_value AS metric_value,
            pm25_prev AS previous_metric_value,
            'healthy_pm25' AS objective_id
        FROM hourly_obs
        WHERE bucket > last_run
          AND pm25_prev IS NOT NULL
          AND pm25_value IS NOT NULL
          AND (
              (pm25_prev < 12 AND pm25_value >= 12)
              OR (pm25_prev >= 12 AND pm25_value < 12)
          )
    ),
    all_crossings AS (
        SELECT * FROM co2_crossings
        UNION ALL
        SELECT * FROM pm25_crossings
    )
    INSERT INTO gold.events (
        event_time, stream_id, entity_id, event_type,
        metric, threshold_value, crossing_direction,
        metric_value, previous_metric_value, objective_id,
        context, details
    )
    SELECT
        c.event_time,
        c.stream_id,
        c.entity_id,
        c.event_type,
        c.metric,
        c.threshold_value,
        c.crossing_direction,
        c.metric_value,
        c.previous_metric_value,
        c.objective_id,
        -- Context from aligned view at crossing time
        COALESCE(
            (SELECT jsonb_build_object(
                'indoor_co2', a.indoor_co2_mean,
                'indoor_pm25', a.indoor_pm25_mean,
                'indoor_temp', a.indoor_temperature_c_mean,
                'outdoor_temp', a.outdoor_temperature_c_mean,
                'outdoor_pm25', a.outdoor_aqi_pm25_mean,
                'window_state', a.state_state_last
            ) FROM gold.indoor_air_quality_aligned a
            WHERE a.bucket = c.event_time),
            '{}'::JSONB
        ),
        jsonb_build_object('condition', '<', 'unit', CASE c.metric WHEN 'co2' THEN 'ppm' ELSE 'ug/m3' END)
    FROM all_crossings c
    ON CONFLICT DO NOTHING;

    GET DIAGNOSTICS crossing_events_inserted = ROW_COUNT;

    RAISE NOTICE 'Event detection: % state transitions, % threshold crossings',
        state_events_inserted, crossing_events_inserted;

    COMMIT;
END;
$$;

COMMENT ON PROCEDURE gold.detect_events IS
    'Detects state transitions and threshold crossings, inserts into gold.events with context snapshots.';

-- Schedule the detection job (every 15 minutes)
SELECT add_job(
    'gold.detect_events'::regproc,
    '15 minutes'::INTERVAL,
    config => '{}'::JSONB
);
