-- Gold layer DDL for stream: outdoor-air-quality
-- Generated by ndp-gold-ddl

CREATE SCHEMA IF NOT EXISTS gold;

-- Sync mode: Create if not exists
-- CA-SYNC-CHECK: schema=gold name=outdoor_air_quality_hourly
CREATE MATERIALIZED VIEW gold.outdoor_air_quality_hourly
WITH (timescaledb.continuous) AS
SELECT
    time_bucket('1 hour', observation_time) AS bucket,
    ndp_id,
    AVG(pm10) AS pm10_mean,
    MIN(pm10) AS pm10_min,
    MAX(pm10) AS pm10_max,
    AVG(aqi_epa) AS aqi_epa_mean,
    MIN(aqi_epa) AS aqi_epa_min,
    MAX(aqi_epa) AS aqi_epa_max,
    AVG(co_ugm3) AS co_ugm3_mean,
    MAX(co_ugm3) AS co_ugm3_max,
    AVG(o3_ugm3) AS o3_ugm3_mean,
    MAX(o3_ugm3) AS o3_ugm3_max,
    AVG(pm25) AS pm25_mean,
    STDDEV(pm25) AS pm25_std,
    MIN(pm25) AS pm25_min,
    MAX(pm25) AS pm25_max,
    PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY pm25) AS pm25_p95,
    AVG(aqi_owm) AS aqi_owm_mean,
    MIN(aqi_owm) AS aqi_owm_min,
    MAX(aqi_owm) AS aqi_owm_max,
    AVG(no2_ugm3) AS no2_ugm3_mean,
    MAX(no2_ugm3) AS no2_ugm3_max,
    AVG(so2_ugm3) AS so2_ugm3_mean,
    MAX(so2_ugm3) AS so2_ugm3_max,
    COUNT(*) AS sample_count
FROM silver.outdoor_air_quality
GROUP BY bucket, ndp_id;

-- Refresh policy for gold.outdoor_air_quality_hourly
SELECT add_continuous_aggregate_policy('gold.outdoor_air_quality_hourly',
    start_offset => INTERVAL '4 hours',
    end_offset => INTERVAL '15 minutes',
    schedule_interval => INTERVAL '15 minutes',
    if_not_exists => TRUE
);

