-- Gold layer DDL for stream: air-quality
-- Generated by ndp-gold-ddl

CREATE SCHEMA IF NOT EXISTS gold;

-- Sync mode: Create if not exists
-- CA-SYNC-CHECK: schema=gold name=air_quality_hourly
CREATE MATERIALIZED VIEW gold.air_quality_hourly
WITH (timescaledb.continuous) AS
SELECT
    time_bucket('1 hour', observation_time) AS bucket,
    ndp_id,
    AVG(co2) AS co2_mean,
    STDDEV(co2) AS co2_std,
    MIN(co2) AS co2_min,
    MAX(co2) AS co2_max,
    AVG(temperature_c) AS temperature_c_mean,
    MIN(temperature_c) AS temperature_c_min,
    MAX(temperature_c) AS temperature_c_max,
    AVG(humidity_pct) AS humidity_pct_mean,
    MIN(humidity_pct) AS humidity_pct_min,
    MAX(humidity_pct) AS humidity_pct_max,
    AVG(pm25) AS pm25_mean,
    STDDEV(pm25) AS pm25_std,
    MIN(pm25) AS pm25_min,
    MAX(pm25) AS pm25_max,
    PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY pm25) AS pm25_p95,
    AVG(nox_index) AS nox_index_mean,
    MAX(nox_index) AS nox_index_max,
    AVG(tvoc_index) AS tvoc_index_mean,
    MAX(tvoc_index) AS tvoc_index_max,
    AVG(pm10) AS pm10_mean,
    MIN(pm10) AS pm10_min,
    MAX(pm10) AS pm10_max,
    COUNT(*) AS sample_count
FROM silver.air_quality_observations
GROUP BY bucket, ndp_id;

-- Sync mode: Create if not exists
-- CA-SYNC-CHECK: schema=gold name=air_quality_daily
CREATE MATERIALIZED VIEW gold.air_quality_daily
WITH (timescaledb.continuous) AS
SELECT
    time_bucket('1 day', observation_time) AS bucket,
    ndp_id,
    AVG(co2) AS co2_mean,
    STDDEV(co2) AS co2_std,
    MIN(co2) AS co2_min,
    MAX(co2) AS co2_max,
    AVG(temperature_c) AS temperature_c_mean,
    MIN(temperature_c) AS temperature_c_min,
    MAX(temperature_c) AS temperature_c_max,
    AVG(humidity_pct) AS humidity_pct_mean,
    MIN(humidity_pct) AS humidity_pct_min,
    MAX(humidity_pct) AS humidity_pct_max,
    AVG(pm25) AS pm25_mean,
    STDDEV(pm25) AS pm25_std,
    MIN(pm25) AS pm25_min,
    MAX(pm25) AS pm25_max,
    PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY pm25) AS pm25_p95,
    AVG(nox_index) AS nox_index_mean,
    MAX(nox_index) AS nox_index_max,
    AVG(tvoc_index) AS tvoc_index_mean,
    MAX(tvoc_index) AS tvoc_index_max,
    AVG(pm10) AS pm10_mean,
    MIN(pm10) AS pm10_min,
    MAX(pm10) AS pm10_max,
    COUNT(*) AS sample_count
FROM silver.air_quality_observations
GROUP BY bucket, ndp_id;

-- Refresh policy for gold.air_quality_hourly
SELECT add_continuous_aggregate_policy('gold.air_quality_hourly',
    start_offset => INTERVAL '4 hours',
    end_offset => INTERVAL '15 minutes',
    schedule_interval => INTERVAL '15 minutes',
    if_not_exists => TRUE
);

-- Refresh policy for gold.air_quality_daily
SELECT add_continuous_aggregate_policy('gold.air_quality_daily',
    start_offset => INTERVAL '3 days',
    end_offset => INTERVAL '1 hour',
    schedule_interval => INTERVAL '1 hour',
    if_not_exists => TRUE
);

