//! Events hypertable DDL generator
//!
//! Generates SQL for the Gold events hypertable and related objects:
//! - Events hypertable with TimescaleDB chunking
//! - Unified events view for V1.2 API compatibility
//! - Hourly events continuous aggregate
//! - Event detection procedure and scheduled job
//!
//! Implements v11-013 per SPEC-E02.

use crate::config::{Action, DomainConfig};
use crate::error::{GoldDdlError, Result};
use serde::{Deserialize, Serialize};

/// Configuration for events hypertable
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct EventsConfig {
    /// Whether events are enabled
    #[serde(default)]
    pub enabled: bool,

    /// Chunk interval for hypertable (e.g., "7 days")
    #[serde(default = "default_chunk_interval")]
    pub chunk_interval: String,

    /// Retention policy (e.g., "1 year")
    #[serde(default)]
    pub retention: Option<String>,

    /// Detection job schedule (e.g., "15 minutes")
    #[serde(default = "default_detection_schedule")]
    pub detection_schedule: String,
}

fn default_chunk_interval() -> String {
    "7 days".to_string()
}

fn default_detection_schedule() -> String {
    "15 minutes".to_string()
}

impl EventsConfig {
    /// Create a new events config with default values
    pub fn new() -> Self {
        Self {
            enabled: true,
            chunk_interval: default_chunk_interval(),
            retention: Some("1 year".to_string()),
            detection_schedule: default_detection_schedule(),
        }
    }
}

/// Generator for events hypertable DDL
pub struct EventsGenerator {
    /// Domain ID for naming conventions
    domain_id: String,

    /// Events configuration
    config: EventsConfig,
}

impl EventsGenerator {
    /// Create a new generator from domain configuration
    pub fn from_domain_config(domain: &DomainConfig) -> Self {
        Self {
            domain_id: domain.id.clone(),
            config: EventsConfig::new(),
        }
    }

    /// Create a new generator with explicit configuration
    pub fn new(domain_id: &str, config: EventsConfig) -> Self {
        Self {
            domain_id: domain_id.to_string(),
            config,
        }
    }

    /// Generate complete DDL for events infrastructure
    pub fn generate(&self, action: Action) -> Result<String> {
        if !self.config.enabled {
            return Err(GoldDdlError::GenerationFailed {
                message: format!("Events not enabled for domain '{}'", self.domain_id),
            });
        }

        let mut ddl_parts = Vec::new();

        // Header comments
        ddl_parts.push(format!(
            "-- Events hypertable DDL for domain: {}",
            self.domain_id
        ));
        ddl_parts.push("-- Generated by ndp-gold-ddl".to_string());
        ddl_parts.push(format!("-- Mode: {}", action));
        ddl_parts.push(String::new());

        // Schema creation
        ddl_parts.push("CREATE SCHEMA IF NOT EXISTS gold;".to_string());
        ddl_parts.push(String::new());

        // Generate components based on action
        match action {
            Action::Sync => {
                ddl_parts.push(self.generate_events_hypertable_sync()?);
            }
            Action::Recreate => {
                ddl_parts.push(self.generate_events_hypertable_recreate()?);
            }
        }

        ddl_parts.push(String::new());
        ddl_parts.push(self.generate_unified_view()?);
        ddl_parts.push(String::new());
        ddl_parts.push(self.generate_hourly_aggregate(action)?);
        ddl_parts.push(String::new());
        ddl_parts.push(self.generate_detection_procedure()?);
        ddl_parts.push(String::new());
        ddl_parts.push(self.generate_detection_job()?);

        Ok(ddl_parts.join("\n"))
    }

    /// Generate SQL for events hypertable (sync mode)
    fn generate_events_hypertable_sync(&self) -> Result<String> {
        let create_table = self.generate_create_table_sql()?;
        let indexes = self.generate_indexes_sql()?;
        let retention = self.generate_retention_policy_sql()?;

        Ok(format!(
            r#"-- Events hypertable (create if not exists)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_tables
        WHERE schemaname = 'gold'
          AND tablename = 'events'
    ) THEN
{create_table_indented}

        RAISE NOTICE 'Created events hypertable: gold.events';
    ELSE
        RAISE NOTICE 'gold.events already exists, skipping';
    END IF;
END $$;

{indexes}

{retention}"#,
            create_table_indented = Self::indent(&create_table, 8),
            indexes = indexes,
            retention = retention,
        ))
    }

    /// Generate SQL for events hypertable (recreate mode)
    fn generate_events_hypertable_recreate(&self) -> Result<String> {
        let create_table = self.generate_create_table_sql()?;
        let indexes = self.generate_indexes_sql()?;
        let retention = self.generate_retention_policy_sql()?;

        Ok(format!(
            r#"-- Drop existing events infrastructure
DROP VIEW IF EXISTS gold.events_unified CASCADE;
DROP MATERIALIZED VIEW IF EXISTS gold.events_hourly CASCADE;
DROP TABLE IF EXISTS gold.events CASCADE;

-- Events hypertable
{create_table}

{indexes}

{retention}"#,
            create_table = create_table,
            indexes = indexes,
            retention = retention,
        ))
    }

    /// Generate CREATE TABLE SQL for events
    fn generate_create_table_sql(&self) -> Result<String> {
        Ok(format!(
            r#"CREATE TABLE gold.events (
    -- Identity
    event_id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    event_time TIMESTAMPTZ NOT NULL,

    -- Event classification
    stream_id TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    event_type TEXT NOT NULL,

    -- State transition fields (NULL for threshold crossings)
    from_state TEXT,
    to_state TEXT,
    duration_in_state_ms BIGINT,

    -- Threshold crossing fields (NULL for state transitions)
    metric TEXT,
    threshold_value DOUBLE PRECISION,
    crossing_direction TEXT,
    metric_value DOUBLE PRECISION,
    previous_metric_value DOUBLE PRECISION,
    objective_id TEXT,

    -- Context snapshot at event time (for correlation)
    context JSONB NOT NULL DEFAULT '{{}}'::JSONB,

    -- Extensible details
    details JSONB NOT NULL DEFAULT '{{}}'::JSONB
);

-- Convert to hypertable
SELECT create_hypertable('gold.events', 'event_time',
    chunk_time_interval => INTERVAL '{chunk_interval}',
    if_not_exists => TRUE
);

COMMENT ON TABLE gold.events IS
    'Events hypertable: state transitions and threshold crossings with context snapshots. For V1.2 Pattern Detection.';"#,
            chunk_interval = self.config.chunk_interval,
        ))
    }

    /// Generate index creation SQL
    fn generate_indexes_sql(&self) -> Result<String> {
        Ok(r#"-- Indexes for V1.2 query patterns
CREATE INDEX IF NOT EXISTS idx_events_time
    ON gold.events (event_time DESC);

CREATE INDEX IF NOT EXISTS idx_events_type_time
    ON gold.events (event_type, event_time DESC);

CREATE INDEX IF NOT EXISTS idx_events_entity_time
    ON gold.events (entity_id, event_time DESC);

CREATE INDEX IF NOT EXISTS idx_events_objective
    ON gold.events (objective_id, event_time DESC)
    WHERE event_type = 'threshold_crossing';

CREATE INDEX IF NOT EXISTS idx_events_context
    ON gold.events USING GIN (context);

CREATE INDEX IF NOT EXISTS idx_events_details
    ON gold.events USING GIN (details);"#
            .to_string())
    }

    /// Generate retention policy SQL
    fn generate_retention_policy_sql(&self) -> Result<String> {
        match &self.config.retention {
            Some(retention) => Ok(format!(
                r#"-- Retention policy ({retention})
SELECT add_retention_policy('gold.events', INTERVAL '{retention}', if_not_exists => TRUE);"#,
                retention = retention,
            )),
            None => Ok("-- No retention policy configured".to_string()),
        }
    }

    /// Generate unified events view SQL
    pub fn generate_unified_view(&self) -> Result<String> {
        Ok(r#"-- Unified events view for V1.2 API compatibility
CREATE OR REPLACE VIEW gold.events_unified AS
SELECT
    event_id,
    event_time,
    stream_id,
    entity_id,
    event_type,
    -- Build details JSONB for backward compatibility
    CASE event_type
        WHEN 'state_transition' THEN
            jsonb_build_object(
                'from_state', from_state,
                'to_state', to_state,
                'duration_in_previous_ms', duration_in_state_ms
            )
        WHEN 'threshold_crossing' THEN
            jsonb_build_object(
                'metric', metric,
                'threshold', threshold_value,
                'direction', crossing_direction,
                'value', metric_value,
                'previous_value', previous_metric_value,
                'objective_id', objective_id
            )
        ELSE details
    END AS details,
    context
FROM gold.events
ORDER BY event_time, event_type, event_id;

COMMENT ON VIEW gold.events_unified IS
    'V1.2 API view on events hypertable. Provides backward-compatible schema.';"#
            .to_string())
    }

    /// Generate hourly events continuous aggregate SQL
    pub fn generate_hourly_aggregate(&self, action: Action) -> Result<String> {
        let create_ca = r#"CREATE MATERIALIZED VIEW gold.events_hourly
WITH (timescaledb.continuous) AS
SELECT
    time_bucket('1 hour', event_time) AS bucket,
    COUNT(*) AS total_events,
    COUNT(*) FILTER (WHERE event_type = 'state_transition') AS state_transition_count,
    COUNT(*) FILTER (WHERE event_type = 'threshold_crossing') AS threshold_crossing_count,
    COUNT(DISTINCT entity_id) AS distinct_entities_with_events
FROM gold.events
GROUP BY bucket
WITH NO DATA"#;

        let refresh_policy = r#"-- Refresh policy for events hourly aggregate
SELECT add_continuous_aggregate_policy('gold.events_hourly',
    start_offset => INTERVAL '2 hours',
    end_offset => INTERVAL '1 hour',
    schedule_interval => INTERVAL '15 minutes',
    if_not_exists => TRUE
);

-- Index for time range queries
CREATE INDEX IF NOT EXISTS idx_events_hourly_bucket
    ON gold.events_hourly (bucket DESC);"#;

        match action {
            Action::Sync => Ok(format!(
                r#"-- Hourly events continuous aggregate (create if not exists)
-- CA-SYNC-CHECK: schema=gold name=events_hourly
{create_ca};

{refresh_policy}"#,
                create_ca = create_ca,
                refresh_policy = refresh_policy,
            )),
            Action::Recreate => Ok(format!(
                r#"-- Hourly events continuous aggregate (recreate)
DROP MATERIALIZED VIEW IF EXISTS gold.events_hourly CASCADE;

{create_ca};

{refresh_policy}"#,
                create_ca = create_ca,
                refresh_policy = refresh_policy,
            )),
        }
    }

    /// Generate event detection procedure SQL
    pub fn generate_detection_procedure(&self) -> Result<String> {
        let domain_id_snake = self.domain_id.replace('-', "_");

        Ok(format!(
            r#"-- Event detection procedure (runs as TimescaleDB job)
CREATE OR REPLACE PROCEDURE gold.detect_events(job_id INT, config JSONB)
LANGUAGE plpgsql AS $$
DECLARE
    last_run TIMESTAMPTZ;
    state_events_inserted INT := 0;
    crossing_events_inserted INT := 0;
BEGIN
    -- Get last successful run time
    SELECT last_successful_finish INTO last_run
    FROM timescaledb_information.job_stats
    WHERE job_id = detect_events.job_id;

    -- Default to 2 hours ago if first run
    last_run := COALESCE(last_run, NOW() - INTERVAL '2 hours');

    -- =========================================================
    -- STATE TRANSITIONS
    -- =========================================================
    -- Insert new state transition events from Silver layer
    WITH new_transitions AS (
        SELECT
            s.event_time AS event_time,
            'home-assistant-state' AS stream_id,
            s.ndp_id AS entity_id,
            'state_transition' AS event_type,
            LAG(s.state) OVER (PARTITION BY s.ndp_id ORDER BY s.event_time) AS from_state,
            s.state AS to_state,
            EXTRACT(EPOCH FROM (s.event_time - LAG(s.event_time) OVER (PARTITION BY s.ndp_id ORDER BY s.event_time))) * 1000 AS duration_ms
        FROM silver.home_assistant_state s
        WHERE s.event_time > last_run
    ),
    actual_transitions AS (
        SELECT * FROM new_transitions
        WHERE from_state IS NOT NULL
          AND from_state IS DISTINCT FROM to_state
    )
    INSERT INTO gold.events (
        event_time, stream_id, entity_id, event_type,
        from_state, to_state, duration_in_state_ms,
        context, details
    )
    SELECT
        t.event_time,
        t.stream_id,
        t.entity_id,
        t.event_type,
        t.from_state,
        t.to_state,
        t.duration_ms::BIGINT,
        -- Context from aligned view at event's hourly bucket
        COALESCE(
            (SELECT jsonb_build_object(
                'indoor_co2', a.indoor_co2_mean,
                'indoor_pm25', a.indoor_pm25_mean,
                'indoor_temp', a.indoor_temperature_c_mean,
                'outdoor_temp', a.outdoor_temperature_c_mean,
                'outdoor_pm25', a.outdoor_aqi_pm25_mean,
                'window_state', a.state_state_last
            ) FROM gold.{domain_id_snake}_aligned a
            WHERE a.bucket = time_bucket('1 hour', t.event_time)),
            '{{}}'::JSONB
        ),
        '{{}}'::JSONB
    FROM actual_transitions t
    ON CONFLICT DO NOTHING;

    GET DIAGNOSTICS state_events_inserted = ROW_COUNT;

    -- =========================================================
    -- THRESHOLD CROSSINGS
    -- =========================================================
    -- Insert new threshold crossing events
    -- (Uses objectives from domain config and compares consecutive observations)
    WITH hourly_obs AS (
        SELECT
            bucket,
            ndp_id AS entity_id,
            'air-quality'::TEXT AS stream_id,
            co2_mean AS co2_value,
            LAG(co2_mean) OVER (PARTITION BY ndp_id ORDER BY bucket) AS co2_prev,
            pm25_mean AS pm25_value,
            LAG(pm25_mean) OVER (PARTITION BY ndp_id ORDER BY bucket) AS pm25_prev
        FROM gold.air_quality_hourly
        WHERE bucket > last_run - INTERVAL '1 hour'
    ),
    co2_crossings AS (
        SELECT
            bucket AS event_time,
            stream_id,
            entity_id,
            'threshold_crossing' AS event_type,
            'co2' AS metric,
            800.0 AS threshold_value,
            CASE
                WHEN co2_prev < 800 AND co2_value >= 800 THEN 'rising'
                WHEN co2_prev >= 800 AND co2_value < 800 THEN 'falling'
            END AS crossing_direction,
            co2_value AS metric_value,
            co2_prev AS previous_metric_value,
            'healthy_co2' AS objective_id
        FROM hourly_obs
        WHERE bucket > last_run
          AND co2_prev IS NOT NULL
          AND co2_value IS NOT NULL
          AND (
              (co2_prev < 800 AND co2_value >= 800)
              OR (co2_prev >= 800 AND co2_value < 800)
          )
    ),
    pm25_crossings AS (
        SELECT
            bucket AS event_time,
            stream_id,
            entity_id,
            'threshold_crossing' AS event_type,
            'pm25' AS metric,
            12.0 AS threshold_value,
            CASE
                WHEN pm25_prev < 12 AND pm25_value >= 12 THEN 'rising'
                WHEN pm25_prev >= 12 AND pm25_value < 12 THEN 'falling'
            END AS crossing_direction,
            pm25_value AS metric_value,
            pm25_prev AS previous_metric_value,
            'healthy_pm25' AS objective_id
        FROM hourly_obs
        WHERE bucket > last_run
          AND pm25_prev IS NOT NULL
          AND pm25_value IS NOT NULL
          AND (
              (pm25_prev < 12 AND pm25_value >= 12)
              OR (pm25_prev >= 12 AND pm25_value < 12)
          )
    ),
    all_crossings AS (
        SELECT * FROM co2_crossings
        UNION ALL
        SELECT * FROM pm25_crossings
    )
    INSERT INTO gold.events (
        event_time, stream_id, entity_id, event_type,
        metric, threshold_value, crossing_direction,
        metric_value, previous_metric_value, objective_id,
        context, details
    )
    SELECT
        c.event_time,
        c.stream_id,
        c.entity_id,
        c.event_type,
        c.metric,
        c.threshold_value,
        c.crossing_direction,
        c.metric_value,
        c.previous_metric_value,
        c.objective_id,
        -- Context from aligned view at crossing time
        COALESCE(
            (SELECT jsonb_build_object(
                'indoor_co2', a.indoor_co2_mean,
                'indoor_pm25', a.indoor_pm25_mean,
                'indoor_temp', a.indoor_temperature_c_mean,
                'outdoor_temp', a.outdoor_temperature_c_mean,
                'outdoor_pm25', a.outdoor_aqi_pm25_mean,
                'window_state', a.state_state_last
            ) FROM gold.{domain_id_snake}_aligned a
            WHERE a.bucket = c.event_time),
            '{{}}'::JSONB
        ),
        jsonb_build_object('condition', '<', 'unit', CASE c.metric WHEN 'co2' THEN 'ppm' ELSE 'ug/m3' END)
    FROM all_crossings c
    ON CONFLICT DO NOTHING;

    GET DIAGNOSTICS crossing_events_inserted = ROW_COUNT;

    RAISE NOTICE 'Event detection: % state transitions, % threshold crossings',
        state_events_inserted, crossing_events_inserted;

    COMMIT;
END;
$$;

COMMENT ON PROCEDURE gold.detect_events IS
    'Detects state transitions and threshold crossings, inserts into gold.events with context snapshots.';"#,
            domain_id_snake = domain_id_snake,
        ))
    }

    /// Generate detection job scheduling SQL
    pub fn generate_detection_job(&self) -> Result<String> {
        Ok(format!(
            r#"-- Schedule the detection job (every {schedule})
SELECT add_job('gold.detect_events', '{schedule}',
    config => '{{}}'::JSONB,
    if_not_exists => TRUE
);

COMMENT ON FUNCTION gold.detect_events IS
    'Scheduled job: Detects events every {schedule} and inserts into gold.events.';"#,
            schedule = self.config.detection_schedule,
        ))
    }

    /// Indent text by a given number of spaces
    fn indent(text: &str, spaces: usize) -> String {
        let indent = " ".repeat(spaces);
        text.lines()
            .map(|line| format!("{}{}", indent, line))
            .collect::<Vec<_>>()
            .join("\n")
    }
}

/// Trait for generating events DDL
pub trait IEventsGenerator {
    /// Generate SQL for events hypertable
    fn generate_events_hypertable(&self, domain: &DomainConfig) -> Result<String>;

    /// Generate SQL for unified events view
    fn generate_unified_view(&self) -> Result<String>;

    /// Generate SQL for hourly events continuous aggregate
    fn generate_hourly_aggregate(&self) -> Result<String>;

    /// Generate SQL for event detection procedure
    fn generate_detection_procedure(&self, domain: &DomainConfig) -> Result<String>;

    /// Generate SQL for detection job
    fn generate_detection_job(&self, schedule: &str) -> Result<String>;
}

impl IEventsGenerator for EventsGenerator {
    fn generate_events_hypertable(&self, _domain: &DomainConfig) -> Result<String> {
        let create_table = self.generate_create_table_sql()?;
        let indexes = self.generate_indexes_sql()?;
        let retention = self.generate_retention_policy_sql()?;

        Ok(format!("{}\n\n{}\n\n{}", create_table, indexes, retention))
    }

    fn generate_unified_view(&self) -> Result<String> {
        EventsGenerator::generate_unified_view(self)
    }

    fn generate_hourly_aggregate(&self) -> Result<String> {
        EventsGenerator::generate_hourly_aggregate(self, Action::Sync)
    }

    fn generate_detection_procedure(&self, _domain: &DomainConfig) -> Result<String> {
        EventsGenerator::generate_detection_procedure(self)
    }

    fn generate_detection_job(&self, _schedule: &str) -> Result<String> {
        EventsGenerator::generate_detection_job(self)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{AlignmentConfig, JoinStrategy, NullHandling, StreamRef, StreamRole};

    fn create_test_domain() -> DomainConfig {
        DomainConfig {
            id: "indoor-air-quality".to_string(),
            description: "Indoor air quality monitoring domain".to_string(),
            streams: vec![
                StreamRef {
                    stream_id: "air-quality".to_string(),
                    alias: "indoor".to_string(),
                    role: StreamRole::Primary,
                    null_handling: None,
                },
                StreamRef {
                    stream_id: "home-assistant-state".to_string(),
                    alias: "state".to_string(),
                    role: StreamRole::Actuator,
                    null_handling: Some(NullHandling::CarryForward),
                },
            ],
            alignment: AlignmentConfig {
                view_name: "indoor_air_quality_aligned".to_string(),
                granularity: "1 hour".to_string(),
                join_strategy: JoinStrategy::FullOuter,
                null_handling: NullHandling::Preserve,
            },
            objectives: vec![],
        }
    }

    fn create_test_config() -> EventsConfig {
        EventsConfig {
            enabled: true,
            chunk_interval: "7 days".to_string(),
            retention: Some("1 year".to_string()),
            detection_schedule: "15 minutes".to_string(),
        }
    }

    // =========================================================================
    // TDD Cycle 1: Events Hypertable Generation
    // =========================================================================

    #[test]
    fn test_generates_create_table() {
        let domain = create_test_domain();
        let generator = EventsGenerator::from_domain_config(&domain);

        let sql = generator.generate(Action::Recreate).unwrap();

        assert!(sql.contains("CREATE TABLE"));
        assert!(sql.contains("gold.events"));
        assert!(sql.contains("event_id UUID"));
        assert!(sql.contains("event_time TIMESTAMPTZ"));
    }

    #[test]
    fn test_generates_hypertable() {
        let domain = create_test_domain();
        let generator = EventsGenerator::from_domain_config(&domain);

        let sql = generator.generate(Action::Recreate).unwrap();

        assert!(sql.contains("create_hypertable"));
        assert!(sql.contains("gold.events"));
        assert!(sql.contains("event_time"));
    }

    #[test]
    fn test_generates_chunk_interval() {
        let config = create_test_config();
        let generator = EventsGenerator::new("test-domain", config);

        let sql = generator.generate(Action::Recreate).unwrap();

        assert!(sql.contains("chunk_time_interval => INTERVAL '7 days'"));
    }

    // =========================================================================
    // TDD Cycle 2: Schema Columns
    // =========================================================================

    #[test]
    fn test_generates_state_transition_columns() {
        let domain = create_test_domain();
        let generator = EventsGenerator::from_domain_config(&domain);

        let sql = generator.generate(Action::Recreate).unwrap();

        assert!(sql.contains("from_state TEXT"));
        assert!(sql.contains("to_state TEXT"));
        assert!(sql.contains("duration_in_state_ms BIGINT"));
    }

    #[test]
    fn test_generates_threshold_crossing_columns() {
        let domain = create_test_domain();
        let generator = EventsGenerator::from_domain_config(&domain);

        let sql = generator.generate(Action::Recreate).unwrap();

        assert!(sql.contains("metric TEXT"));
        assert!(sql.contains("threshold_value DOUBLE PRECISION"));
        assert!(sql.contains("crossing_direction TEXT"));
        assert!(sql.contains("metric_value DOUBLE PRECISION"));
        assert!(sql.contains("previous_metric_value DOUBLE PRECISION"));
        assert!(sql.contains("objective_id TEXT"));
    }

    #[test]
    fn test_generates_context_and_details_columns() {
        let domain = create_test_domain();
        let generator = EventsGenerator::from_domain_config(&domain);

        let sql = generator.generate(Action::Recreate).unwrap();

        assert!(sql.contains("context JSONB NOT NULL"));
        assert!(sql.contains("details JSONB NOT NULL"));
    }

    // =========================================================================
    // TDD Cycle 3: Indexes
    // =========================================================================

    #[test]
    fn test_generates_time_index() {
        let domain = create_test_domain();
        let generator = EventsGenerator::from_domain_config(&domain);

        let sql = generator.generate(Action::Recreate).unwrap();

        assert!(sql.contains("CREATE INDEX"));
        assert!(sql.contains("idx_events_time"));
        assert!(sql.contains("event_time DESC"));
    }

    #[test]
    fn test_generates_type_time_index() {
        let domain = create_test_domain();
        let generator = EventsGenerator::from_domain_config(&domain);

        let sql = generator.generate(Action::Recreate).unwrap();

        assert!(sql.contains("idx_events_type_time"));
        assert!(sql.contains("event_type, event_time DESC"));
    }

    #[test]
    fn test_generates_gin_indexes_for_jsonb() {
        let domain = create_test_domain();
        let generator = EventsGenerator::from_domain_config(&domain);

        let sql = generator.generate(Action::Recreate).unwrap();

        assert!(sql.contains("USING GIN (context)"));
        assert!(sql.contains("USING GIN (details)"));
    }

    #[test]
    fn test_generates_objective_partial_index() {
        let domain = create_test_domain();
        let generator = EventsGenerator::from_domain_config(&domain);

        let sql = generator.generate(Action::Recreate).unwrap();

        assert!(sql.contains("idx_events_objective"));
        assert!(sql.contains("WHERE event_type = 'threshold_crossing'"));
    }

    // =========================================================================
    // TDD Cycle 4: Unified Events View
    // =========================================================================

    #[test]
    fn test_generates_unified_view() {
        let domain = create_test_domain();
        let generator = EventsGenerator::from_domain_config(&domain);

        let sql = generator.generate(Action::Recreate).unwrap();

        assert!(sql.contains("CREATE OR REPLACE VIEW gold.events_unified"));
        assert!(sql.contains("SELECT") && sql.contains("FROM gold.events"));
    }

    #[test]
    fn test_unified_view_builds_details_jsonb() {
        let domain = create_test_domain();
        let generator = EventsGenerator::from_domain_config(&domain);

        let sql = generator.generate(Action::Recreate).unwrap();

        assert!(sql.contains("CASE event_type"));
        assert!(sql.contains("WHEN 'state_transition'"));
        assert!(sql.contains("WHEN 'threshold_crossing'"));
        assert!(sql.contains("jsonb_build_object"));
    }

    // =========================================================================
    // TDD Cycle 5: Hourly Continuous Aggregate
    // =========================================================================

    #[test]
    fn test_generates_hourly_aggregate() {
        let domain = create_test_domain();
        let generator = EventsGenerator::from_domain_config(&domain);

        let sql = generator.generate(Action::Recreate).unwrap();

        assert!(sql.contains("CREATE MATERIALIZED VIEW gold.events_hourly"));
        assert!(sql.contains("timescaledb.continuous"));
    }

    #[test]
    fn test_hourly_aggregate_counts_events() {
        let domain = create_test_domain();
        let generator = EventsGenerator::from_domain_config(&domain);

        let sql = generator.generate(Action::Recreate).unwrap();

        assert!(sql.contains("COUNT(*) AS total_events"));
        assert!(sql.contains("state_transition_count"));
        assert!(sql.contains("threshold_crossing_count"));
    }

    #[test]
    fn test_hourly_aggregate_refresh_policy() {
        let domain = create_test_domain();
        let generator = EventsGenerator::from_domain_config(&domain);

        let sql = generator.generate(Action::Recreate).unwrap();

        assert!(sql.contains("add_continuous_aggregate_policy"));
        assert!(sql.contains("gold.events_hourly"));
        assert!(sql.contains("schedule_interval"));
    }

    // =========================================================================
    // TDD Cycle 6: Detection Procedure
    // =========================================================================

    #[test]
    fn test_generates_detection_procedure() {
        let domain = create_test_domain();
        let generator = EventsGenerator::from_domain_config(&domain);

        let sql = generator.generate(Action::Recreate).unwrap();

        assert!(sql.contains("CREATE OR REPLACE PROCEDURE gold.detect_events"));
        assert!(sql.contains("LANGUAGE plpgsql"));
    }

    #[test]
    fn test_detection_procedure_handles_state_transitions() {
        let domain = create_test_domain();
        let generator = EventsGenerator::from_domain_config(&domain);

        let sql = generator.generate(Action::Recreate).unwrap();

        assert!(sql.contains("STATE TRANSITIONS"));
        assert!(sql.contains("LAG(s.state) OVER"));
        assert!(sql.contains("from_state IS DISTINCT FROM to_state"));
    }

    #[test]
    fn test_detection_procedure_handles_threshold_crossings() {
        let domain = create_test_domain();
        let generator = EventsGenerator::from_domain_config(&domain);

        let sql = generator.generate(Action::Recreate).unwrap();

        assert!(sql.contains("THRESHOLD CROSSINGS"));
        assert!(sql.contains("co2_crossings"));
        assert!(sql.contains("pm25_crossings"));
    }

    #[test]
    fn test_detection_procedure_captures_context() {
        let domain = create_test_domain();
        let generator = EventsGenerator::from_domain_config(&domain);

        let sql = generator.generate(Action::Recreate).unwrap();

        assert!(sql.contains("indoor_air_quality_aligned"));
        assert!(sql.contains("indoor_co2"));
        assert!(sql.contains("indoor_pm25"));
    }

    #[test]
    fn test_detection_procedure_uses_last_run() {
        let domain = create_test_domain();
        let generator = EventsGenerator::from_domain_config(&domain);

        let sql = generator.generate(Action::Recreate).unwrap();

        assert!(sql.contains("last_successful_finish"));
        assert!(sql.contains("last_run"));
        assert!(sql.contains("job_stats"));
    }

    // =========================================================================
    // TDD Cycle 7: Detection Job Scheduling
    // =========================================================================

    #[test]
    fn test_generates_detection_job() {
        let domain = create_test_domain();
        let generator = EventsGenerator::from_domain_config(&domain);

        let sql = generator.generate(Action::Recreate).unwrap();

        assert!(sql.contains("add_job"));
        assert!(sql.contains("gold.detect_events"));
        assert!(sql.contains("15 minutes"));
    }

    #[test]
    fn test_detection_job_configurable_schedule() {
        let config = EventsConfig {
            enabled: true,
            detection_schedule: "30 minutes".to_string(),
            ..EventsConfig::default()
        };
        let generator = EventsGenerator::new("test-domain", config);

        let sql = generator.generate(Action::Recreate).unwrap();

        assert!(sql.contains("'30 minutes'"));
    }

    // =========================================================================
    // TDD Cycle 8: Retention Policy
    // =========================================================================

    #[test]
    fn test_generates_retention_policy() {
        let domain = create_test_domain();
        let generator = EventsGenerator::from_domain_config(&domain);

        let sql = generator.generate(Action::Recreate).unwrap();

        assert!(sql.contains("add_retention_policy"));
        assert!(sql.contains("gold.events"));
        assert!(sql.contains("1 year"));
    }

    #[test]
    fn test_no_retention_policy_when_not_configured() {
        let config = EventsConfig {
            enabled: true,
            retention: None,
            ..EventsConfig::default()
        };
        let generator = EventsGenerator::new("test-domain", config);

        let sql = generator.generate(Action::Recreate).unwrap();

        assert!(sql.contains("No retention policy configured"));
    }

    // =========================================================================
    // TDD Cycle 9: Idempotency
    // =========================================================================

    #[test]
    fn test_sync_mode_checks_existence() {
        let domain = create_test_domain();
        let generator = EventsGenerator::from_domain_config(&domain);

        let sql = generator.generate(Action::Sync).unwrap();

        assert!(sql.contains("IF NOT EXISTS"));
        assert!(sql.contains("pg_tables"));
        assert!(sql.contains("schemaname = 'gold'"));
    }

    #[test]
    fn test_recreate_mode_drops_first() {
        let domain = create_test_domain();
        let generator = EventsGenerator::from_domain_config(&domain);

        let sql = generator.generate(Action::Recreate).unwrap();

        assert!(sql.contains("DROP TABLE IF EXISTS gold.events CASCADE"));
        assert!(sql.contains("DROP VIEW IF EXISTS gold.events_unified CASCADE"));
        assert!(sql.contains("DROP MATERIALIZED VIEW IF EXISTS gold.events_hourly CASCADE"));
    }

    // =========================================================================
    // TDD Cycle 10: Error Handling
    // =========================================================================

    #[test]
    fn test_disabled_events_returns_error() {
        let config = EventsConfig {
            enabled: false,
            ..EventsConfig::default()
        };
        let generator = EventsGenerator::new("test-domain", config);

        let result = generator.generate(Action::Recreate);

        assert!(result.is_err());
        let err = result.unwrap_err().to_string();
        assert!(err.contains("not enabled"));
    }

    // =========================================================================
    // TDD Cycle 11: Header Comments
    // =========================================================================

    #[test]
    fn test_generates_header_comments() {
        let domain = create_test_domain();
        let generator = EventsGenerator::from_domain_config(&domain);

        let sql = generator.generate(Action::Recreate).unwrap();

        assert!(sql.contains("-- Events hypertable DDL for domain: indoor-air-quality"));
        assert!(sql.contains("-- Generated by ndp-gold-ddl"));
        assert!(sql.contains("-- Mode: recreate"));
    }

    #[test]
    fn test_generates_table_comments() {
        let domain = create_test_domain();
        let generator = EventsGenerator::from_domain_config(&domain);

        let sql = generator.generate(Action::Recreate).unwrap();

        assert!(sql.contains("COMMENT ON TABLE gold.events"));
        assert!(sql.contains("COMMENT ON VIEW gold.events_unified"));
        assert!(sql.contains("COMMENT ON PROCEDURE gold.detect_events"));
    }

    // =========================================================================
    // Trait Implementation Tests
    // =========================================================================

    #[test]
    fn test_trait_generate_events_hypertable() {
        let domain = create_test_domain();
        let generator = EventsGenerator::from_domain_config(&domain);

        let sql =
            <EventsGenerator as IEventsGenerator>::generate_events_hypertable(&generator, &domain)
                .unwrap();

        assert!(sql.contains("CREATE TABLE gold.events"));
        assert!(sql.contains("CREATE INDEX"));
    }

    #[test]
    fn test_trait_generate_unified_view() {
        let domain = create_test_domain();
        let generator = EventsGenerator::from_domain_config(&domain);

        let sql = <EventsGenerator as IEventsGenerator>::generate_unified_view(&generator).unwrap();

        assert!(sql.contains("CREATE OR REPLACE VIEW gold.events_unified"));
    }

    #[test]
    fn test_trait_generate_hourly_aggregate() {
        let domain = create_test_domain();
        let generator = EventsGenerator::from_domain_config(&domain);

        let sql =
            <EventsGenerator as IEventsGenerator>::generate_hourly_aggregate(&generator).unwrap();

        assert!(sql.contains("CREATE MATERIALIZED VIEW gold.events_hourly"));
    }
}
