-- Computed columns for Silver layer tables
-- These are derived values that support dashboard queries
-- Run after tables are created by Silver ETL

-- =============================================================================
-- DISABLED: lead_time_hours GENERATED column
-- =============================================================================
-- Reason: Adding GENERATED ALWAYS STORED columns to TimescaleDB hypertables
--         caused DuckDB ETL loading to fail. See dp-008/bugs/reported-bugs-01.md
--
-- Resolution: The Forecast Accuracy dashboard queries now compute lead_time_hours
--             dynamically using: EXTRACT(EPOCH FROM (valid_time - issue_time)) / 3600.0
--             This is more flexible and avoids schema conflicts.
--
-- The silver.weather_forecasts table already has lead_time_hours INTEGER column
-- defined in 001_silver_schema.sql. ETL can optionally populate it, but
-- dashboards no longer depend on it being populated.
-- =============================================================================

-- Original code (disabled):
-- DO $$
-- BEGIN
--     IF EXISTS (
--         SELECT 1 FROM information_schema.tables
--         WHERE table_schema = 'silver' AND table_name = 'weather_forecasts'
--     ) THEN
--         IF NOT EXISTS (
--             SELECT 1 FROM information_schema.columns
--             WHERE table_schema = 'silver'
--             AND table_name = 'weather_forecasts'
--             AND column_name = 'lead_time_hours'
--         ) THEN
--             ALTER TABLE silver.weather_forecasts
--             ADD COLUMN lead_time_hours double precision
--             GENERATED ALWAYS AS (EXTRACT(EPOCH FROM (valid_time - issue_time)) / 3600.0) STORED;
--             RAISE NOTICE 'Added lead_time_hours column to silver.weather_forecasts';
--         END IF;
--     END IF;
-- END $$;

-- No-op: This script is now a placeholder
SELECT 'Computed columns script - no actions required (lead_time computed dynamically in dashboards)' AS status;
