// This file is @generated by prost-build.
/// Configuration request with hierarchical path and context
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetConfigRequest {
    /// e.g., "/neural-trading/data-ingestion"
    #[prost(string, tag = "1")]
    pub namespace_path: ::prost::alloc::string::String,
    /// Configuration key within namespace
    #[prost(string, tag = "2")]
    pub key: ::prost::alloc::string::String,
    /// Optional version constraint (default: latest)
    #[prost(string, tag = "3")]
    pub version: ::prost::alloc::string::String,
    /// Environment context for conditional configs
    #[prost(map = "string, string", tag = "4")]
    pub context: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// Include modification timestamps and audit info
    #[prost(bool, tag = "5")]
    pub include_metadata: bool,
}
/// Configuration response with typed value support
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetConfigResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub namespace_path: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub version: ::prost::alloc::string::String,
    /// Strongly typed configuration value
    #[prost(message, optional, tag = "5")]
    pub value: ::core::option::Option<ConfigValue>,
    /// Optional metadata when requested
    #[prost(message, optional, tag = "6")]
    pub metadata: ::core::option::Option<ConfigMetadata>,
    /// Error details if success=false
    #[prost(string, tag = "7")]
    pub error_message: ::prost::alloc::string::String,
}
/// Bulk configuration request for multiple keys
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBulkConfigRequest {
    #[prost(string, tag = "1")]
    pub namespace_path: ::prost::alloc::string::String,
    /// List of configuration keys to retrieve
    #[prost(string, repeated, tag = "2")]
    pub keys: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Version constraint applies to all keys
    #[prost(string, tag = "3")]
    pub version: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "4")]
    pub context: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(bool, tag = "5")]
    pub include_metadata: bool,
}
/// Bulk configuration response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBulkConfigResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub namespace_path: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub version: ::prost::alloc::string::String,
    /// Key -> ConfigValue mapping
    #[prost(map = "string, message", tag = "4")]
    pub values: ::std::collections::HashMap<::prost::alloc::string::String, ConfigValue>,
    /// Key -> Metadata mapping (if requested)
    #[prost(map = "string, message", tag = "5")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ConfigMetadata,
    >,
    /// Keys that were not found
    #[prost(string, repeated, tag = "6")]
    pub missing_keys: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "7")]
    pub error_message: ::prost::alloc::string::String,
}
/// Set configuration request with validation
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetConfigRequest {
    #[prost(string, tag = "1")]
    pub namespace_path: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub key: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub value: ::core::option::Option<ConfigValue>,
    /// Audit trail: reason for change
    #[prost(string, tag = "4")]
    pub change_reason: ::prost::alloc::string::String,
    /// Validate without persisting (dry-run)
    #[prost(bool, tag = "5")]
    pub validate_only: bool,
    /// Optimistic concurrency control
    #[prost(string, tag = "6")]
    pub expected_version: ::prost::alloc::string::String,
}
/// Set configuration response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetConfigResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub namespace_path: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub key: ::prost::alloc::string::String,
    /// Version after successful update
    #[prost(string, tag = "4")]
    pub new_version: ::prost::alloc::string::String,
    /// Schema validation errors
    #[prost(string, repeated, tag = "5")]
    pub validation_errors: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "6")]
    pub error_message: ::prost::alloc::string::String,
}
/// Watch configuration changes request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WatchConfigRequest {
    #[prost(string, tag = "1")]
    pub namespace_path: ::prost::alloc::string::String,
    /// Specific keys to watch (empty = all)
    #[prost(string, repeated, tag = "2")]
    pub keys: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Send current values immediately
    #[prost(bool, tag = "3")]
    pub include_initial_values: bool,
}
/// Real-time configuration change event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConfigChangeEvent {
    #[prost(string, tag = "1")]
    pub namespace_path: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub key: ::prost::alloc::string::String,
    #[prost(enumeration = "ChangeType", tag = "3")]
    pub change_type: i32,
    /// Previous value (for UPDATED/DELETED)
    #[prost(message, optional, tag = "4")]
    pub old_value: ::core::option::Option<ConfigValue>,
    /// New value (for CREATED/UPDATED)
    #[prost(message, optional, tag = "5")]
    pub new_value: ::core::option::Option<ConfigValue>,
    #[prost(message, optional, tag = "6")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    /// Audit trail
    #[prost(string, tag = "7")]
    pub change_reason: ::prost::alloc::string::String,
    /// Service/user that made the change
    #[prost(string, tag = "8")]
    pub changed_by: ::prost::alloc::string::String,
    /// Version after change
    #[prost(string, tag = "9")]
    pub version: ::prost::alloc::string::String,
}
/// Schema request for namespace configuration
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSchemaRequest {
    #[prost(string, tag = "1")]
    pub namespace_path: ::prost::alloc::string::String,
    /// Optional specific schema version
    #[prost(string, tag = "2")]
    pub schema_version: ::prost::alloc::string::String,
}
/// Schema response with JSON Schema definition
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSchemaResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub namespace_path: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub schema_version: ::prost::alloc::string::String,
    /// JSON Schema definition as string
    #[prost(string, tag = "4")]
    pub json_schema: ::prost::alloc::string::String,
    /// Available schema versions
    #[prost(string, repeated, tag = "5")]
    pub supported_versions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "6")]
    pub error_message: ::prost::alloc::string::String,
}
/// Strongly typed configuration value supporting multiple data types
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConfigValue {
    #[prost(enumeration = "ValueType", tag = "1")]
    pub r#type: i32,
    #[prost(oneof = "config_value::Value", tags = "2, 3, 4, 5, 6, 7")]
    pub value: ::core::option::Option<config_value::Value>,
}
/// Nested message and enum types in `ConfigValue`.
pub mod config_value {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(string, tag = "2")]
        StringValue(::prost::alloc::string::String),
        #[prost(int64, tag = "3")]
        IntValue(i64),
        #[prost(double, tag = "4")]
        FloatValue(f64),
        #[prost(bool, tag = "5")]
        BoolValue(bool),
        /// Complex nested objects/arrays
        #[prost(message, tag = "6")]
        JsonValue(::prost_types::Struct),
        /// Binary configuration data
        #[prost(bytes, tag = "7")]
        BinaryValue(::prost::alloc::vec::Vec<u8>),
    }
}
/// Configuration metadata for audit and versioning
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConfigMetadata {
    #[prost(message, optional, tag = "1")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "2")]
    pub modified_at: ::core::option::Option<::prost_types::Timestamp>,
    /// Service/user that created
    #[prost(string, tag = "3")]
    pub created_by: ::prost::alloc::string::String,
    /// Service/user that last modified
    #[prost(string, tag = "4")]
    pub modified_by: ::prost::alloc::string::String,
    /// Configuration version
    #[prost(string, tag = "5")]
    pub version: ::prost::alloc::string::String,
    /// Organizational tags
    #[prost(string, repeated, tag = "6")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Additional metadata
    #[prost(map = "string, string", tag = "7")]
    pub annotations: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
/// Health status for monitoring integration
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HealthStatus {
    #[prost(bool, tag = "1")]
    pub healthy: bool,
    /// "SERVING", "NOT_SERVING", "UNKNOWN"
    #[prost(string, tag = "2")]
    pub status: ::prost::alloc::string::String,
    /// Component-specific health info
    #[prost(map = "string, string", tag = "3")]
    pub details: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(message, optional, tag = "4")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    /// Service version
    #[prost(string, tag = "5")]
    pub version: ::prost::alloc::string::String,
}
/// Configuration validation error details
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidationError {
    /// JSON path to invalid field
    #[prost(string, tag = "1")]
    pub field_path: ::prost::alloc::string::String,
    /// Validation error code
    #[prost(string, tag = "2")]
    pub error_code: ::prost::alloc::string::String,
    /// Human-readable error message
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
    /// Expected value format/type
    #[prost(message, optional, tag = "4")]
    pub expected_value: ::core::option::Option<::prost_types::Any>,
    /// Actual invalid value
    #[prost(message, optional, tag = "5")]
    pub actual_value: ::core::option::Option<::prost_types::Any>,
}
/// Namespace listing request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListNamespacesRequest {
    /// Filter namespaces by prefix
    #[prost(string, tag = "1")]
    pub prefix: ::prost::alloc::string::String,
    /// Include usage statistics
    #[prost(bool, tag = "2")]
    pub include_stats: bool,
}
/// Namespace listing response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListNamespacesResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(message, repeated, tag = "2")]
    pub namespaces: ::prost::alloc::vec::Vec<NamespaceInfo>,
    #[prost(string, tag = "3")]
    pub error_message: ::prost::alloc::string::String,
}
/// Namespace information
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NamespaceInfo {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    /// Number of configuration keys
    #[prost(int32, tag = "3")]
    pub key_count: i32,
    #[prost(message, optional, tag = "4")]
    pub last_modified: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, repeated, tag = "5")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "6")]
    pub schema_version: ::prost::alloc::string::String,
}
/// Get namespace info request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetNamespaceInfoRequest {
    #[prost(string, tag = "1")]
    pub namespace_path: ::prost::alloc::string::String,
    /// Include list of all keys
    #[prost(bool, tag = "2")]
    pub include_keys: bool,
}
/// Get namespace info response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetNamespaceInfoResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(message, optional, tag = "2")]
    pub info: ::core::option::Option<NamespaceInfo>,
    /// All configuration keys (if requested)
    #[prost(string, repeated, tag = "3")]
    pub keys: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "4")]
    pub error_message: ::prost::alloc::string::String,
}
/// Configuration validation request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidateConfigRequest {
    #[prost(string, tag = "1")]
    pub namespace_path: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub key: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub value: ::core::option::Option<ConfigValue>,
    /// Specific schema version to validate against
    #[prost(string, tag = "4")]
    pub schema_version: ::prost::alloc::string::String,
}
/// Configuration validation response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidateConfigResponse {
    #[prost(bool, tag = "1")]
    pub valid: bool,
    #[prost(message, repeated, tag = "2")]
    pub errors: ::prost::alloc::vec::Vec<ValidationError>,
    /// Schema version used for validation
    #[prost(string, tag = "3")]
    pub schema_version: ::prost::alloc::string::String,
}
/// Audit trail request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAuditTrailRequest {
    #[prost(string, tag = "1")]
    pub namespace_path: ::prost::alloc::string::String,
    /// Optional: filter by specific key
    #[prost(string, tag = "2")]
    pub key: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub start_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "4")]
    pub end_time: ::core::option::Option<::prost_types::Timestamp>,
    /// Maximum number of entries
    #[prost(int32, tag = "5")]
    pub limit: i32,
    /// Pagination token
    #[prost(string, tag = "6")]
    pub next_token: ::prost::alloc::string::String,
}
/// Audit trail response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAuditTrailResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(message, repeated, tag = "2")]
    pub entries: ::prost::alloc::vec::Vec<AuditEntry>,
    /// Pagination token for next page
    #[prost(string, tag = "3")]
    pub next_token: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub error_message: ::prost::alloc::string::String,
}
/// Audit trail entry
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuditEntry {
    #[prost(message, optional, tag = "1")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag = "2")]
    pub namespace_path: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub key: ::prost::alloc::string::String,
    #[prost(enumeration = "ChangeType", tag = "4")]
    pub change_type: i32,
    #[prost(message, optional, tag = "5")]
    pub old_value: ::core::option::Option<ConfigValue>,
    #[prost(message, optional, tag = "6")]
    pub new_value: ::core::option::Option<ConfigValue>,
    #[prost(string, tag = "7")]
    pub changed_by: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub change_reason: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub version: ::prost::alloc::string::String,
    /// Request session identifier
    #[prost(string, tag = "10")]
    pub session_id: ::prost::alloc::string::String,
}
/// Backup namespace request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BackupNamespaceRequest {
    #[prost(string, tag = "1")]
    pub namespace_path: ::prost::alloc::string::String,
    /// Optional backup identifier
    #[prost(string, tag = "2")]
    pub backup_name: ::prost::alloc::string::String,
    /// Include audit trails and metadata
    #[prost(bool, tag = "3")]
    pub include_metadata: bool,
}
/// Backup namespace response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BackupNamespaceResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// Unique backup identifier
    #[prost(string, tag = "2")]
    pub backup_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    /// Number of configurations backed up
    #[prost(int32, tag = "4")]
    pub config_count: i32,
    #[prost(string, tag = "5")]
    pub error_message: ::prost::alloc::string::String,
}
/// Restore namespace request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RestoreNamespaceRequest {
    #[prost(string, tag = "1")]
    pub backup_id: ::prost::alloc::string::String,
    /// Where to restore (can be different from original)
    #[prost(string, tag = "2")]
    pub target_namespace_path: ::prost::alloc::string::String,
    /// Overwrite existing configurations
    #[prost(bool, tag = "3")]
    pub overwrite_existing: bool,
    /// Validate restore without executing
    #[prost(bool, tag = "4")]
    pub dry_run: bool,
}
/// Restore namespace response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RestoreNamespaceResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// Number of configurations restored
    #[prost(int32, tag = "2")]
    pub restored_count: i32,
    /// Keys that would conflict (in dry-run)
    #[prost(string, repeated, tag = "3")]
    pub conflicts: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "4")]
    pub error_message: ::prost::alloc::string::String,
}
/// Enumeration for supported value types
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ValueType {
    Unspecified = 0,
    String = 1,
    Int = 2,
    Float = 3,
    Bool = 4,
    Json = 5,
    Binary = 6,
}
impl ValueType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            ValueType::Unspecified => "VALUE_TYPE_UNSPECIFIED",
            ValueType::String => "VALUE_TYPE_STRING",
            ValueType::Int => "VALUE_TYPE_INT",
            ValueType::Float => "VALUE_TYPE_FLOAT",
            ValueType::Bool => "VALUE_TYPE_BOOL",
            ValueType::Json => "VALUE_TYPE_JSON",
            ValueType::Binary => "VALUE_TYPE_BINARY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "VALUE_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "VALUE_TYPE_STRING" => Some(Self::String),
            "VALUE_TYPE_INT" => Some(Self::Int),
            "VALUE_TYPE_FLOAT" => Some(Self::Float),
            "VALUE_TYPE_BOOL" => Some(Self::Bool),
            "VALUE_TYPE_JSON" => Some(Self::Json),
            "VALUE_TYPE_BINARY" => Some(Self::Binary),
            _ => None,
        }
    }
}
/// Enumeration for configuration change types
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ChangeType {
    Unspecified = 0,
    Created = 1,
    Updated = 2,
    Deleted = 3,
}
impl ChangeType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            ChangeType::Unspecified => "CHANGE_TYPE_UNSPECIFIED",
            ChangeType::Created => "CHANGE_TYPE_CREATED",
            ChangeType::Updated => "CHANGE_TYPE_UPDATED",
            ChangeType::Deleted => "CHANGE_TYPE_DELETED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CHANGE_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "CHANGE_TYPE_CREATED" => Some(Self::Created),
            "CHANGE_TYPE_UPDATED" => Some(Self::Updated),
            "CHANGE_TYPE_DELETED" => Some(Self::Deleted),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod config_store_service_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// ConfigStoreService provides configuration management with namespace isolation,
    /// schema validation, and real-time updates for neural-trader platform services
    #[derive(Debug, Clone)]
    pub struct ConfigStoreServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ConfigStoreServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ConfigStoreServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ConfigStoreServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + Send + Sync,
        {
            ConfigStoreServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Get configuration by namespace path with optional versioning
        pub async fn get_config(
            &mut self,
            request: impl tonic::IntoRequest<super::GetConfigRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetConfigResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/neural_platform.config.ConfigStoreService/GetConfig",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "neural_platform.config.ConfigStoreService",
                        "GetConfig",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get multiple configuration values in a single request for performance
        pub async fn get_bulk_config(
            &mut self,
            request: impl tonic::IntoRequest<super::GetBulkConfigRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetBulkConfigResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/neural_platform.config.ConfigStoreService/GetBulkConfig",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "neural_platform.config.ConfigStoreService",
                        "GetBulkConfig",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Set configuration value with schema validation (admin/authorized services only)
        pub async fn set_config(
            &mut self,
            request: impl tonic::IntoRequest<super::SetConfigRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SetConfigResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/neural_platform.config.ConfigStoreService/SetConfig",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "neural_platform.config.ConfigStoreService",
                        "SetConfig",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Watch for real-time configuration changes with streaming updates
        pub async fn watch_config(
            &mut self,
            request: impl tonic::IntoRequest<super::WatchConfigRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ConfigChangeEvent>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/neural_platform.config.ConfigStoreService/WatchConfig",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "neural_platform.config.ConfigStoreService",
                        "WatchConfig",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Get configuration schema for validation and documentation
        pub async fn get_schema(
            &mut self,
            request: impl tonic::IntoRequest<super::GetSchemaRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetSchemaResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/neural_platform.config.ConfigStoreService/GetSchema",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "neural_platform.config.ConfigStoreService",
                        "GetSchema",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Health check endpoint for monitoring
        pub async fn health_check(
            &mut self,
            request: impl tonic::IntoRequest<()>,
        ) -> std::result::Result<tonic::Response<super::HealthStatus>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/neural_platform.config.ConfigStoreService/HealthCheck",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "neural_platform.config.ConfigStoreService",
                        "HealthCheck",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated client implementations.
pub mod config_management_service_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Extended configuration service for administrative operations
    #[derive(Debug, Clone)]
    pub struct ConfigManagementServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ConfigManagementServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ConfigManagementServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ConfigManagementServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + Send + Sync,
        {
            ConfigManagementServiceClient::new(
                InterceptedService::new(inner, interceptor),
            )
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// List all available namespaces
        pub async fn list_namespaces(
            &mut self,
            request: impl tonic::IntoRequest<super::ListNamespacesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListNamespacesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/neural_platform.config.ConfigManagementService/ListNamespaces",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "neural_platform.config.ConfigManagementService",
                        "ListNamespaces",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get namespace configuration structure
        pub async fn get_namespace_info(
            &mut self,
            request: impl tonic::IntoRequest<super::GetNamespaceInfoRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetNamespaceInfoResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/neural_platform.config.ConfigManagementService/GetNamespaceInfo",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "neural_platform.config.ConfigManagementService",
                        "GetNamespaceInfo",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Validate configuration against schema without persisting
        pub async fn validate_config(
            &mut self,
            request: impl tonic::IntoRequest<super::ValidateConfigRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ValidateConfigResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/neural_platform.config.ConfigManagementService/ValidateConfig",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "neural_platform.config.ConfigManagementService",
                        "ValidateConfig",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get audit trail for configuration changes
        pub async fn get_audit_trail(
            &mut self,
            request: impl tonic::IntoRequest<super::GetAuditTrailRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetAuditTrailResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/neural_platform.config.ConfigManagementService/GetAuditTrail",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "neural_platform.config.ConfigManagementService",
                        "GetAuditTrail",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Backup namespace configuration
        pub async fn backup_namespace(
            &mut self,
            request: impl tonic::IntoRequest<super::BackupNamespaceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BackupNamespaceResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/neural_platform.config.ConfigManagementService/BackupNamespace",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "neural_platform.config.ConfigManagementService",
                        "BackupNamespace",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Restore namespace from backup
        pub async fn restore_namespace(
            &mut self,
            request: impl tonic::IntoRequest<super::RestoreNamespaceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RestoreNamespaceResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/neural_platform.config.ConfigManagementService/RestoreNamespace",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "neural_platform.config.ConfigManagementService",
                        "RestoreNamespace",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod config_store_service_server {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with ConfigStoreServiceServer.
    #[async_trait]
    pub trait ConfigStoreService: Send + Sync + 'static {
        /// Get configuration by namespace path with optional versioning
        async fn get_config(
            &self,
            request: tonic::Request<super::GetConfigRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetConfigResponse>,
            tonic::Status,
        >;
        /// Get multiple configuration values in a single request for performance
        async fn get_bulk_config(
            &self,
            request: tonic::Request<super::GetBulkConfigRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetBulkConfigResponse>,
            tonic::Status,
        >;
        /// Set configuration value with schema validation (admin/authorized services only)
        async fn set_config(
            &self,
            request: tonic::Request<super::SetConfigRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SetConfigResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the WatchConfig method.
        type WatchConfigStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::ConfigChangeEvent, tonic::Status>,
            >
            + Send
            + 'static;
        /// Watch for real-time configuration changes with streaming updates
        async fn watch_config(
            &self,
            request: tonic::Request<super::WatchConfigRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::WatchConfigStream>,
            tonic::Status,
        >;
        /// Get configuration schema for validation and documentation
        async fn get_schema(
            &self,
            request: tonic::Request<super::GetSchemaRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetSchemaResponse>,
            tonic::Status,
        >;
        /// Health check endpoint for monitoring
        async fn health_check(
            &self,
            request: tonic::Request<()>,
        ) -> std::result::Result<tonic::Response<super::HealthStatus>, tonic::Status>;
    }
    /// ConfigStoreService provides configuration management with namespace isolation,
    /// schema validation, and real-time updates for neural-trader platform services
    #[derive(Debug)]
    pub struct ConfigStoreServiceServer<T: ConfigStoreService> {
        inner: _Inner<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    struct _Inner<T>(Arc<T>);
    impl<T: ConfigStoreService> ConfigStoreServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            let inner = _Inner(inner);
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for ConfigStoreServiceServer<T>
    where
        T: ConfigStoreService,
        B: Body + Send + 'static,
        B::Error: Into<StdError> + Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            let inner = self.inner.clone();
            match req.uri().path() {
                "/neural_platform.config.ConfigStoreService/GetConfig" => {
                    #[allow(non_camel_case_types)]
                    struct GetConfigSvc<T: ConfigStoreService>(pub Arc<T>);
                    impl<
                        T: ConfigStoreService,
                    > tonic::server::UnaryService<super::GetConfigRequest>
                    for GetConfigSvc<T> {
                        type Response = super::GetConfigResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetConfigRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ConfigStoreService>::get_config(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetConfigSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/neural_platform.config.ConfigStoreService/GetBulkConfig" => {
                    #[allow(non_camel_case_types)]
                    struct GetBulkConfigSvc<T: ConfigStoreService>(pub Arc<T>);
                    impl<
                        T: ConfigStoreService,
                    > tonic::server::UnaryService<super::GetBulkConfigRequest>
                    for GetBulkConfigSvc<T> {
                        type Response = super::GetBulkConfigResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetBulkConfigRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ConfigStoreService>::get_bulk_config(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetBulkConfigSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/neural_platform.config.ConfigStoreService/SetConfig" => {
                    #[allow(non_camel_case_types)]
                    struct SetConfigSvc<T: ConfigStoreService>(pub Arc<T>);
                    impl<
                        T: ConfigStoreService,
                    > tonic::server::UnaryService<super::SetConfigRequest>
                    for SetConfigSvc<T> {
                        type Response = super::SetConfigResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SetConfigRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ConfigStoreService>::set_config(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = SetConfigSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/neural_platform.config.ConfigStoreService/WatchConfig" => {
                    #[allow(non_camel_case_types)]
                    struct WatchConfigSvc<T: ConfigStoreService>(pub Arc<T>);
                    impl<
                        T: ConfigStoreService,
                    > tonic::server::ServerStreamingService<super::WatchConfigRequest>
                    for WatchConfigSvc<T> {
                        type Response = super::ConfigChangeEvent;
                        type ResponseStream = T::WatchConfigStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::WatchConfigRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ConfigStoreService>::watch_config(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = WatchConfigSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/neural_platform.config.ConfigStoreService/GetSchema" => {
                    #[allow(non_camel_case_types)]
                    struct GetSchemaSvc<T: ConfigStoreService>(pub Arc<T>);
                    impl<
                        T: ConfigStoreService,
                    > tonic::server::UnaryService<super::GetSchemaRequest>
                    for GetSchemaSvc<T> {
                        type Response = super::GetSchemaResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetSchemaRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ConfigStoreService>::get_schema(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetSchemaSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/neural_platform.config.ConfigStoreService/HealthCheck" => {
                    #[allow(non_camel_case_types)]
                    struct HealthCheckSvc<T: ConfigStoreService>(pub Arc<T>);
                    impl<T: ConfigStoreService> tonic::server::UnaryService<()>
                    for HealthCheckSvc<T> {
                        type Response = super::HealthStatus;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(&mut self, request: tonic::Request<()>) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ConfigStoreService>::health_check(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = HealthCheckSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        Ok(
                            http::Response::builder()
                                .status(200)
                                .header("grpc-status", "12")
                                .header("content-type", "application/grpc")
                                .body(empty_body())
                                .unwrap(),
                        )
                    })
                }
            }
        }
    }
    impl<T: ConfigStoreService> Clone for ConfigStoreServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    impl<T: ConfigStoreService> Clone for _Inner<T> {
        fn clone(&self) -> Self {
            Self(Arc::clone(&self.0))
        }
    }
    impl<T: std::fmt::Debug> std::fmt::Debug for _Inner<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{:?}", self.0)
        }
    }
    impl<T: ConfigStoreService> tonic::server::NamedService
    for ConfigStoreServiceServer<T> {
        const NAME: &'static str = "neural_platform.config.ConfigStoreService";
    }
}
/// Generated server implementations.
pub mod config_management_service_server {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with ConfigManagementServiceServer.
    #[async_trait]
    pub trait ConfigManagementService: Send + Sync + 'static {
        /// List all available namespaces
        async fn list_namespaces(
            &self,
            request: tonic::Request<super::ListNamespacesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListNamespacesResponse>,
            tonic::Status,
        >;
        /// Get namespace configuration structure
        async fn get_namespace_info(
            &self,
            request: tonic::Request<super::GetNamespaceInfoRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetNamespaceInfoResponse>,
            tonic::Status,
        >;
        /// Validate configuration against schema without persisting
        async fn validate_config(
            &self,
            request: tonic::Request<super::ValidateConfigRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ValidateConfigResponse>,
            tonic::Status,
        >;
        /// Get audit trail for configuration changes
        async fn get_audit_trail(
            &self,
            request: tonic::Request<super::GetAuditTrailRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetAuditTrailResponse>,
            tonic::Status,
        >;
        /// Backup namespace configuration
        async fn backup_namespace(
            &self,
            request: tonic::Request<super::BackupNamespaceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BackupNamespaceResponse>,
            tonic::Status,
        >;
        /// Restore namespace from backup
        async fn restore_namespace(
            &self,
            request: tonic::Request<super::RestoreNamespaceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RestoreNamespaceResponse>,
            tonic::Status,
        >;
    }
    /// Extended configuration service for administrative operations
    #[derive(Debug)]
    pub struct ConfigManagementServiceServer<T: ConfigManagementService> {
        inner: _Inner<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    struct _Inner<T>(Arc<T>);
    impl<T: ConfigManagementService> ConfigManagementServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            let inner = _Inner(inner);
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>>
    for ConfigManagementServiceServer<T>
    where
        T: ConfigManagementService,
        B: Body + Send + 'static,
        B::Error: Into<StdError> + Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            let inner = self.inner.clone();
            match req.uri().path() {
                "/neural_platform.config.ConfigManagementService/ListNamespaces" => {
                    #[allow(non_camel_case_types)]
                    struct ListNamespacesSvc<T: ConfigManagementService>(pub Arc<T>);
                    impl<
                        T: ConfigManagementService,
                    > tonic::server::UnaryService<super::ListNamespacesRequest>
                    for ListNamespacesSvc<T> {
                        type Response = super::ListNamespacesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListNamespacesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ConfigManagementService>::list_namespaces(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = ListNamespacesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/neural_platform.config.ConfigManagementService/GetNamespaceInfo" => {
                    #[allow(non_camel_case_types)]
                    struct GetNamespaceInfoSvc<T: ConfigManagementService>(pub Arc<T>);
                    impl<
                        T: ConfigManagementService,
                    > tonic::server::UnaryService<super::GetNamespaceInfoRequest>
                    for GetNamespaceInfoSvc<T> {
                        type Response = super::GetNamespaceInfoResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetNamespaceInfoRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ConfigManagementService>::get_namespace_info(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetNamespaceInfoSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/neural_platform.config.ConfigManagementService/ValidateConfig" => {
                    #[allow(non_camel_case_types)]
                    struct ValidateConfigSvc<T: ConfigManagementService>(pub Arc<T>);
                    impl<
                        T: ConfigManagementService,
                    > tonic::server::UnaryService<super::ValidateConfigRequest>
                    for ValidateConfigSvc<T> {
                        type Response = super::ValidateConfigResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ValidateConfigRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ConfigManagementService>::validate_config(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = ValidateConfigSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/neural_platform.config.ConfigManagementService/GetAuditTrail" => {
                    #[allow(non_camel_case_types)]
                    struct GetAuditTrailSvc<T: ConfigManagementService>(pub Arc<T>);
                    impl<
                        T: ConfigManagementService,
                    > tonic::server::UnaryService<super::GetAuditTrailRequest>
                    for GetAuditTrailSvc<T> {
                        type Response = super::GetAuditTrailResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetAuditTrailRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ConfigManagementService>::get_audit_trail(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetAuditTrailSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/neural_platform.config.ConfigManagementService/BackupNamespace" => {
                    #[allow(non_camel_case_types)]
                    struct BackupNamespaceSvc<T: ConfigManagementService>(pub Arc<T>);
                    impl<
                        T: ConfigManagementService,
                    > tonic::server::UnaryService<super::BackupNamespaceRequest>
                    for BackupNamespaceSvc<T> {
                        type Response = super::BackupNamespaceResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::BackupNamespaceRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ConfigManagementService>::backup_namespace(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = BackupNamespaceSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/neural_platform.config.ConfigManagementService/RestoreNamespace" => {
                    #[allow(non_camel_case_types)]
                    struct RestoreNamespaceSvc<T: ConfigManagementService>(pub Arc<T>);
                    impl<
                        T: ConfigManagementService,
                    > tonic::server::UnaryService<super::RestoreNamespaceRequest>
                    for RestoreNamespaceSvc<T> {
                        type Response = super::RestoreNamespaceResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RestoreNamespaceRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ConfigManagementService>::restore_namespace(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = RestoreNamespaceSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        Ok(
                            http::Response::builder()
                                .status(200)
                                .header("grpc-status", "12")
                                .header("content-type", "application/grpc")
                                .body(empty_body())
                                .unwrap(),
                        )
                    })
                }
            }
        }
    }
    impl<T: ConfigManagementService> Clone for ConfigManagementServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    impl<T: ConfigManagementService> Clone for _Inner<T> {
        fn clone(&self) -> Self {
            Self(Arc::clone(&self.0))
        }
    }
    impl<T: std::fmt::Debug> std::fmt::Debug for _Inner<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{:?}", self.0)
        }
    }
    impl<T: ConfigManagementService> tonic::server::NamedService
    for ConfigManagementServiceServer<T> {
        const NAME: &'static str = "neural_platform.config.ConfigManagementService";
    }
}
