//! Processor Framework for Business Logic (DP-012 Phase 3)
//!
//! Provides trait-based abstraction for processing raw data points
//! and generating outputs like alerts, metrics, and events.

mod threshold;

pub use threshold::{
    AlertSeverity, ThresholdAlert, ThresholdConfig, ThresholdProcessor, ThresholdRule,
};

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use crate::types::RawDataPoint;

/// Output types that processors can generate
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum ProcessorOutput {
    Alert(Alert),
    Metric(Metric),
    Event(ProcessorEvent),
}

/// Alert generated by a processor
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Alert {
    pub id: String,
    pub timestamp: DateTime<Utc>,
    pub source: String,
    pub severity: Severity,
    pub alert_type: String,
    pub message: String,
    pub field: Option<String>,
    pub value: Option<f64>,
    pub threshold: Option<f64>,
    pub context: Option<serde_json::Value>,
}

/// Severity levels for alerts
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
pub enum Severity {
    Info,
    Warning,
    Critical,
}

impl std::fmt::Display for Severity {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Severity::Info => write!(f, "info"),
            Severity::Warning => write!(f, "warning"),
            Severity::Critical => write!(f, "critical"),
        }
    }
}

/// Metric for monitoring/observability
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Metric {
    pub name: String,
    pub timestamp: DateTime<Utc>,
    pub value: f64,
    pub tags: std::collections::HashMap<String, String>,
}

/// Generic event for downstream processing
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ProcessorEvent {
    pub event_type: String,
    pub timestamp: DateTime<Utc>,
    pub source: String,
    pub payload: serde_json::Value,
}

/// Base configuration for all processors
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct ProcessorConfig {
    pub name: String,
    #[serde(default = "default_enabled")]
    pub enabled: bool,
    #[serde(default)]
    pub stream_filter: Vec<String>,
    #[serde(default)]
    pub extra: serde_json::Value,
}

fn default_enabled() -> bool {
    true
}

/// Trait for processing raw data points and generating outputs
#[cfg_attr(test, mockall::automock)]
pub trait Processor: Send + Sync {
    /// Process a single data point and optionally generate output
    fn process(&self, event: &RawDataPoint) -> Option<ProcessorOutput>;
    /// Process a data point and return all generated outputs
    fn process_batch(&self, event: &RawDataPoint) -> Vec<ProcessorOutput> {
        self.process(event).into_iter().collect()
    }
    /// Get the name of this processor
    fn name(&self) -> String;
    /// Check if processor accepts events from a given stream
    fn accepts_stream(&self, stream_id: &str) -> bool;
    /// Reset any internal state
    fn reset(&self) {}
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn test_severity_ordering() {
        assert!(Severity::Info < Severity::Warning);
        assert!(Severity::Warning < Severity::Critical);
    }

    #[test]
    fn test_severity_display() {
        assert_eq!(format!("{}", Severity::Info), "info");
        assert_eq!(format!("{}", Severity::Warning), "warning");
        assert_eq!(format!("{}", Severity::Critical), "critical");
    }

    #[test]
    fn test_mock_processor() {
        let mut mock = MockProcessor::new();
        mock.expect_process().returning(|_| None);
        mock.expect_name().returning(|| "mock".to_string());
        mock.expect_accepts_stream().returning(|_| true);

        let event = RawDataPoint::new("test", json!({}));
        assert!(mock.process(&event).is_none());
    }
}
