//! Threshold Processor for alert generation (DP-012 Phase 3)

use std::collections::HashMap;
use std::sync::Mutex;
use std::time::{Duration, Instant};

use chrono::Utc;
use serde::{Deserialize, Serialize};
use tracing::{debug, info};
use uuid::Uuid;

use super::{Alert, Processor, ProcessorOutput, Severity};
use crate::types::RawDataPoint;

/// Alert severity levels for config
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Default)]
#[serde(rename_all = "lowercase")]
pub enum AlertSeverity {
    Info,
    #[default]
    Warning,
    Critical,
}

impl From<AlertSeverity> for Severity {
    fn from(s: AlertSeverity) -> Self {
        match s {
            AlertSeverity::Info => Severity::Info,
            AlertSeverity::Warning => Severity::Warning,
            AlertSeverity::Critical => Severity::Critical,
        }
    }
}

/// Threshold rule for a specific field
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ThresholdRule {
    pub field: String,
    #[serde(default)]
    pub warning: Option<f64>,
    #[serde(default)]
    pub critical: Option<f64>,
    #[serde(default = "default_cooldown")]
    pub cooldown_seconds: u64,
    #[serde(default)]
    pub min_warning: Option<f64>,
    #[serde(default)]
    pub min_critical: Option<f64>,
}

fn default_cooldown() -> u64 {
    300
}

impl ThresholdRule {
    pub fn new(field: impl Into<String>) -> Self {
        Self {
            field: field.into(),
            warning: None,
            critical: None,
            cooldown_seconds: default_cooldown(),
            min_warning: None,
            min_critical: None,
        }
    }

    pub fn with_warning(mut self, threshold: f64) -> Self {
        self.warning = Some(threshold);
        self
    }

    pub fn with_critical(mut self, threshold: f64) -> Self {
        self.critical = Some(threshold);
        self
    }

    pub fn with_cooldown(mut self, seconds: u64) -> Self {
        self.cooldown_seconds = seconds;
        self
    }
}

/// Configuration for ThresholdProcessor
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct ThresholdConfig {
    #[serde(default = "default_name")]
    pub name: String,
    #[serde(default = "default_enabled")]
    pub enabled: bool,
    #[serde(default)]
    pub stream_filter: Vec<String>,
    #[serde(default)]
    pub thresholds: Vec<ThresholdRule>,
}

fn default_name() -> String {
    "threshold-processor".to_string()
}

fn default_enabled() -> bool {
    true
}

/// Alert generated by threshold check
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ThresholdAlert {
    pub field: String,
    pub value: f64,
    pub threshold: f64,
    pub severity: AlertSeverity,
    pub is_minimum: bool,
}

#[derive(Debug)]
struct CooldownEntry {
    last_triggered: Instant,
    cooldown_duration: Duration,
}

impl CooldownEntry {
    fn new(cooldown_duration: Duration) -> Self {
        Self {
            last_triggered: Instant::now(),
            cooldown_duration,
        }
    }

    fn is_expired(&self) -> bool {
        self.last_triggered.elapsed() >= self.cooldown_duration
    }

    fn reset(&mut self) {
        self.last_triggered = Instant::now();
    }
}

/// Threshold processor for generating alerts
pub struct ThresholdProcessor {
    config: ThresholdConfig,
    cooldowns: Mutex<HashMap<String, CooldownEntry>>,
}

impl ThresholdProcessor {
    pub fn new(config: ThresholdConfig) -> Self {
        Self {
            config,
            cooldowns: Mutex::new(HashMap::new()),
        }
    }

    pub fn with_rule(rule: ThresholdRule) -> Self {
        Self::new(ThresholdConfig {
            thresholds: vec![rule],
            ..Default::default()
        })
    }

    fn check_rule(&self, rule: &ThresholdRule, value: f64) -> Option<ThresholdAlert> {
        if let Some(critical) = rule.critical {
            if value >= critical {
                return Some(ThresholdAlert {
                    field: rule.field.clone(),
                    value,
                    threshold: critical,
                    severity: AlertSeverity::Critical,
                    is_minimum: false,
                });
            }
        }

        if let Some(min_critical) = rule.min_critical {
            if value <= min_critical {
                return Some(ThresholdAlert {
                    field: rule.field.clone(),
                    value,
                    threshold: min_critical,
                    severity: AlertSeverity::Critical,
                    is_minimum: true,
                });
            }
        }

        if let Some(warning) = rule.warning {
            if value >= warning {
                return Some(ThresholdAlert {
                    field: rule.field.clone(),
                    value,
                    threshold: warning,
                    severity: AlertSeverity::Warning,
                    is_minimum: false,
                });
            }
        }

        if let Some(min_warning) = rule.min_warning {
            if value <= min_warning {
                return Some(ThresholdAlert {
                    field: rule.field.clone(),
                    value,
                    threshold: min_warning,
                    severity: AlertSeverity::Warning,
                    is_minimum: true,
                });
            }
        }

        None
    }

    fn is_in_cooldown(&self, key: &str) -> bool {
        let cooldowns = self.cooldowns.lock().unwrap();
        cooldowns.get(key).map(|e| !e.is_expired()).unwrap_or(false)
    }

    fn start_cooldown(&self, key: &str, duration: Duration) {
        let mut cooldowns = self.cooldowns.lock().unwrap();
        if let Some(entry) = cooldowns.get_mut(key) {
            entry.reset();
        } else {
            cooldowns.insert(key.to_string(), CooldownEntry::new(duration));
        }
    }

    fn cooldown_key(field: &str, severity: &AlertSeverity, source: &str) -> String {
        let sev = match severity {
            AlertSeverity::Info => "info",
            AlertSeverity::Warning => "warning",
            AlertSeverity::Critical => "critical",
        };
        format!("{}:{}:{}", field, sev, source)
    }

    fn extract_value(payload: &serde_json::Value, field: &str) -> Option<f64> {
        let parts: Vec<&str> = field.split('.').collect();
        let mut current = payload;
        for part in parts {
            current = current.get(part)?;
        }
        current.as_f64()
    }

    fn create_alert(
        &self,
        threshold_alert: &ThresholdAlert,
        source_id: &str,
        ndp_id: Option<&str>,
    ) -> Alert {
        let direction = if threshold_alert.is_minimum {
            "below"
        } else {
            "above"
        };
        let sev = match threshold_alert.severity {
            AlertSeverity::Info => "informational",
            AlertSeverity::Warning => "warning",
            AlertSeverity::Critical => "critical",
        };

        Alert {
            id: Uuid::new_v4().to_string(),
            timestamp: Utc::now(),
            source: source_id.to_string(),
            severity: threshold_alert.severity.into(),
            alert_type: "threshold".to_string(),
            message: format!(
                "{} {} is {} {} threshold ({:.2} {} {:.2})",
                threshold_alert.field,
                sev,
                direction,
                sev,
                threshold_alert.value,
                if threshold_alert.is_minimum {
                    "<="
                } else {
                    ">="
                },
                threshold_alert.threshold
            ),
            field: Some(threshold_alert.field.clone()),
            value: Some(threshold_alert.value),
            threshold: Some(threshold_alert.threshold),
            context: ndp_id.map(|id| serde_json::json!({"ndp_id": id})),
        }
    }
}

impl Processor for ThresholdProcessor {
    fn process(&self, event: &RawDataPoint) -> Option<ProcessorOutput> {
        if !self.config.enabled {
            return None;
        }

        for rule in &self.config.thresholds {
            if let Some(value) = Self::extract_value(&event.raw_payload, &rule.field) {
                if let Some(threshold_alert) = self.check_rule(rule, value) {
                    let key = Self::cooldown_key(
                        &threshold_alert.field,
                        &threshold_alert.severity,
                        &event.source_id,
                    );

                    if self.is_in_cooldown(&key) {
                        debug!(field = %threshold_alert.field, "Alert suppressed due to cooldown");
                        continue;
                    }

                    self.start_cooldown(&key, Duration::from_secs(rule.cooldown_seconds));

                    let alert = self.create_alert(
                        &threshold_alert,
                        &event.source_id,
                        event.ndp_id.as_deref(),
                    );

                    info!(
                        field = %threshold_alert.field,
                        value = threshold_alert.value,
                        "Threshold alert triggered"
                    );

                    return Some(ProcessorOutput::Alert(alert));
                }
            }
        }

        None
    }

    fn name(&self) -> String {
        self.config.name.clone()
    }

    fn accepts_stream(&self, stream_id: &str) -> bool {
        if self.config.stream_filter.is_empty() {
            true
        } else {
            self.config.stream_filter.iter().any(|s| s == stream_id)
        }
    }

    fn reset(&self) {
        let mut cooldowns = self.cooldowns.lock().unwrap();
        cooldowns.clear();
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn test_threshold_rule_builder() {
        let rule = ThresholdRule::new("pm25")
            .with_warning(35.0)
            .with_critical(55.0)
            .with_cooldown(300);

        assert_eq!(rule.field, "pm25");
        assert_eq!(rule.warning, Some(35.0));
        assert_eq!(rule.critical, Some(55.0));
    }

    #[test]
    fn test_processor_no_alert_under_threshold() {
        let config = ThresholdConfig {
            enabled: true,
            thresholds: vec![ThresholdRule::new("pm25").with_warning(35.0)],
            ..Default::default()
        };

        let processor = ThresholdProcessor::new(config);
        let event = RawDataPoint::new("test", json!({"pm25": 20.0}));

        assert!(processor.process(&event).is_none());
    }

    #[test]
    fn test_processor_warning_alert() {
        let config = ThresholdConfig {
            enabled: true,
            thresholds: vec![ThresholdRule::new("pm25").with_warning(35.0)],
            ..Default::default()
        };

        let processor = ThresholdProcessor::new(config);
        let event = RawDataPoint::new("test", json!({"pm25": 40.0}));

        let result = processor.process(&event);
        assert!(result.is_some());

        if let Some(ProcessorOutput::Alert(alert)) = result {
            assert_eq!(alert.severity, Severity::Warning);
            assert_eq!(alert.value, Some(40.0));
        }
    }

    #[test]
    fn test_processor_critical_alert() {
        let config = ThresholdConfig {
            enabled: true,
            thresholds: vec![ThresholdRule::new("pm25")
                .with_warning(35.0)
                .with_critical(55.0)],
            ..Default::default()
        };

        let processor = ThresholdProcessor::new(config);
        let event = RawDataPoint::new("test", json!({"pm25": 60.0}));

        let result = processor.process(&event);
        assert!(result.is_some()); // Ensure result exists
        if let Some(ProcessorOutput::Alert(alert)) = result {
            assert_eq!(alert.severity, Severity::Critical);
        }
    }

    #[test]
    fn test_processor_disabled() {
        let config = ThresholdConfig {
            enabled: false,
            thresholds: vec![ThresholdRule::new("pm25").with_warning(35.0)],
            ..Default::default()
        };

        let processor = ThresholdProcessor::new(config);
        let event = RawDataPoint::new("test", json!({"pm25": 100.0}));

        assert!(processor.process(&event).is_none());
    }
}
