// This file is @generated by prost-build.
pub mod neural_trader {
    pub mod interfaces {
        pub mod action {
            include!("neural_trader.interfaces.action.rs");
        }
        pub mod execution {
            include!("neural_trader.interfaces.execution.rs");
        }
        pub mod ingestion {
            include!("neural_trader.interfaces.ingestion.rs");
        }
        pub mod mlops {
            include!("neural_trader.interfaces.mlops.rs");
        }
    }
}
