// This file is @generated by prost-build.
/// Standard envelope for all messages entering the event bus
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventEnvelope {
    /// Unique message identifier
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    /// Correlation ID for tracking related messages
    #[prost(string, tag = "2")]
    pub correlation_id: ::prost::alloc::string::String,
    /// Source system identifier
    #[prost(string, tag = "3")]
    pub source: ::prost::alloc::string::String,
    /// Domain this message belongs to
    #[prost(string, tag = "4")]
    pub domain: ::prost::alloc::string::String,
    /// Event type for routing
    #[prost(string, tag = "5")]
    pub event_type: ::prost::alloc::string::String,
    /// Schema version of the payload
    #[prost(string, tag = "6")]
    pub schema_version: ::prost::alloc::string::String,
    /// When the event was created
    #[prost(message, optional, tag = "7")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    /// When the event was ingested
    #[prost(message, optional, tag = "8")]
    pub ingested_at: ::core::option::Option<::prost_types::Timestamp>,
    /// Routing metadata
    #[prost(message, optional, tag = "9")]
    pub routing: ::core::option::Option<RoutingMetadata>,
    /// Quality metadata
    #[prost(message, optional, tag = "10")]
    pub quality: ::core::option::Option<QualityMetadata>,
    /// The actual event payload (domain-specific)
    #[prost(message, optional, tag = "11")]
    pub payload: ::core::option::Option<::prost_types::Any>,
    /// Headers for additional metadata
    #[prost(map = "string, string", tag = "12")]
    pub headers: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// Tracing context for distributed tracing
    #[prost(message, optional, tag = "13")]
    pub tracing: ::core::option::Option<TracingContext>,
}
/// Routing information for the message
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RoutingMetadata {
    /// Target topic/stream
    #[prost(string, tag = "1")]
    pub topic: ::prost::alloc::string::String,
    /// Partition key for ordering
    #[prost(string, tag = "2")]
    pub partition_key: ::prost::alloc::string::String,
    /// Priority level (0-9, 0 highest)
    #[prost(int32, tag = "3")]
    pub priority: i32,
    /// TTL in seconds (0 = no expiry)
    #[prost(int64, tag = "4")]
    pub ttl_seconds: i64,
    /// Routing tags for filtering
    #[prost(string, repeated, tag = "5")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Retry policy
    #[prost(message, optional, tag = "6")]
    pub retry_policy: ::core::option::Option<RetryPolicy>,
}
/// Data quality indicators
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QualityMetadata {
    /// Completeness score (0-100)
    #[prost(float, tag = "1")]
    pub completeness: f32,
    /// Timeliness in milliseconds
    #[prost(int64, tag = "2")]
    pub latency_ms: i64,
    /// Data validation status
    #[prost(enumeration = "ValidationStatus", tag = "3")]
    pub validation_status: i32,
    /// Quality score (0-100)
    #[prost(float, tag = "4")]
    pub quality_score: f32,
    /// Anomaly indicators
    #[prost(message, repeated, tag = "5")]
    pub anomalies: ::prost::alloc::vec::Vec<AnomalyIndicator>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AnomalyIndicator {
    #[prost(string, tag = "1")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(float, tag = "2")]
    pub severity: f32,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
}
/// Retry configuration
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RetryPolicy {
    #[prost(int32, tag = "1")]
    pub max_attempts: i32,
    #[prost(int64, tag = "2")]
    pub initial_delay_ms: i64,
    #[prost(float, tag = "3")]
    pub backoff_multiplier: f32,
    #[prost(int64, tag = "4")]
    pub max_delay_ms: i64,
    #[prost(string, repeated, tag = "5")]
    pub retryable_errors: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Distributed tracing context
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TracingContext {
    #[prost(string, tag = "1")]
    pub trace_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub span_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub parent_span_id: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "4")]
    pub baggage: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
/// Batch ingestion request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchIngestionRequest {
    #[prost(message, repeated, tag = "1")]
    pub events: ::prost::alloc::vec::Vec<EventEnvelope>,
    #[prost(string, tag = "2")]
    pub batch_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub options: ::core::option::Option<IngestOptions>,
}
/// Ingestion options
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IngestOptions {
    #[prost(bool, tag = "1")]
    pub validate_schema: bool,
    #[prost(bool, tag = "2")]
    pub async_mode: bool,
    #[prost(bool, tag = "3")]
    pub enable_dedup: bool,
    #[prost(int32, tag = "4")]
    pub batch_size: i32,
    #[prost(int64, tag = "5")]
    pub timeout_ms: i64,
}
/// Ingestion response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IngestionResponse {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub success: bool,
    #[prost(message, repeated, tag = "3")]
    pub results: ::prost::alloc::vec::Vec<IngestionResult>,
    #[prost(message, optional, tag = "4")]
    pub metrics: ::core::option::Option<IngestionMetrics>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IngestionResult {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub accepted: bool,
    #[prost(string, tag = "3")]
    pub error_code: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub error_message: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub assigned_partition: ::prost::alloc::string::String,
    #[prost(int64, tag = "6")]
    pub offset: i64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IngestionMetrics {
    #[prost(int32, tag = "1")]
    pub total_received: i32,
    #[prost(int32, tag = "2")]
    pub total_accepted: i32,
    #[prost(int32, tag = "3")]
    pub total_rejected: i32,
    #[prost(int64, tag = "4")]
    pub processing_time_ms: i64,
    #[prost(float, tag = "5")]
    pub throughput_mps: f32,
}
/// Error handling
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IngestionError {
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub details: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(map = "string, string", tag = "5")]
    pub context: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(bool, tag = "6")]
    pub retryable: bool,
}
/// Backpressure signals
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BackpressureSignal {
    #[prost(enumeration = "backpressure_signal::Level", tag = "1")]
    pub level: i32,
    #[prost(float, tag = "2")]
    pub utilization: f32,
    #[prost(int64, tag = "3")]
    pub queue_depth: i64,
    #[prost(int64, tag = "4")]
    pub recommended_delay_ms: i64,
    #[prost(string, tag = "5")]
    pub reason: ::prost::alloc::string::String,
}
/// Nested message and enum types in `BackpressureSignal`.
pub mod backpressure_signal {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Level {
        Unspecified = 0,
        Normal = 1,
        Warning = 2,
        Critical = 3,
        Emergency = 4,
    }
    impl Level {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Level::Unspecified => "LEVEL_UNSPECIFIED",
                Level::Normal => "LEVEL_NORMAL",
                Level::Warning => "LEVEL_WARNING",
                Level::Critical => "LEVEL_CRITICAL",
                Level::Emergency => "LEVEL_EMERGENCY",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "LEVEL_UNSPECIFIED" => Some(Self::Unspecified),
                "LEVEL_NORMAL" => Some(Self::Normal),
                "LEVEL_WARNING" => Some(Self::Warning),
                "LEVEL_CRITICAL" => Some(Self::Critical),
                "LEVEL_EMERGENCY" => Some(Self::Emergency),
                _ => None,
            }
        }
    }
}
/// Stream routing rules
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamRoutingRule {
    #[prost(string, tag = "1")]
    pub rule_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub r#match: ::core::option::Option<stream_routing_rule::Criteria>,
    #[prost(message, repeated, tag = "4")]
    pub actions: ::prost::alloc::vec::Vec<stream_routing_rule::Action>,
    #[prost(bool, tag = "5")]
    pub enabled: bool,
    #[prost(int32, tag = "6")]
    pub order: i32,
}
/// Nested message and enum types in `StreamRoutingRule`.
pub mod stream_routing_rule {
    /// Matching criteria
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Criteria {
        #[prost(string, tag = "1")]
        pub domain: ::prost::alloc::string::String,
        #[prost(string, tag = "2")]
        pub event_type: ::prost::alloc::string::String,
        #[prost(map = "string, string", tag = "3")]
        pub headers: ::std::collections::HashMap<
            ::prost::alloc::string::String,
            ::prost::alloc::string::String,
        >,
        /// JSONPath or similar
        #[prost(string, tag = "4")]
        pub payload_filter: ::prost::alloc::string::String,
    }
    /// Routing actions
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Action {
        #[prost(string, tag = "1")]
        pub target_topic: ::prost::alloc::string::String,
        #[prost(string, tag = "2")]
        pub transformation: ::prost::alloc::string::String,
        #[prost(map = "string, string", tag = "3")]
        pub add_headers: ::std::collections::HashMap<
            ::prost::alloc::string::String,
            ::prost::alloc::string::String,
        >,
        #[prost(int32, tag = "4")]
        pub priority_override: i32,
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidationResponse {
    #[prost(bool, tag = "1")]
    pub valid: bool,
    #[prost(message, repeated, tag = "2")]
    pub errors: ::prost::alloc::vec::Vec<ValidationError>,
    #[prost(message, repeated, tag = "3")]
    pub warnings: ::prost::alloc::vec::Vec<ValidationWarning>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidationError {
    #[prost(string, tag = "1")]
    pub field: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub expected: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub actual: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidationWarning {
    #[prost(string, tag = "1")]
    pub field: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub warning: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchValidationRequest {
    #[prost(message, repeated, tag = "1")]
    pub events: ::prost::alloc::vec::Vec<EventEnvelope>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchValidationResponse {
    #[prost(map = "string, message", tag = "1")]
    pub results: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ValidationResponse,
    >,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ValidationStatus {
    Unspecified = 0,
    Passed = 1,
    Failed = 2,
    Partial = 3,
    Skipped = 4,
}
impl ValidationStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            ValidationStatus::Unspecified => "VALIDATION_STATUS_UNSPECIFIED",
            ValidationStatus::Passed => "VALIDATION_STATUS_PASSED",
            ValidationStatus::Failed => "VALIDATION_STATUS_FAILED",
            ValidationStatus::Partial => "VALIDATION_STATUS_PARTIAL",
            ValidationStatus::Skipped => "VALIDATION_STATUS_SKIPPED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "VALIDATION_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "VALIDATION_STATUS_PASSED" => Some(Self::Passed),
            "VALIDATION_STATUS_FAILED" => Some(Self::Failed),
            "VALIDATION_STATUS_PARTIAL" => Some(Self::Partial),
            "VALIDATION_STATUS_SKIPPED" => Some(Self::Skipped),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod ingestion_service_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Service definition
    #[derive(Debug, Clone)]
    pub struct IngestionServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl IngestionServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> IngestionServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> IngestionServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + Send + Sync,
        {
            IngestionServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Single event ingestion
        pub async fn ingest(
            &mut self,
            request: impl tonic::IntoRequest<super::EventEnvelope>,
        ) -> std::result::Result<
            tonic::Response<super::IngestionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/neural_trader.interfaces.ingestion.IngestionService/Ingest",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "neural_trader.interfaces.ingestion.IngestionService",
                        "Ingest",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Batch ingestion
        pub async fn ingest_batch(
            &mut self,
            request: impl tonic::IntoRequest<super::BatchIngestionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::IngestionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/neural_trader.interfaces.ingestion.IngestionService/IngestBatch",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "neural_trader.interfaces.ingestion.IngestionService",
                        "IngestBatch",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Streaming ingestion
        pub async fn ingest_stream(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::EventEnvelope>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::IngestionResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/neural_trader.interfaces.ingestion.IngestionService/IngestStream",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "neural_trader.interfaces.ingestion.IngestionService",
                        "IngestStream",
                    ),
                );
            self.inner.streaming(req, path, codec).await
        }
        /// Get backpressure status
        pub async fn get_backpressure(
            &mut self,
            request: impl tonic::IntoRequest<::prost_types::Empty>,
        ) -> std::result::Result<
            tonic::Response<super::BackpressureSignal>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/neural_trader.interfaces.ingestion.IngestionService/GetBackpressure",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "neural_trader.interfaces.ingestion.IngestionService",
                        "GetBackpressure",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Manage routing rules
        pub async fn update_routing_rules(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::StreamRoutingRule>,
        ) -> std::result::Result<tonic::Response<::prost_types::Empty>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/neural_trader.interfaces.ingestion.IngestionService/UpdateRoutingRules",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "neural_trader.interfaces.ingestion.IngestionService",
                        "UpdateRoutingRules",
                    ),
                );
            self.inner.client_streaming(req, path, codec).await
        }
    }
}
/// Generated client implementations.
pub mod schema_validation_service_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Schema validation service
    #[derive(Debug, Clone)]
    pub struct SchemaValidationServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl SchemaValidationServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> SchemaValidationServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> SchemaValidationServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + Send + Sync,
        {
            SchemaValidationServiceClient::new(
                InterceptedService::new(inner, interceptor),
            )
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Validate a message against its schema
        pub async fn validate(
            &mut self,
            request: impl tonic::IntoRequest<super::EventEnvelope>,
        ) -> std::result::Result<
            tonic::Response<super::ValidationResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/neural_trader.interfaces.ingestion.SchemaValidationService/Validate",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "neural_trader.interfaces.ingestion.SchemaValidationService",
                        "Validate",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Batch validation
        pub async fn validate_batch(
            &mut self,
            request: impl tonic::IntoRequest<super::BatchValidationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BatchValidationResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/neural_trader.interfaces.ingestion.SchemaValidationService/ValidateBatch",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "neural_trader.interfaces.ingestion.SchemaValidationService",
                        "ValidateBatch",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod ingestion_service_server {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with IngestionServiceServer.
    #[async_trait]
    pub trait IngestionService: Send + Sync + 'static {
        /// Single event ingestion
        async fn ingest(
            &self,
            request: tonic::Request<super::EventEnvelope>,
        ) -> std::result::Result<
            tonic::Response<super::IngestionResponse>,
            tonic::Status,
        >;
        /// Batch ingestion
        async fn ingest_batch(
            &self,
            request: tonic::Request<super::BatchIngestionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::IngestionResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the IngestStream method.
        type IngestStreamStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::IngestionResponse, tonic::Status>,
            >
            + Send
            + 'static;
        /// Streaming ingestion
        async fn ingest_stream(
            &self,
            request: tonic::Request<tonic::Streaming<super::EventEnvelope>>,
        ) -> std::result::Result<
            tonic::Response<Self::IngestStreamStream>,
            tonic::Status,
        >;
        /// Get backpressure status
        async fn get_backpressure(
            &self,
            request: tonic::Request<::prost_types::Empty>,
        ) -> std::result::Result<
            tonic::Response<super::BackpressureSignal>,
            tonic::Status,
        >;
        /// Manage routing rules
        async fn update_routing_rules(
            &self,
            request: tonic::Request<tonic::Streaming<super::StreamRoutingRule>>,
        ) -> std::result::Result<tonic::Response<::prost_types::Empty>, tonic::Status>;
    }
    /// Service definition
    #[derive(Debug)]
    pub struct IngestionServiceServer<T: IngestionService> {
        inner: _Inner<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    struct _Inner<T>(Arc<T>);
    impl<T: IngestionService> IngestionServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            let inner = _Inner(inner);
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for IngestionServiceServer<T>
    where
        T: IngestionService,
        B: Body + Send + 'static,
        B::Error: Into<StdError> + Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            let inner = self.inner.clone();
            match req.uri().path() {
                "/neural_trader.interfaces.ingestion.IngestionService/Ingest" => {
                    #[allow(non_camel_case_types)]
                    struct IngestSvc<T: IngestionService>(pub Arc<T>);
                    impl<
                        T: IngestionService,
                    > tonic::server::UnaryService<super::EventEnvelope>
                    for IngestSvc<T> {
                        type Response = super::IngestionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::EventEnvelope>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as IngestionService>::ingest(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = IngestSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/neural_trader.interfaces.ingestion.IngestionService/IngestBatch" => {
                    #[allow(non_camel_case_types)]
                    struct IngestBatchSvc<T: IngestionService>(pub Arc<T>);
                    impl<
                        T: IngestionService,
                    > tonic::server::UnaryService<super::BatchIngestionRequest>
                    for IngestBatchSvc<T> {
                        type Response = super::IngestionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::BatchIngestionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as IngestionService>::ingest_batch(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = IngestBatchSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/neural_trader.interfaces.ingestion.IngestionService/IngestStream" => {
                    #[allow(non_camel_case_types)]
                    struct IngestStreamSvc<T: IngestionService>(pub Arc<T>);
                    impl<
                        T: IngestionService,
                    > tonic::server::StreamingService<super::EventEnvelope>
                    for IngestStreamSvc<T> {
                        type Response = super::IngestionResponse;
                        type ResponseStream = T::IngestStreamStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::EventEnvelope>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as IngestionService>::ingest_stream(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = IngestStreamSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/neural_trader.interfaces.ingestion.IngestionService/GetBackpressure" => {
                    #[allow(non_camel_case_types)]
                    struct GetBackpressureSvc<T: IngestionService>(pub Arc<T>);
                    impl<
                        T: IngestionService,
                    > tonic::server::UnaryService<::prost_types::Empty>
                    for GetBackpressureSvc<T> {
                        type Response = super::BackpressureSignal;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<::prost_types::Empty>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as IngestionService>::get_backpressure(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetBackpressureSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/neural_trader.interfaces.ingestion.IngestionService/UpdateRoutingRules" => {
                    #[allow(non_camel_case_types)]
                    struct UpdateRoutingRulesSvc<T: IngestionService>(pub Arc<T>);
                    impl<
                        T: IngestionService,
                    > tonic::server::ClientStreamingService<super::StreamRoutingRule>
                    for UpdateRoutingRulesSvc<T> {
                        type Response = ::prost_types::Empty;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::StreamRoutingRule>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as IngestionService>::update_routing_rules(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = UpdateRoutingRulesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.client_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        Ok(
                            http::Response::builder()
                                .status(200)
                                .header("grpc-status", "12")
                                .header("content-type", "application/grpc")
                                .body(empty_body())
                                .unwrap(),
                        )
                    })
                }
            }
        }
    }
    impl<T: IngestionService> Clone for IngestionServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    impl<T: IngestionService> Clone for _Inner<T> {
        fn clone(&self) -> Self {
            Self(Arc::clone(&self.0))
        }
    }
    impl<T: std::fmt::Debug> std::fmt::Debug for _Inner<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{:?}", self.0)
        }
    }
    impl<T: IngestionService> tonic::server::NamedService for IngestionServiceServer<T> {
        const NAME: &'static str = "neural_trader.interfaces.ingestion.IngestionService";
    }
}
/// Generated server implementations.
pub mod schema_validation_service_server {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with SchemaValidationServiceServer.
    #[async_trait]
    pub trait SchemaValidationService: Send + Sync + 'static {
        /// Validate a message against its schema
        async fn validate(
            &self,
            request: tonic::Request<super::EventEnvelope>,
        ) -> std::result::Result<
            tonic::Response<super::ValidationResponse>,
            tonic::Status,
        >;
        /// Batch validation
        async fn validate_batch(
            &self,
            request: tonic::Request<super::BatchValidationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BatchValidationResponse>,
            tonic::Status,
        >;
    }
    /// Schema validation service
    #[derive(Debug)]
    pub struct SchemaValidationServiceServer<T: SchemaValidationService> {
        inner: _Inner<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    struct _Inner<T>(Arc<T>);
    impl<T: SchemaValidationService> SchemaValidationServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            let inner = _Inner(inner);
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>>
    for SchemaValidationServiceServer<T>
    where
        T: SchemaValidationService,
        B: Body + Send + 'static,
        B::Error: Into<StdError> + Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            let inner = self.inner.clone();
            match req.uri().path() {
                "/neural_trader.interfaces.ingestion.SchemaValidationService/Validate" => {
                    #[allow(non_camel_case_types)]
                    struct ValidateSvc<T: SchemaValidationService>(pub Arc<T>);
                    impl<
                        T: SchemaValidationService,
                    > tonic::server::UnaryService<super::EventEnvelope>
                    for ValidateSvc<T> {
                        type Response = super::ValidationResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::EventEnvelope>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SchemaValidationService>::validate(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = ValidateSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/neural_trader.interfaces.ingestion.SchemaValidationService/ValidateBatch" => {
                    #[allow(non_camel_case_types)]
                    struct ValidateBatchSvc<T: SchemaValidationService>(pub Arc<T>);
                    impl<
                        T: SchemaValidationService,
                    > tonic::server::UnaryService<super::BatchValidationRequest>
                    for ValidateBatchSvc<T> {
                        type Response = super::BatchValidationResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::BatchValidationRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SchemaValidationService>::validate_batch(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = ValidateBatchSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        Ok(
                            http::Response::builder()
                                .status(200)
                                .header("grpc-status", "12")
                                .header("content-type", "application/grpc")
                                .body(empty_body())
                                .unwrap(),
                        )
                    })
                }
            }
        }
    }
    impl<T: SchemaValidationService> Clone for SchemaValidationServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    impl<T: SchemaValidationService> Clone for _Inner<T> {
        fn clone(&self) -> Self {
            Self(Arc::clone(&self.0))
        }
    }
    impl<T: std::fmt::Debug> std::fmt::Debug for _Inner<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{:?}", self.0)
        }
    }
    impl<T: SchemaValidationService> tonic::server::NamedService
    for SchemaValidationServiceServer<T> {
        const NAME: &'static str = "neural_trader.interfaces.ingestion.SchemaValidationService";
    }
}
