// This file is @generated by prost-build.
/// Trading decision from model
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TradingDecision {
    #[prost(string, tag = "1")]
    pub decision_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub model_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub strategy_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(enumeration = "DecisionType", tag = "5")]
    pub r#type: i32,
    #[prost(message, optional, tag = "6")]
    pub action: ::core::option::Option<ActionDetails>,
    #[prost(message, optional, tag = "7")]
    pub risk: ::core::option::Option<RiskAssessment>,
    #[prost(message, optional, tag = "8")]
    pub constraints: ::core::option::Option<ExecutionConstraints>,
    #[prost(message, optional, tag = "9")]
    pub metadata: ::core::option::Option<DecisionMetadata>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ActionDetails {
    #[prost(string, tag = "1")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub exchange: ::prost::alloc::string::String,
    #[prost(enumeration = "action_details::Side", tag = "3")]
    pub side: i32,
    #[prost(message, optional, tag = "4")]
    pub quantity: ::core::option::Option<action_details::Quantity>,
    #[prost(message, optional, tag = "5")]
    pub price: ::core::option::Option<action_details::Price>,
    #[prost(message, optional, tag = "6")]
    pub order_type: ::core::option::Option<action_details::OrderType>,
    #[prost(message, optional, tag = "7")]
    pub exit: ::core::option::Option<action_details::ExitStrategy>,
}
/// Nested message and enum types in `ActionDetails`.
pub mod action_details {
    /// Quantities
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Quantity {
        #[prost(float, tag = "1")]
        pub base: f32,
        #[prost(float, tag = "2")]
        pub quote: f32,
        #[prost(float, tag = "3")]
        pub percentage_of_portfolio: f32,
        #[prost(float, tag = "4")]
        pub dollar_value: f32,
    }
    /// Pricing
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Price {
        #[prost(float, tag = "1")]
        pub limit_price: f32,
        #[prost(float, tag = "2")]
        pub stop_price: f32,
        #[prost(float, tag = "3")]
        pub market_price_reference: f32,
        #[prost(float, tag = "4")]
        pub slippage_tolerance: f32,
    }
    /// Order type specifics
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct OrderType {
        #[prost(enumeration = "order_type::Type", tag = "1")]
        pub r#type: i32,
        #[prost(enumeration = "order_type::TimeInForce", tag = "2")]
        pub time_in_force: i32,
        #[prost(message, optional, tag = "3")]
        pub expire_time: ::core::option::Option<::prost_types::Timestamp>,
    }
    /// Nested message and enum types in `OrderType`.
    pub mod order_type {
        #[derive(
            Clone,
            Copy,
            Debug,
            PartialEq,
            Eq,
            Hash,
            PartialOrd,
            Ord,
            ::prost::Enumeration
        )]
        #[repr(i32)]
        pub enum Type {
            Unspecified = 0,
            Market = 1,
            Limit = 2,
            StopMarket = 3,
            StopLimit = 4,
            TrailingStop = 5,
            Iceberg = 6,
        }
        impl Type {
            /// String value of the enum field names used in the ProtoBuf definition.
            ///
            /// The values are not transformed in any way and thus are considered stable
            /// (if the ProtoBuf definition does not change) and safe for programmatic use.
            pub fn as_str_name(&self) -> &'static str {
                match self {
                    Type::Unspecified => "TYPE_UNSPECIFIED",
                    Type::Market => "TYPE_MARKET",
                    Type::Limit => "TYPE_LIMIT",
                    Type::StopMarket => "TYPE_STOP_MARKET",
                    Type::StopLimit => "TYPE_STOP_LIMIT",
                    Type::TrailingStop => "TYPE_TRAILING_STOP",
                    Type::Iceberg => "TYPE_ICEBERG",
                }
            }
            /// Creates an enum from field names used in the ProtoBuf definition.
            pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
                match value {
                    "TYPE_UNSPECIFIED" => Some(Self::Unspecified),
                    "TYPE_MARKET" => Some(Self::Market),
                    "TYPE_LIMIT" => Some(Self::Limit),
                    "TYPE_STOP_MARKET" => Some(Self::StopMarket),
                    "TYPE_STOP_LIMIT" => Some(Self::StopLimit),
                    "TYPE_TRAILING_STOP" => Some(Self::TrailingStop),
                    "TYPE_ICEBERG" => Some(Self::Iceberg),
                    _ => None,
                }
            }
        }
        /// Time in force
        #[derive(
            Clone,
            Copy,
            Debug,
            PartialEq,
            Eq,
            Hash,
            PartialOrd,
            Ord,
            ::prost::Enumeration
        )]
        #[repr(i32)]
        pub enum TimeInForce {
            Unspecified = 0,
            /// Good till canceled
            Gtc = 1,
            /// Immediate or cancel
            Ioc = 2,
            /// Fill or kill
            Fok = 3,
            /// Good till date
            Gtd = 4,
        }
        impl TimeInForce {
            /// String value of the enum field names used in the ProtoBuf definition.
            ///
            /// The values are not transformed in any way and thus are considered stable
            /// (if the ProtoBuf definition does not change) and safe for programmatic use.
            pub fn as_str_name(&self) -> &'static str {
                match self {
                    TimeInForce::Unspecified => "TIME_IN_FORCE_UNSPECIFIED",
                    TimeInForce::Gtc => "TIME_IN_FORCE_GTC",
                    TimeInForce::Ioc => "TIME_IN_FORCE_IOC",
                    TimeInForce::Fok => "TIME_IN_FORCE_FOK",
                    TimeInForce::Gtd => "TIME_IN_FORCE_GTD",
                }
            }
            /// Creates an enum from field names used in the ProtoBuf definition.
            pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
                match value {
                    "TIME_IN_FORCE_UNSPECIFIED" => Some(Self::Unspecified),
                    "TIME_IN_FORCE_GTC" => Some(Self::Gtc),
                    "TIME_IN_FORCE_IOC" => Some(Self::Ioc),
                    "TIME_IN_FORCE_FOK" => Some(Self::Fok),
                    "TIME_IN_FORCE_GTD" => Some(Self::Gtd),
                    _ => None,
                }
            }
        }
    }
    /// Exit strategy
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct ExitStrategy {
        #[prost(float, tag = "1")]
        pub take_profit_price: f32,
        #[prost(float, tag = "2")]
        pub stop_loss_price: f32,
        #[prost(float, tag = "3")]
        pub trailing_stop_percentage: f32,
        #[prost(message, optional, tag = "4")]
        pub time_exit: ::core::option::Option<::prost_types::Timestamp>,
    }
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Side {
        Unspecified = 0,
        Buy = 1,
        Sell = 2,
    }
    impl Side {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Side::Unspecified => "SIDE_UNSPECIFIED",
                Side::Buy => "SIDE_BUY",
                Side::Sell => "SIDE_SELL",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "SIDE_UNSPECIFIED" => Some(Self::Unspecified),
                "SIDE_BUY" => Some(Self::Buy),
                "SIDE_SELL" => Some(Self::Sell),
                _ => None,
            }
        }
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RiskAssessment {
    #[prost(float, tag = "1")]
    pub confidence_score: f32,
    #[prost(float, tag = "2")]
    pub risk_score: f32,
    #[prost(message, optional, tag = "3")]
    pub metrics: ::core::option::Option<risk_assessment::RiskMetrics>,
    /// Risk factors
    #[prost(message, repeated, tag = "4")]
    pub factors: ::prost::alloc::vec::Vec<RiskFactor>,
    /// Risk limits check
    #[prost(message, optional, tag = "5")]
    pub limits_check: ::core::option::Option<RiskLimitsValidation>,
}
/// Nested message and enum types in `RiskAssessment`.
pub mod risk_assessment {
    /// Risk metrics
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct RiskMetrics {
        #[prost(float, tag = "1")]
        pub value_at_risk: f32,
        #[prost(float, tag = "2")]
        pub expected_shortfall: f32,
        #[prost(float, tag = "3")]
        pub sharpe_ratio: f32,
        #[prost(float, tag = "4")]
        pub max_drawdown: f32,
        #[prost(float, tag = "5")]
        pub position_size_risk: f32,
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RiskFactor {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(float, tag = "2")]
    pub value: f32,
    #[prost(float, tag = "3")]
    pub contribution: f32,
    /// market, liquidity, execution, model
    #[prost(string, tag = "4")]
    pub category: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RiskLimitsValidation {
    #[prost(bool, tag = "1")]
    pub passed: bool,
    #[prost(message, repeated, tag = "2")]
    pub checks: ::prost::alloc::vec::Vec<LimitCheck>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LimitCheck {
    #[prost(string, tag = "1")]
    pub limit_type: ::prost::alloc::string::String,
    #[prost(float, tag = "2")]
    pub limit_value: f32,
    #[prost(float, tag = "3")]
    pub current_value: f32,
    #[prost(bool, tag = "4")]
    pub passed: bool,
    #[prost(string, tag = "5")]
    pub message: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecutionConstraints {
    #[prost(message, optional, tag = "1")]
    pub timing: ::core::option::Option<execution_constraints::TimingConstraints>,
    #[prost(message, optional, tag = "2")]
    pub liquidity: ::core::option::Option<execution_constraints::LiquidityConstraints>,
    #[prost(message, optional, tag = "3")]
    pub cost: ::core::option::Option<execution_constraints::CostConstraints>,
    #[prost(message, optional, tag = "4")]
    pub regulatory: ::core::option::Option<execution_constraints::RegulatoryConstraints>,
}
/// Nested message and enum types in `ExecutionConstraints`.
pub mod execution_constraints {
    /// Timing constraints
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct TimingConstraints {
        #[prost(message, optional, tag = "1")]
        pub not_before: ::core::option::Option<::prost_types::Timestamp>,
        #[prost(message, optional, tag = "2")]
        pub not_after: ::core::option::Option<::prost_types::Timestamp>,
        /// "pre-market", "regular", "after-hours"
        #[prost(string, repeated, tag = "3")]
        pub trading_sessions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
        /// "market-open", "market-close"
        #[prost(string, repeated, tag = "4")]
        pub avoid_times: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    }
    /// Liquidity constraints
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct LiquidityConstraints {
        #[prost(float, tag = "1")]
        pub min_volume: f32,
        #[prost(float, tag = "2")]
        pub max_spread: f32,
        #[prost(float, tag = "3")]
        pub max_market_impact: f32,
        /// Max % of volume
        #[prost(float, tag = "4")]
        pub participation_rate: f32,
    }
    /// Cost constraints
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct CostConstraints {
        #[prost(float, tag = "1")]
        pub max_commission: f32,
        #[prost(float, tag = "2")]
        pub max_slippage: f32,
        #[prost(float, tag = "3")]
        pub max_total_cost: f32,
    }
    /// Regulatory constraints
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct RegulatoryConstraints {
        #[prost(bool, tag = "1")]
        pub pattern_day_trader_check: bool,
        #[prost(bool, tag = "2")]
        pub wash_sale_check: bool,
        #[prost(bool, tag = "3")]
        pub short_sale_restrictions: bool,
        #[prost(string, repeated, tag = "4")]
        pub compliance_rules: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DecisionMetadata {
    #[prost(message, optional, tag = "1")]
    pub insights: ::core::option::Option<decision_metadata::ModelInsights>,
    #[prost(message, optional, tag = "2")]
    pub market: ::core::option::Option<decision_metadata::MarketContext>,
    #[prost(message, optional, tag = "3")]
    pub portfolio: ::core::option::Option<decision_metadata::PortfolioContext>,
    #[prost(map = "string, string", tag = "4")]
    pub tags: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
/// Nested message and enum types in `DecisionMetadata`.
pub mod decision_metadata {
    /// Model insights
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct ModelInsights {
        #[prost(message, repeated, tag = "1")]
        pub signals: ::prost::alloc::vec::Vec<super::Signal>,
        #[prost(map = "string, float", tag = "2")]
        pub feature_importance: ::std::collections::HashMap<
            ::prost::alloc::string::String,
            f32,
        >,
        #[prost(string, tag = "3")]
        pub reasoning: ::prost::alloc::string::String,
    }
    /// Market context
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct MarketContext {
        #[prost(float, tag = "1")]
        pub current_price: f32,
        #[prost(float, tag = "2")]
        pub bid: f32,
        #[prost(float, tag = "3")]
        pub ask: f32,
        #[prost(float, tag = "4")]
        pub volume: f32,
        #[prost(float, tag = "5")]
        pub volatility: f32,
        #[prost(string, tag = "6")]
        pub trend: ::prost::alloc::string::String,
        #[prost(string, tag = "7")]
        pub market_regime: ::prost::alloc::string::String,
    }
    /// Portfolio context
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct PortfolioContext {
        #[prost(float, tag = "1")]
        pub current_position: f32,
        #[prost(float, tag = "2")]
        pub average_entry_price: f32,
        #[prost(float, tag = "3")]
        pub unrealized_pnl: f32,
        #[prost(float, tag = "4")]
        pub portfolio_allocation: f32,
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Signal {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(float, tag = "2")]
    pub value: f32,
    #[prost(float, tag = "3")]
    pub strength: f32,
    /// bullish, bearish, neutral
    #[prost(string, tag = "4")]
    pub direction: ::prost::alloc::string::String,
}
/// Execution request to broker/exchange
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecutionRequest {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub decision_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub decision: ::core::option::Option<TradingDecision>,
    #[prost(message, optional, tag = "4")]
    pub options: ::core::option::Option<ExecutionOptions>,
    #[prost(message, optional, tag = "5")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecutionOptions {
    #[prost(enumeration = "execution_options::ExecutionMode", tag = "1")]
    pub mode: i32,
    #[prost(message, optional, tag = "2")]
    pub algorithm: ::core::option::Option<execution_options::Algorithm>,
    #[prost(message, optional, tag = "3")]
    pub routing: ::core::option::Option<execution_options::SmartRouting>,
    #[prost(bool, tag = "4")]
    pub dry_run: bool,
    #[prost(bool, tag = "5")]
    pub require_confirmation: bool,
}
/// Nested message and enum types in `ExecutionOptions`.
pub mod execution_options {
    /// Execution algorithms
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Algorithm {
        /// TWAP, VWAP, POV, etc.
        #[prost(string, tag = "1")]
        pub name: ::prost::alloc::string::String,
        #[prost(map = "string, message", tag = "2")]
        pub params: ::std::collections::HashMap<
            ::prost::alloc::string::String,
            ::prost_types::Value,
        >,
    }
    /// Smart order routing
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct SmartRouting {
        #[prost(bool, tag = "1")]
        pub enabled: bool,
        #[prost(string, repeated, tag = "2")]
        pub venues: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
        #[prost(string, tag = "3")]
        pub routing_strategy: ::prost::alloc::string::String,
    }
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum ExecutionMode {
        Unspecified = 0,
        Immediate = 1,
        Scheduled = 2,
        Algorithmic = 3,
        ManualApproval = 4,
    }
    impl ExecutionMode {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                ExecutionMode::Unspecified => "EXECUTION_MODE_UNSPECIFIED",
                ExecutionMode::Immediate => "EXECUTION_MODE_IMMEDIATE",
                ExecutionMode::Scheduled => "EXECUTION_MODE_SCHEDULED",
                ExecutionMode::Algorithmic => "EXECUTION_MODE_ALGORITHMIC",
                ExecutionMode::ManualApproval => "EXECUTION_MODE_MANUAL_APPROVAL",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "EXECUTION_MODE_UNSPECIFIED" => Some(Self::Unspecified),
                "EXECUTION_MODE_IMMEDIATE" => Some(Self::Immediate),
                "EXECUTION_MODE_SCHEDULED" => Some(Self::Scheduled),
                "EXECUTION_MODE_ALGORITHMIC" => Some(Self::Algorithmic),
                "EXECUTION_MODE_MANUAL_APPROVAL" => Some(Self::ManualApproval),
                _ => None,
            }
        }
    }
}
/// Execution response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecutionResponse {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub execution_id: ::prost::alloc::string::String,
    #[prost(enumeration = "ExecutionStatus", tag = "3")]
    pub status: i32,
    #[prost(message, optional, tag = "4")]
    pub result: ::core::option::Option<ExecutionResult>,
    #[prost(message, optional, tag = "5")]
    pub executed_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecutionResult {
    #[prost(string, tag = "1")]
    pub order_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub exchange_order_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub fills: ::prost::alloc::vec::Vec<Fill>,
    #[prost(message, optional, tag = "4")]
    pub summary: ::core::option::Option<execution_result::Summary>,
    #[prost(string, tag = "5")]
    pub rejection_reason: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub error_message: ::prost::alloc::string::String,
}
/// Nested message and enum types in `ExecutionResult`.
pub mod execution_result {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Summary {
        #[prost(float, tag = "1")]
        pub total_quantity: f32,
        #[prost(float, tag = "2")]
        pub average_price: f32,
        #[prost(float, tag = "3")]
        pub total_commission: f32,
        #[prost(float, tag = "4")]
        pub realized_slippage: f32,
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Fill {
    #[prost(string, tag = "1")]
    pub fill_id: ::prost::alloc::string::String,
    #[prost(float, tag = "2")]
    pub quantity: f32,
    #[prost(float, tag = "3")]
    pub price: f32,
    #[prost(float, tag = "4")]
    pub commission: f32,
    #[prost(message, optional, tag = "5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag = "6")]
    pub venue: ::prost::alloc::string::String,
}
/// Feedback from execution
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecutionFeedback {
    #[prost(string, tag = "1")]
    pub execution_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub decision_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub performance: ::core::option::Option<PerformanceMetrics>,
    #[prost(message, optional, tag = "4")]
    pub impact: ::core::option::Option<MarketImpact>,
    #[prost(message, repeated, tag = "5")]
    pub issues: ::prost::alloc::vec::Vec<Issue>,
    #[prost(message, optional, tag = "6")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PerformanceMetrics {
    #[prost(float, tag = "1")]
    pub realized_pnl: f32,
    #[prost(float, tag = "2")]
    pub unrealized_pnl: f32,
    #[prost(float, tag = "3")]
    pub slippage: f32,
    #[prost(float, tag = "4")]
    pub execution_cost: f32,
    #[prost(message, optional, tag = "5")]
    pub timing: ::core::option::Option<performance_metrics::Timing>,
}
/// Nested message and enum types in `PerformanceMetrics`.
pub mod performance_metrics {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Timing {
        #[prost(int64, tag = "1")]
        pub decision_to_submission_ms: i64,
        #[prost(int64, tag = "2")]
        pub submission_to_fill_ms: i64,
        #[prost(int64, tag = "3")]
        pub total_latency_ms: i64,
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MarketImpact {
    #[prost(float, tag = "1")]
    pub price_impact: f32,
    #[prost(float, tag = "2")]
    pub volume_participation: f32,
    #[prost(float, tag = "3")]
    pub spread_cost: f32,
    #[prost(float, tag = "4")]
    pub market_move: f32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Issue {
    #[prost(enumeration = "issue::Severity", tag = "1")]
    pub severity: i32,
    #[prost(string, tag = "2")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub occurred_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// Nested message and enum types in `Issue`.
pub mod issue {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Severity {
        Unspecified = 0,
        Info = 1,
        Warning = 2,
        Error = 3,
        Critical = 4,
    }
    impl Severity {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Severity::Unspecified => "SEVERITY_UNSPECIFIED",
                Severity::Info => "SEVERITY_INFO",
                Severity::Warning => "SEVERITY_WARNING",
                Severity::Error => "SEVERITY_ERROR",
                Severity::Critical => "SEVERITY_CRITICAL",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "SEVERITY_UNSPECIFIED" => Some(Self::Unspecified),
                "SEVERITY_INFO" => Some(Self::Info),
                "SEVERITY_WARNING" => Some(Self::Warning),
                "SEVERITY_ERROR" => Some(Self::Error),
                "SEVERITY_CRITICAL" => Some(Self::Critical),
                _ => None,
            }
        }
    }
}
/// Emergency control
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EmergencyControl {
    #[prost(string, tag = "1")]
    pub control_id: ::prost::alloc::string::String,
    #[prost(enumeration = "emergency_control::Action", tag = "2")]
    pub action: i32,
    #[prost(string, tag = "3")]
    pub reason: ::prost::alloc::string::String,
    #[prost(enumeration = "emergency_control::Trigger", tag = "4")]
    pub trigger: i32,
    #[prost(map = "string, string", tag = "5")]
    pub parameters: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(message, optional, tag = "6")]
    pub triggered_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// Nested message and enum types in `EmergencyControl`.
pub mod emergency_control {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Action {
        Unspecified = 0,
        HaltTrading = 1,
        CloseAllPositions = 2,
        CancelAllOrders = 3,
        ReduceExposure = 4,
        SwitchToHedgeMode = 5,
    }
    impl Action {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Action::Unspecified => "ACTION_UNSPECIFIED",
                Action::HaltTrading => "ACTION_HALT_TRADING",
                Action::CloseAllPositions => "ACTION_CLOSE_ALL_POSITIONS",
                Action::CancelAllOrders => "ACTION_CANCEL_ALL_ORDERS",
                Action::ReduceExposure => "ACTION_REDUCE_EXPOSURE",
                Action::SwitchToHedgeMode => "ACTION_SWITCH_TO_HEDGE_MODE",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "ACTION_UNSPECIFIED" => Some(Self::Unspecified),
                "ACTION_HALT_TRADING" => Some(Self::HaltTrading),
                "ACTION_CLOSE_ALL_POSITIONS" => Some(Self::CloseAllPositions),
                "ACTION_CANCEL_ALL_ORDERS" => Some(Self::CancelAllOrders),
                "ACTION_REDUCE_EXPOSURE" => Some(Self::ReduceExposure),
                "ACTION_SWITCH_TO_HEDGE_MODE" => Some(Self::SwitchToHedgeMode),
                _ => None,
            }
        }
    }
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Trigger {
        Unspecified = 0,
        Manual = 1,
        RiskBreach = 2,
        SystemError = 3,
        MarketCondition = 4,
        Regulatory = 5,
    }
    impl Trigger {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Trigger::Unspecified => "TRIGGER_UNSPECIFIED",
                Trigger::Manual => "TRIGGER_MANUAL",
                Trigger::RiskBreach => "TRIGGER_RISK_BREACH",
                Trigger::SystemError => "TRIGGER_SYSTEM_ERROR",
                Trigger::MarketCondition => "TRIGGER_MARKET_CONDITION",
                Trigger::Regulatory => "TRIGGER_REGULATORY",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "TRIGGER_UNSPECIFIED" => Some(Self::Unspecified),
                "TRIGGER_MANUAL" => Some(Self::Manual),
                "TRIGGER_RISK_BREACH" => Some(Self::RiskBreach),
                "TRIGGER_SYSTEM_ERROR" => Some(Self::SystemError),
                "TRIGGER_MARKET_CONDITION" => Some(Self::MarketCondition),
                "TRIGGER_REGULATORY" => Some(Self::Regulatory),
                _ => None,
            }
        }
    }
}
/// Risk validation
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RiskValidationRequest {
    #[prost(message, optional, tag = "1")]
    pub decision: ::core::option::Option<TradingDecision>,
    #[prost(message, repeated, tag = "2")]
    pub rules: ::prost::alloc::vec::Vec<RiskRule>,
    #[prost(message, optional, tag = "3")]
    pub portfolio: ::core::option::Option<PortfolioState>,
    #[prost(message, optional, tag = "4")]
    pub market: ::core::option::Option<MarketState>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RiskRule {
    #[prost(string, tag = "1")]
    pub rule_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Risk rule expression
    #[prost(string, tag = "3")]
    pub expression: ::prost::alloc::string::String,
    #[prost(enumeration = "risk_rule::Action", tag = "4")]
    pub action: i32,
    #[prost(map = "string, float", tag = "5")]
    pub parameters: ::std::collections::HashMap<::prost::alloc::string::String, f32>,
}
/// Nested message and enum types in `RiskRule`.
pub mod risk_rule {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Action {
        Unspecified = 0,
        Block = 1,
        Warn = 2,
        Adjust = 3,
    }
    impl Action {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Action::Unspecified => "ACTION_UNSPECIFIED",
                Action::Block => "ACTION_BLOCK",
                Action::Warn => "ACTION_WARN",
                Action::Adjust => "ACTION_ADJUST",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "ACTION_UNSPECIFIED" => Some(Self::Unspecified),
                "ACTION_BLOCK" => Some(Self::Block),
                "ACTION_WARN" => Some(Self::Warn),
                "ACTION_ADJUST" => Some(Self::Adjust),
                _ => None,
            }
        }
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PortfolioState {
    #[prost(map = "string, message", tag = "1")]
    pub positions: ::std::collections::HashMap<::prost::alloc::string::String, Position>,
    #[prost(float, tag = "2")]
    pub cash_balance: f32,
    #[prost(float, tag = "3")]
    pub total_value: f32,
    #[prost(float, tag = "4")]
    pub buying_power: f32,
    #[prost(float, tag = "5")]
    pub margin_used: f32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Position {
    #[prost(string, tag = "1")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(float, tag = "2")]
    pub quantity: f32,
    #[prost(float, tag = "3")]
    pub average_price: f32,
    #[prost(float, tag = "4")]
    pub current_price: f32,
    #[prost(float, tag = "5")]
    pub unrealized_pnl: f32,
    #[prost(float, tag = "6")]
    pub realized_pnl: f32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MarketState {
    /// open, closed, halted
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    #[prost(float, tag = "2")]
    pub volatility_index: f32,
    /// trending, ranging, volatile
    #[prost(string, tag = "3")]
    pub regime: ::prost::alloc::string::String,
    #[prost(map = "string, float", tag = "4")]
    pub indicators: ::std::collections::HashMap<::prost::alloc::string::String, f32>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RiskValidationResponse {
    #[prost(bool, tag = "1")]
    pub approved: bool,
    #[prost(message, repeated, tag = "2")]
    pub results: ::prost::alloc::vec::Vec<ValidationResult>,
    #[prost(message, optional, tag = "3")]
    pub adjusted_decision: ::core::option::Option<TradingDecision>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidationResult {
    #[prost(string, tag = "1")]
    pub rule_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub passed: bool,
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
    #[prost(map = "string, float", tag = "4")]
    pub metrics: ::std::collections::HashMap<::prost::alloc::string::String, f32>,
}
/// Additional service messages
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EmergencyControlResponse {
    #[prost(string, tag = "1")]
    pub control_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub success: bool,
    #[prost(string, repeated, tag = "3")]
    pub affected_orders: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "4")]
    pub affected_positions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "5")]
    pub message: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecutionQuery {
    #[prost(string, tag = "1")]
    pub execution_id: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelRequest {
    #[prost(string, tag = "1")]
    pub execution_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FeedbackResponse {
    #[prost(bool, tag = "1")]
    pub received: bool,
    #[prost(string, tag = "2")]
    pub feedback_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DecisionType {
    Unspecified = 0,
    MarketOrder = 1,
    LimitOrder = 2,
    StopOrder = 3,
    ClosePosition = 4,
    AdjustPosition = 5,
    Hedge = 6,
    NoAction = 7,
}
impl DecisionType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            DecisionType::Unspecified => "DECISION_TYPE_UNSPECIFIED",
            DecisionType::MarketOrder => "DECISION_TYPE_MARKET_ORDER",
            DecisionType::LimitOrder => "DECISION_TYPE_LIMIT_ORDER",
            DecisionType::StopOrder => "DECISION_TYPE_STOP_ORDER",
            DecisionType::ClosePosition => "DECISION_TYPE_CLOSE_POSITION",
            DecisionType::AdjustPosition => "DECISION_TYPE_ADJUST_POSITION",
            DecisionType::Hedge => "DECISION_TYPE_HEDGE",
            DecisionType::NoAction => "DECISION_TYPE_NO_ACTION",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DECISION_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "DECISION_TYPE_MARKET_ORDER" => Some(Self::MarketOrder),
            "DECISION_TYPE_LIMIT_ORDER" => Some(Self::LimitOrder),
            "DECISION_TYPE_STOP_ORDER" => Some(Self::StopOrder),
            "DECISION_TYPE_CLOSE_POSITION" => Some(Self::ClosePosition),
            "DECISION_TYPE_ADJUST_POSITION" => Some(Self::AdjustPosition),
            "DECISION_TYPE_HEDGE" => Some(Self::Hedge),
            "DECISION_TYPE_NO_ACTION" => Some(Self::NoAction),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ExecutionStatus {
    Unspecified = 0,
    Pending = 1,
    Submitted = 2,
    Partial = 3,
    Filled = 4,
    Cancelled = 5,
    Rejected = 6,
    Failed = 7,
}
impl ExecutionStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            ExecutionStatus::Unspecified => "EXECUTION_STATUS_UNSPECIFIED",
            ExecutionStatus::Pending => "EXECUTION_STATUS_PENDING",
            ExecutionStatus::Submitted => "EXECUTION_STATUS_SUBMITTED",
            ExecutionStatus::Partial => "EXECUTION_STATUS_PARTIAL",
            ExecutionStatus::Filled => "EXECUTION_STATUS_FILLED",
            ExecutionStatus::Cancelled => "EXECUTION_STATUS_CANCELLED",
            ExecutionStatus::Rejected => "EXECUTION_STATUS_REJECTED",
            ExecutionStatus::Failed => "EXECUTION_STATUS_FAILED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EXECUTION_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "EXECUTION_STATUS_PENDING" => Some(Self::Pending),
            "EXECUTION_STATUS_SUBMITTED" => Some(Self::Submitted),
            "EXECUTION_STATUS_PARTIAL" => Some(Self::Partial),
            "EXECUTION_STATUS_FILLED" => Some(Self::Filled),
            "EXECUTION_STATUS_CANCELLED" => Some(Self::Cancelled),
            "EXECUTION_STATUS_REJECTED" => Some(Self::Rejected),
            "EXECUTION_STATUS_FAILED" => Some(Self::Failed),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod action_execution_service_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Services
    #[derive(Debug, Clone)]
    pub struct ActionExecutionServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ActionExecutionServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ActionExecutionServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ActionExecutionServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + Send + Sync,
        {
            ActionExecutionServiceClient::new(
                InterceptedService::new(inner, interceptor),
            )
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Submit trading decision for execution
        pub async fn execute_decision(
            &mut self,
            request: impl tonic::IntoRequest<super::ExecutionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ExecutionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/neural_trader.interfaces.action.ActionExecutionService/ExecuteDecision",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "neural_trader.interfaces.action.ActionExecutionService",
                        "ExecuteDecision",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Stream execution updates
        pub async fn stream_execution_updates(
            &mut self,
            request: impl tonic::IntoRequest<super::ExecutionRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ExecutionResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/neural_trader.interfaces.action.ActionExecutionService/StreamExecutionUpdates",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "neural_trader.interfaces.action.ActionExecutionService",
                        "StreamExecutionUpdates",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Validate decision against risk rules
        pub async fn validate_risk(
            &mut self,
            request: impl tonic::IntoRequest<super::RiskValidationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RiskValidationResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/neural_trader.interfaces.action.ActionExecutionService/ValidateRisk",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "neural_trader.interfaces.action.ActionExecutionService",
                        "ValidateRisk",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Emergency controls
        pub async fn trigger_emergency_control(
            &mut self,
            request: impl tonic::IntoRequest<super::EmergencyControl>,
        ) -> std::result::Result<
            tonic::Response<super::EmergencyControlResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/neural_trader.interfaces.action.ActionExecutionService/TriggerEmergencyControl",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "neural_trader.interfaces.action.ActionExecutionService",
                        "TriggerEmergencyControl",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get execution status
        pub async fn get_execution_status(
            &mut self,
            request: impl tonic::IntoRequest<super::ExecutionQuery>,
        ) -> std::result::Result<
            tonic::Response<super::ExecutionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/neural_trader.interfaces.action.ActionExecutionService/GetExecutionStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "neural_trader.interfaces.action.ActionExecutionService",
                        "GetExecutionStatus",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Cancel execution
        pub async fn cancel_execution(
            &mut self,
            request: impl tonic::IntoRequest<super::CancelRequest>,
        ) -> std::result::Result<tonic::Response<super::CancelResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/neural_trader.interfaces.action.ActionExecutionService/CancelExecution",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "neural_trader.interfaces.action.ActionExecutionService",
                        "CancelExecution",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Provide execution feedback
        pub async fn submit_feedback(
            &mut self,
            request: impl tonic::IntoRequest<super::ExecutionFeedback>,
        ) -> std::result::Result<
            tonic::Response<super::FeedbackResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/neural_trader.interfaces.action.ActionExecutionService/SubmitFeedback",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "neural_trader.interfaces.action.ActionExecutionService",
                        "SubmitFeedback",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod action_execution_service_server {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with ActionExecutionServiceServer.
    #[async_trait]
    pub trait ActionExecutionService: Send + Sync + 'static {
        /// Submit trading decision for execution
        async fn execute_decision(
            &self,
            request: tonic::Request<super::ExecutionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ExecutionResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the StreamExecutionUpdates method.
        type StreamExecutionUpdatesStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::ExecutionResponse, tonic::Status>,
            >
            + Send
            + 'static;
        /// Stream execution updates
        async fn stream_execution_updates(
            &self,
            request: tonic::Request<super::ExecutionRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::StreamExecutionUpdatesStream>,
            tonic::Status,
        >;
        /// Validate decision against risk rules
        async fn validate_risk(
            &self,
            request: tonic::Request<super::RiskValidationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RiskValidationResponse>,
            tonic::Status,
        >;
        /// Emergency controls
        async fn trigger_emergency_control(
            &self,
            request: tonic::Request<super::EmergencyControl>,
        ) -> std::result::Result<
            tonic::Response<super::EmergencyControlResponse>,
            tonic::Status,
        >;
        /// Get execution status
        async fn get_execution_status(
            &self,
            request: tonic::Request<super::ExecutionQuery>,
        ) -> std::result::Result<
            tonic::Response<super::ExecutionResponse>,
            tonic::Status,
        >;
        /// Cancel execution
        async fn cancel_execution(
            &self,
            request: tonic::Request<super::CancelRequest>,
        ) -> std::result::Result<tonic::Response<super::CancelResponse>, tonic::Status>;
        /// Provide execution feedback
        async fn submit_feedback(
            &self,
            request: tonic::Request<super::ExecutionFeedback>,
        ) -> std::result::Result<
            tonic::Response<super::FeedbackResponse>,
            tonic::Status,
        >;
    }
    /// Services
    #[derive(Debug)]
    pub struct ActionExecutionServiceServer<T: ActionExecutionService> {
        inner: _Inner<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    struct _Inner<T>(Arc<T>);
    impl<T: ActionExecutionService> ActionExecutionServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            let inner = _Inner(inner);
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>>
    for ActionExecutionServiceServer<T>
    where
        T: ActionExecutionService,
        B: Body + Send + 'static,
        B::Error: Into<StdError> + Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            let inner = self.inner.clone();
            match req.uri().path() {
                "/neural_trader.interfaces.action.ActionExecutionService/ExecuteDecision" => {
                    #[allow(non_camel_case_types)]
                    struct ExecuteDecisionSvc<T: ActionExecutionService>(pub Arc<T>);
                    impl<
                        T: ActionExecutionService,
                    > tonic::server::UnaryService<super::ExecutionRequest>
                    for ExecuteDecisionSvc<T> {
                        type Response = super::ExecutionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ExecutionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ActionExecutionService>::execute_decision(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = ExecuteDecisionSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/neural_trader.interfaces.action.ActionExecutionService/StreamExecutionUpdates" => {
                    #[allow(non_camel_case_types)]
                    struct StreamExecutionUpdatesSvc<T: ActionExecutionService>(
                        pub Arc<T>,
                    );
                    impl<
                        T: ActionExecutionService,
                    > tonic::server::ServerStreamingService<super::ExecutionRequest>
                    for StreamExecutionUpdatesSvc<T> {
                        type Response = super::ExecutionResponse;
                        type ResponseStream = T::StreamExecutionUpdatesStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ExecutionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ActionExecutionService>::stream_execution_updates(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = StreamExecutionUpdatesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/neural_trader.interfaces.action.ActionExecutionService/ValidateRisk" => {
                    #[allow(non_camel_case_types)]
                    struct ValidateRiskSvc<T: ActionExecutionService>(pub Arc<T>);
                    impl<
                        T: ActionExecutionService,
                    > tonic::server::UnaryService<super::RiskValidationRequest>
                    for ValidateRiskSvc<T> {
                        type Response = super::RiskValidationResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RiskValidationRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ActionExecutionService>::validate_risk(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = ValidateRiskSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/neural_trader.interfaces.action.ActionExecutionService/TriggerEmergencyControl" => {
                    #[allow(non_camel_case_types)]
                    struct TriggerEmergencyControlSvc<T: ActionExecutionService>(
                        pub Arc<T>,
                    );
                    impl<
                        T: ActionExecutionService,
                    > tonic::server::UnaryService<super::EmergencyControl>
                    for TriggerEmergencyControlSvc<T> {
                        type Response = super::EmergencyControlResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::EmergencyControl>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ActionExecutionService>::trigger_emergency_control(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = TriggerEmergencyControlSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/neural_trader.interfaces.action.ActionExecutionService/GetExecutionStatus" => {
                    #[allow(non_camel_case_types)]
                    struct GetExecutionStatusSvc<T: ActionExecutionService>(pub Arc<T>);
                    impl<
                        T: ActionExecutionService,
                    > tonic::server::UnaryService<super::ExecutionQuery>
                    for GetExecutionStatusSvc<T> {
                        type Response = super::ExecutionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ExecutionQuery>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ActionExecutionService>::get_execution_status(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetExecutionStatusSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/neural_trader.interfaces.action.ActionExecutionService/CancelExecution" => {
                    #[allow(non_camel_case_types)]
                    struct CancelExecutionSvc<T: ActionExecutionService>(pub Arc<T>);
                    impl<
                        T: ActionExecutionService,
                    > tonic::server::UnaryService<super::CancelRequest>
                    for CancelExecutionSvc<T> {
                        type Response = super::CancelResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CancelRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ActionExecutionService>::cancel_execution(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = CancelExecutionSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/neural_trader.interfaces.action.ActionExecutionService/SubmitFeedback" => {
                    #[allow(non_camel_case_types)]
                    struct SubmitFeedbackSvc<T: ActionExecutionService>(pub Arc<T>);
                    impl<
                        T: ActionExecutionService,
                    > tonic::server::UnaryService<super::ExecutionFeedback>
                    for SubmitFeedbackSvc<T> {
                        type Response = super::FeedbackResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ExecutionFeedback>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ActionExecutionService>::submit_feedback(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = SubmitFeedbackSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        Ok(
                            http::Response::builder()
                                .status(200)
                                .header("grpc-status", "12")
                                .header("content-type", "application/grpc")
                                .body(empty_body())
                                .unwrap(),
                        )
                    })
                }
            }
        }
    }
    impl<T: ActionExecutionService> Clone for ActionExecutionServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    impl<T: ActionExecutionService> Clone for _Inner<T> {
        fn clone(&self) -> Self {
            Self(Arc::clone(&self.0))
        }
    }
    impl<T: std::fmt::Debug> std::fmt::Debug for _Inner<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{:?}", self.0)
        }
    }
    impl<T: ActionExecutionService> tonic::server::NamedService
    for ActionExecutionServiceServer<T> {
        const NAME: &'static str = "neural_trader.interfaces.action.ActionExecutionService";
    }
}
