// This file is @generated by prost-build.
/// Feature extraction request from event stream
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FeatureExtractionRequest {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub pipeline_id: ::prost::alloc::string::String,
    /// Source data reference
    #[prost(message, optional, tag = "3")]
    pub source: ::core::option::Option<DataSource>,
    /// Feature extraction configuration
    #[prost(message, optional, tag = "4")]
    pub config: ::core::option::Option<FeatureConfig>,
    /// Time window for features
    #[prost(message, optional, tag = "5")]
    pub window: ::core::option::Option<TimeWindow>,
    /// Quality requirements
    #[prost(message, optional, tag = "6")]
    pub quality: ::core::option::Option<QualityRequirements>,
    /// Processing options
    #[prost(message, optional, tag = "7")]
    pub options: ::core::option::Option<ProcessingOptions>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DataSource {
    #[prost(enumeration = "data_source::SourceType", tag = "1")]
    pub r#type: i32,
    #[prost(string, tag = "2")]
    pub topic: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub query: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "4")]
    pub partitions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(map = "string, string", tag = "5")]
    pub filters: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
/// Nested message and enum types in `DataSource`.
pub mod data_source {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum SourceType {
        Unspecified = 0,
        Stream = 1,
        Batch = 2,
        Hybrid = 3,
    }
    impl SourceType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                SourceType::Unspecified => "SOURCE_TYPE_UNSPECIFIED",
                SourceType::Stream => "SOURCE_TYPE_STREAM",
                SourceType::Batch => "SOURCE_TYPE_BATCH",
                SourceType::Hybrid => "SOURCE_TYPE_HYBRID",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "SOURCE_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
                "SOURCE_TYPE_STREAM" => Some(Self::Stream),
                "SOURCE_TYPE_BATCH" => Some(Self::Batch),
                "SOURCE_TYPE_HYBRID" => Some(Self::Hybrid),
                _ => None,
            }
        }
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FeatureConfig {
    #[prost(string, tag = "1")]
    pub feature_set_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub features: ::prost::alloc::vec::Vec<FeatureDefinition>,
    #[prost(message, repeated, tag = "4")]
    pub aggregations: ::prost::alloc::vec::Vec<Aggregation>,
    #[prost(message, repeated, tag = "5")]
    pub transformations: ::prost::alloc::vec::Vec<Transformation>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FeatureDefinition {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub expression: ::prost::alloc::string::String,
    #[prost(enumeration = "feature_definition::DataType", tag = "3")]
    pub r#type: i32,
    #[prost(message, optional, tag = "4")]
    pub expected_stats: ::core::option::Option<feature_definition::Statistics>,
    /// Validation rules
    #[prost(message, repeated, tag = "5")]
    pub validation: ::prost::alloc::vec::Vec<ValidationRule>,
}
/// Nested message and enum types in `FeatureDefinition`.
pub mod feature_definition {
    /// Statistical properties
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Statistics {
        #[prost(float, tag = "1")]
        pub min: f32,
        #[prost(float, tag = "2")]
        pub max: f32,
        #[prost(float, tag = "3")]
        pub mean: f32,
        #[prost(float, tag = "4")]
        pub std_dev: f32,
        #[prost(float, repeated, tag = "5")]
        pub percentiles: ::prost::alloc::vec::Vec<f32>,
    }
    #[allow(clippy::enum_variant_names)]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum DataType {
        Unspecified = 0,
        Float = 1,
        Int = 2,
        String = 3,
        Bool = 4,
        Vector = 5,
        Tensor = 6,
    }
    impl DataType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                DataType::Unspecified => "DATA_TYPE_UNSPECIFIED",
                DataType::Float => "DATA_TYPE_FLOAT",
                DataType::Int => "DATA_TYPE_INT",
                DataType::String => "DATA_TYPE_STRING",
                DataType::Bool => "DATA_TYPE_BOOL",
                DataType::Vector => "DATA_TYPE_VECTOR",
                DataType::Tensor => "DATA_TYPE_TENSOR",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "DATA_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
                "DATA_TYPE_FLOAT" => Some(Self::Float),
                "DATA_TYPE_INT" => Some(Self::Int),
                "DATA_TYPE_STRING" => Some(Self::String),
                "DATA_TYPE_BOOL" => Some(Self::Bool),
                "DATA_TYPE_VECTOR" => Some(Self::Vector),
                "DATA_TYPE_TENSOR" => Some(Self::Tensor),
                _ => None,
            }
        }
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidationRule {
    #[prost(enumeration = "validation_rule::RuleType", tag = "1")]
    pub r#type: i32,
    #[prost(string, tag = "2")]
    pub expression: ::prost::alloc::string::String,
    #[prost(enumeration = "Severity", tag = "3")]
    pub severity: i32,
    #[prost(string, tag = "4")]
    pub error_message: ::prost::alloc::string::String,
}
/// Nested message and enum types in `ValidationRule`.
pub mod validation_rule {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum RuleType {
        Unspecified = 0,
        Range = 1,
        Regex = 2,
        Enum = 3,
        NullCheck = 4,
        Uniqueness = 5,
        Distribution = 6,
    }
    impl RuleType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                RuleType::Unspecified => "RULE_TYPE_UNSPECIFIED",
                RuleType::Range => "RULE_TYPE_RANGE",
                RuleType::Regex => "RULE_TYPE_REGEX",
                RuleType::Enum => "RULE_TYPE_ENUM",
                RuleType::NullCheck => "RULE_TYPE_NULL_CHECK",
                RuleType::Uniqueness => "RULE_TYPE_UNIQUENESS",
                RuleType::Distribution => "RULE_TYPE_DISTRIBUTION",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "RULE_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
                "RULE_TYPE_RANGE" => Some(Self::Range),
                "RULE_TYPE_REGEX" => Some(Self::Regex),
                "RULE_TYPE_ENUM" => Some(Self::Enum),
                "RULE_TYPE_NULL_CHECK" => Some(Self::NullCheck),
                "RULE_TYPE_UNIQUENESS" => Some(Self::Uniqueness),
                "RULE_TYPE_DISTRIBUTION" => Some(Self::Distribution),
                _ => None,
            }
        }
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Aggregation {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// sum, mean, max, min, std, percentile
    #[prost(string, tag = "2")]
    pub function: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub field: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub window: ::core::option::Option<TimeWindow>,
    #[prost(string, tag = "5")]
    pub group_by: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transformation {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(enumeration = "transformation::Type", tag = "2")]
    pub r#type: i32,
    #[prost(map = "string, string", tag = "3")]
    pub params: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
/// Nested message and enum types in `Transformation`.
pub mod transformation {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Type {
        Unspecified = 0,
        Normalization = 1,
        Standardization = 2,
        Log = 3,
        Polynomial = 4,
        CategoricalEncoding = 5,
        Embedding = 6,
        Custom = 7,
    }
    impl Type {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Type::Unspecified => "TYPE_UNSPECIFIED",
                Type::Normalization => "TYPE_NORMALIZATION",
                Type::Standardization => "TYPE_STANDARDIZATION",
                Type::Log => "TYPE_LOG",
                Type::Polynomial => "TYPE_POLYNOMIAL",
                Type::CategoricalEncoding => "TYPE_CATEGORICAL_ENCODING",
                Type::Embedding => "TYPE_EMBEDDING",
                Type::Custom => "TYPE_CUSTOM",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "TYPE_UNSPECIFIED" => Some(Self::Unspecified),
                "TYPE_NORMALIZATION" => Some(Self::Normalization),
                "TYPE_STANDARDIZATION" => Some(Self::Standardization),
                "TYPE_LOG" => Some(Self::Log),
                "TYPE_POLYNOMIAL" => Some(Self::Polynomial),
                "TYPE_CATEGORICAL_ENCODING" => Some(Self::CategoricalEncoding),
                "TYPE_EMBEDDING" => Some(Self::Embedding),
                "TYPE_CUSTOM" => Some(Self::Custom),
                _ => None,
            }
        }
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TimeWindow {
    #[prost(message, optional, tag = "1")]
    pub start: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "2")]
    pub end: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(int64, tag = "3")]
    pub duration_seconds: i64,
    /// e.g., "5m", "1h"
    #[prost(string, tag = "4")]
    pub sliding_window: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub tumbling_window: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QualityRequirements {
    #[prost(float, tag = "1")]
    pub min_completeness: f32,
    #[prost(int64, tag = "2")]
    pub max_latency_ms: i64,
    #[prost(float, tag = "3")]
    pub min_quality_score: f32,
    #[prost(bool, tag = "4")]
    pub allow_missing: bool,
    #[prost(bool, tag = "5")]
    pub allow_outliers: bool,
    #[prost(message, repeated, tag = "6")]
    pub drift_thresholds: ::prost::alloc::vec::Vec<
        quality_requirements::DataDriftThreshold,
    >,
}
/// Nested message and enum types in `QualityRequirements`.
pub mod quality_requirements {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct DataDriftThreshold {
        #[prost(string, tag = "1")]
        pub metric: ::prost::alloc::string::String,
        #[prost(float, tag = "2")]
        pub threshold: f32,
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProcessingOptions {
    #[prost(bool, tag = "1")]
    pub r#async: bool,
    #[prost(int32, tag = "2")]
    pub parallelism: i32,
    #[prost(int64, tag = "3")]
    pub timeout_ms: i64,
    #[prost(bool, tag = "4")]
    pub cache_enabled: bool,
    #[prost(int64, tag = "5")]
    pub cache_ttl_seconds: i64,
    #[prost(bool, tag = "6")]
    pub incremental: bool,
}
/// Feature extraction response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FeatureExtractionResponse {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub success: bool,
    #[prost(message, optional, tag = "3")]
    pub feature_set: ::core::option::Option<FeatureSet>,
    #[prost(message, optional, tag = "4")]
    pub metrics: ::core::option::Option<ExtractionMetrics>,
    #[prost(message, repeated, tag = "5")]
    pub issues: ::prost::alloc::vec::Vec<DataQualityIssue>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FeatureSet {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, repeated, tag = "4")]
    pub features: ::prost::alloc::vec::Vec<Feature>,
    #[prost(map = "string, message", tag = "5")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost_types::Value,
    >,
    /// Storage location
    #[prost(string, tag = "6")]
    pub storage_path: ::prost::alloc::string::String,
    /// parquet, tfrecord, etc.
    #[prost(string, tag = "7")]
    pub format: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Feature {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub value: ::core::option::Option<::prost_types::Value>,
    #[prost(message, optional, tag = "3")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(map = "string, string", tag = "4")]
    pub tags: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExtractionMetrics {
    #[prost(int64, tag = "1")]
    pub records_processed: i64,
    #[prost(int64, tag = "2")]
    pub features_extracted: i64,
    #[prost(int64, tag = "3")]
    pub processing_time_ms: i64,
    #[prost(float, tag = "4")]
    pub completeness: f32,
    #[prost(float, tag = "5")]
    pub quality_score: f32,
    #[prost(map = "string, float", tag = "6")]
    pub feature_statistics: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        f32,
    >,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DataQualityIssue {
    #[prost(enumeration = "Severity", tag = "1")]
    pub severity: i32,
    #[prost(string, tag = "2")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub field: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub description: ::prost::alloc::string::String,
    #[prost(int64, tag = "5")]
    pub occurrences: i64,
    #[prost(message, optional, tag = "6")]
    pub sample: ::core::option::Option<::prost_types::Value>,
}
/// Training data preparation
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TrainingDataRequest {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub model_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub dataset: ::core::option::Option<DatasetConfig>,
    #[prost(message, optional, tag = "4")]
    pub split: ::core::option::Option<SplitConfig>,
    #[prost(message, optional, tag = "5")]
    pub sampling: ::core::option::Option<SamplingConfig>,
    #[prost(message, optional, tag = "6")]
    pub augmentation: ::core::option::Option<AugmentationConfig>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DatasetConfig {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub feature_sets: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "4")]
    pub label_column: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub time_range: ::core::option::Option<TimeWindow>,
    #[prost(map = "string, string", tag = "6")]
    pub filters: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SplitConfig {
    #[prost(float, tag = "1")]
    pub train_ratio: f32,
    #[prost(float, tag = "2")]
    pub validation_ratio: f32,
    #[prost(float, tag = "3")]
    pub test_ratio: f32,
    #[prost(enumeration = "split_config::SplitStrategy", tag = "4")]
    pub strategy: i32,
    #[prost(string, tag = "5")]
    pub group_column: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "6")]
    pub split_timestamp: ::core::option::Option<::prost_types::Timestamp>,
}
/// Nested message and enum types in `SplitConfig`.
pub mod split_config {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum SplitStrategy {
        Unspecified = 0,
        Random = 1,
        TimeBased = 2,
        Stratified = 3,
        Group = 4,
    }
    impl SplitStrategy {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                SplitStrategy::Unspecified => "SPLIT_STRATEGY_UNSPECIFIED",
                SplitStrategy::Random => "SPLIT_STRATEGY_RANDOM",
                SplitStrategy::TimeBased => "SPLIT_STRATEGY_TIME_BASED",
                SplitStrategy::Stratified => "SPLIT_STRATEGY_STRATIFIED",
                SplitStrategy::Group => "SPLIT_STRATEGY_GROUP",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "SPLIT_STRATEGY_UNSPECIFIED" => Some(Self::Unspecified),
                "SPLIT_STRATEGY_RANDOM" => Some(Self::Random),
                "SPLIT_STRATEGY_TIME_BASED" => Some(Self::TimeBased),
                "SPLIT_STRATEGY_STRATIFIED" => Some(Self::Stratified),
                "SPLIT_STRATEGY_GROUP" => Some(Self::Group),
                _ => None,
            }
        }
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SamplingConfig {
    #[prost(enumeration = "sampling_config::SamplingMethod", tag = "1")]
    pub method: i32,
    #[prost(float, tag = "2")]
    pub sample_rate: f32,
    #[prost(map = "string, float", tag = "3")]
    pub class_weights: ::std::collections::HashMap<::prost::alloc::string::String, f32>,
    #[prost(int32, tag = "4")]
    pub random_seed: i32,
}
/// Nested message and enum types in `SamplingConfig`.
pub mod sampling_config {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum SamplingMethod {
        Unspecified = 0,
        Random = 1,
        Stratified = 2,
        Systematic = 3,
        Cluster = 4,
        /// For imbalanced data
        Smote = 5,
    }
    impl SamplingMethod {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                SamplingMethod::Unspecified => "SAMPLING_METHOD_UNSPECIFIED",
                SamplingMethod::Random => "SAMPLING_METHOD_RANDOM",
                SamplingMethod::Stratified => "SAMPLING_METHOD_STRATIFIED",
                SamplingMethod::Systematic => "SAMPLING_METHOD_SYSTEMATIC",
                SamplingMethod::Cluster => "SAMPLING_METHOD_CLUSTER",
                SamplingMethod::Smote => "SAMPLING_METHOD_SMOTE",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "SAMPLING_METHOD_UNSPECIFIED" => Some(Self::Unspecified),
                "SAMPLING_METHOD_RANDOM" => Some(Self::Random),
                "SAMPLING_METHOD_STRATIFIED" => Some(Self::Stratified),
                "SAMPLING_METHOD_SYSTEMATIC" => Some(Self::Systematic),
                "SAMPLING_METHOD_CLUSTER" => Some(Self::Cluster),
                "SAMPLING_METHOD_SMOTE" => Some(Self::Smote),
                _ => None,
            }
        }
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AugmentationConfig {
    #[prost(bool, tag = "1")]
    pub enabled: bool,
    #[prost(message, repeated, tag = "2")]
    pub techniques: ::prost::alloc::vec::Vec<AugmentationTechnique>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AugmentationTechnique {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(enumeration = "augmentation_technique::Type", tag = "2")]
    pub r#type: i32,
    #[prost(map = "string, float", tag = "3")]
    pub params: ::std::collections::HashMap<::prost::alloc::string::String, f32>,
}
/// Nested message and enum types in `AugmentationTechnique`.
pub mod augmentation_technique {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Type {
        Unspecified = 0,
        NoiseInjection = 1,
        TimeWarping = 2,
        SyntheticMinority = 3,
        FeatureCombination = 4,
    }
    impl Type {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Type::Unspecified => "TYPE_UNSPECIFIED",
                Type::NoiseInjection => "TYPE_NOISE_INJECTION",
                Type::TimeWarping => "TYPE_TIME_WARPING",
                Type::SyntheticMinority => "TYPE_SYNTHETIC_MINORITY",
                Type::FeatureCombination => "TYPE_FEATURE_COMBINATION",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "TYPE_UNSPECIFIED" => Some(Self::Unspecified),
                "TYPE_NOISE_INJECTION" => Some(Self::NoiseInjection),
                "TYPE_TIME_WARPING" => Some(Self::TimeWarping),
                "TYPE_SYNTHETIC_MINORITY" => Some(Self::SyntheticMinority),
                "TYPE_FEATURE_COMBINATION" => Some(Self::FeatureCombination),
                _ => None,
            }
        }
    }
}
/// Training data response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TrainingDataResponse {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub success: bool,
    #[prost(message, optional, tag = "3")]
    pub dataset: ::core::option::Option<TrainingDataset>,
    #[prost(message, optional, tag = "4")]
    pub metrics: ::core::option::Option<DatasetMetrics>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TrainingDataset {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub train: ::core::option::Option<DatasetSplit>,
    #[prost(message, optional, tag = "4")]
    pub validation: ::core::option::Option<DatasetSplit>,
    #[prost(message, optional, tag = "5")]
    pub test: ::core::option::Option<DatasetSplit>,
    #[prost(map = "string, string", tag = "6")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DatasetSplit {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub num_samples: i64,
    #[prost(int64, tag = "3")]
    pub num_features: i64,
    #[prost(map = "string, int64", tag = "4")]
    pub class_distribution: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        i64,
    >,
    #[prost(message, optional, tag = "5")]
    pub stats: ::core::option::Option<dataset_split::Statistics>,
}
/// Nested message and enum types in `DatasetSplit`.
pub mod dataset_split {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Statistics {
        #[prost(map = "string, message", tag = "1")]
        pub features: ::std::collections::HashMap<
            ::prost::alloc::string::String,
            super::FeatureStatistics,
        >,
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FeatureStatistics {
    #[prost(float, tag = "1")]
    pub min: f32,
    #[prost(float, tag = "2")]
    pub max: f32,
    #[prost(float, tag = "3")]
    pub mean: f32,
    #[prost(float, tag = "4")]
    pub std: f32,
    #[prost(float, tag = "5")]
    pub missing_ratio: f32,
    #[prost(int64, tag = "6")]
    pub unique_values: i64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DatasetMetrics {
    #[prost(int64, tag = "1")]
    pub total_samples: i64,
    #[prost(int64, tag = "2")]
    pub total_features: i64,
    #[prost(float, tag = "3")]
    pub dataset_size_mb: f32,
    #[prost(int64, tag = "4")]
    pub preparation_time_ms: i64,
    #[prost(map = "string, float", tag = "5")]
    pub quality_metrics: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        f32,
    >,
}
/// Model serving request preparation
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModelServingDataRequest {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub model_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub inputs: ::prost::alloc::vec::Vec<InputData>,
    #[prost(message, optional, tag = "4")]
    pub preprocessing: ::core::option::Option<PreprocessingConfig>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InputData {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(map = "string, message", tag = "2")]
    pub features: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost_types::Value,
    >,
    #[prost(message, optional, tag = "3")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PreprocessingConfig {
    #[prost(bool, tag = "1")]
    pub normalize: bool,
    #[prost(bool, tag = "2")]
    pub handle_missing: bool,
    /// mean, median, forward_fill, etc.
    #[prost(string, tag = "3")]
    pub missing_strategy: ::prost::alloc::string::String,
    #[prost(map = "string, message", tag = "4")]
    pub transformations: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        Transformation,
    >,
}
/// Additional messages for service methods
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FeatureStatisticsRequest {
    #[prost(string, tag = "1")]
    pub feature_set_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub window: ::core::option::Option<TimeWindow>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FeatureStatisticsResponse {
    #[prost(map = "string, message", tag = "1")]
    pub statistics: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        FeatureStatistics,
    >,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TrainingDataValidationRequest {
    #[prost(string, tag = "1")]
    pub dataset_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub rules: ::prost::alloc::vec::Vec<ValidationRule>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TrainingDataValidationResponse {
    #[prost(bool, tag = "1")]
    pub valid: bool,
    #[prost(message, repeated, tag = "2")]
    pub issues: ::prost::alloc::vec::Vec<DataQualityIssue>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DataDriftRequest {
    #[prost(string, tag = "1")]
    pub reference_dataset: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub target_dataset: ::prost::alloc::string::String,
    /// KS, PSI, etc.
    #[prost(string, repeated, tag = "3")]
    pub metrics: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DataDriftResponse {
    #[prost(map = "string, float", tag = "1")]
    pub drift_scores: ::std::collections::HashMap<::prost::alloc::string::String, f32>,
    #[prost(bool, tag = "2")]
    pub drift_detected: bool,
    #[prost(string, repeated, tag = "3")]
    pub drifted_features: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Severity {
    Unspecified = 0,
    Warning = 1,
    Error = 2,
    Critical = 3,
}
impl Severity {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Severity::Unspecified => "SEVERITY_UNSPECIFIED",
            Severity::Warning => "SEVERITY_WARNING",
            Severity::Error => "SEVERITY_ERROR",
            Severity::Critical => "SEVERITY_CRITICAL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SEVERITY_UNSPECIFIED" => Some(Self::Unspecified),
            "SEVERITY_WARNING" => Some(Self::Warning),
            "SEVERITY_ERROR" => Some(Self::Error),
            "SEVERITY_CRITICAL" => Some(Self::Critical),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod feature_extraction_service_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Services
    #[derive(Debug, Clone)]
    pub struct FeatureExtractionServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl FeatureExtractionServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> FeatureExtractionServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> FeatureExtractionServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + Send + Sync,
        {
            FeatureExtractionServiceClient::new(
                InterceptedService::new(inner, interceptor),
            )
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Extract features from event stream
        pub async fn extract_features(
            &mut self,
            request: impl tonic::IntoRequest<super::FeatureExtractionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::FeatureExtractionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/neural_trader.interfaces.mlops.FeatureExtractionService/ExtractFeatures",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "neural_trader.interfaces.mlops.FeatureExtractionService",
                        "ExtractFeatures",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Stream feature extraction
        pub async fn extract_features_stream(
            &mut self,
            request: impl tonic::IntoStreamingRequest<
                Message = super::FeatureExtractionRequest,
            >,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::FeatureExtractionResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/neural_trader.interfaces.mlops.FeatureExtractionService/ExtractFeaturesStream",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "neural_trader.interfaces.mlops.FeatureExtractionService",
                        "ExtractFeaturesStream",
                    ),
                );
            self.inner.streaming(req, path, codec).await
        }
        /// Get feature statistics
        pub async fn get_feature_statistics(
            &mut self,
            request: impl tonic::IntoRequest<super::FeatureStatisticsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::FeatureStatisticsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/neural_trader.interfaces.mlops.FeatureExtractionService/GetFeatureStatistics",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "neural_trader.interfaces.mlops.FeatureExtractionService",
                        "GetFeatureStatistics",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated client implementations.
pub mod training_data_service_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct TrainingDataServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl TrainingDataServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> TrainingDataServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> TrainingDataServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + Send + Sync,
        {
            TrainingDataServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Prepare training data
        pub async fn prepare_training_data(
            &mut self,
            request: impl tonic::IntoRequest<super::TrainingDataRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TrainingDataResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/neural_trader.interfaces.mlops.TrainingDataService/PrepareTrainingData",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "neural_trader.interfaces.mlops.TrainingDataService",
                        "PrepareTrainingData",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Validate training data
        pub async fn validate_training_data(
            &mut self,
            request: impl tonic::IntoRequest<super::TrainingDataValidationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TrainingDataValidationResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/neural_trader.interfaces.mlops.TrainingDataService/ValidateTrainingData",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "neural_trader.interfaces.mlops.TrainingDataService",
                        "ValidateTrainingData",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Monitor data drift
        pub async fn monitor_data_drift(
            &mut self,
            request: impl tonic::IntoRequest<super::DataDriftRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DataDriftResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/neural_trader.interfaces.mlops.TrainingDataService/MonitorDataDrift",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "neural_trader.interfaces.mlops.TrainingDataService",
                        "MonitorDataDrift",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod feature_extraction_service_server {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with FeatureExtractionServiceServer.
    #[async_trait]
    pub trait FeatureExtractionService: Send + Sync + 'static {
        /// Extract features from event stream
        async fn extract_features(
            &self,
            request: tonic::Request<super::FeatureExtractionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::FeatureExtractionResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the ExtractFeaturesStream method.
        type ExtractFeaturesStreamStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<
                    super::FeatureExtractionResponse,
                    tonic::Status,
                >,
            >
            + Send
            + 'static;
        /// Stream feature extraction
        async fn extract_features_stream(
            &self,
            request: tonic::Request<tonic::Streaming<super::FeatureExtractionRequest>>,
        ) -> std::result::Result<
            tonic::Response<Self::ExtractFeaturesStreamStream>,
            tonic::Status,
        >;
        /// Get feature statistics
        async fn get_feature_statistics(
            &self,
            request: tonic::Request<super::FeatureStatisticsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::FeatureStatisticsResponse>,
            tonic::Status,
        >;
    }
    /// Services
    #[derive(Debug)]
    pub struct FeatureExtractionServiceServer<T: FeatureExtractionService> {
        inner: _Inner<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    struct _Inner<T>(Arc<T>);
    impl<T: FeatureExtractionService> FeatureExtractionServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            let inner = _Inner(inner);
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>>
    for FeatureExtractionServiceServer<T>
    where
        T: FeatureExtractionService,
        B: Body + Send + 'static,
        B::Error: Into<StdError> + Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            let inner = self.inner.clone();
            match req.uri().path() {
                "/neural_trader.interfaces.mlops.FeatureExtractionService/ExtractFeatures" => {
                    #[allow(non_camel_case_types)]
                    struct ExtractFeaturesSvc<T: FeatureExtractionService>(pub Arc<T>);
                    impl<
                        T: FeatureExtractionService,
                    > tonic::server::UnaryService<super::FeatureExtractionRequest>
                    for ExtractFeaturesSvc<T> {
                        type Response = super::FeatureExtractionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::FeatureExtractionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as FeatureExtractionService>::extract_features(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = ExtractFeaturesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/neural_trader.interfaces.mlops.FeatureExtractionService/ExtractFeaturesStream" => {
                    #[allow(non_camel_case_types)]
                    struct ExtractFeaturesStreamSvc<T: FeatureExtractionService>(
                        pub Arc<T>,
                    );
                    impl<
                        T: FeatureExtractionService,
                    > tonic::server::StreamingService<super::FeatureExtractionRequest>
                    for ExtractFeaturesStreamSvc<T> {
                        type Response = super::FeatureExtractionResponse;
                        type ResponseStream = T::ExtractFeaturesStreamStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::FeatureExtractionRequest>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as FeatureExtractionService>::extract_features_stream(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = ExtractFeaturesStreamSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/neural_trader.interfaces.mlops.FeatureExtractionService/GetFeatureStatistics" => {
                    #[allow(non_camel_case_types)]
                    struct GetFeatureStatisticsSvc<T: FeatureExtractionService>(
                        pub Arc<T>,
                    );
                    impl<
                        T: FeatureExtractionService,
                    > tonic::server::UnaryService<super::FeatureStatisticsRequest>
                    for GetFeatureStatisticsSvc<T> {
                        type Response = super::FeatureStatisticsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::FeatureStatisticsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as FeatureExtractionService>::get_feature_statistics(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetFeatureStatisticsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        Ok(
                            http::Response::builder()
                                .status(200)
                                .header("grpc-status", "12")
                                .header("content-type", "application/grpc")
                                .body(empty_body())
                                .unwrap(),
                        )
                    })
                }
            }
        }
    }
    impl<T: FeatureExtractionService> Clone for FeatureExtractionServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    impl<T: FeatureExtractionService> Clone for _Inner<T> {
        fn clone(&self) -> Self {
            Self(Arc::clone(&self.0))
        }
    }
    impl<T: std::fmt::Debug> std::fmt::Debug for _Inner<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{:?}", self.0)
        }
    }
    impl<T: FeatureExtractionService> tonic::server::NamedService
    for FeatureExtractionServiceServer<T> {
        const NAME: &'static str = "neural_trader.interfaces.mlops.FeatureExtractionService";
    }
}
/// Generated server implementations.
pub mod training_data_service_server {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with TrainingDataServiceServer.
    #[async_trait]
    pub trait TrainingDataService: Send + Sync + 'static {
        /// Prepare training data
        async fn prepare_training_data(
            &self,
            request: tonic::Request<super::TrainingDataRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TrainingDataResponse>,
            tonic::Status,
        >;
        /// Validate training data
        async fn validate_training_data(
            &self,
            request: tonic::Request<super::TrainingDataValidationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TrainingDataValidationResponse>,
            tonic::Status,
        >;
        /// Monitor data drift
        async fn monitor_data_drift(
            &self,
            request: tonic::Request<super::DataDriftRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DataDriftResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct TrainingDataServiceServer<T: TrainingDataService> {
        inner: _Inner<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    struct _Inner<T>(Arc<T>);
    impl<T: TrainingDataService> TrainingDataServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            let inner = _Inner(inner);
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for TrainingDataServiceServer<T>
    where
        T: TrainingDataService,
        B: Body + Send + 'static,
        B::Error: Into<StdError> + Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            let inner = self.inner.clone();
            match req.uri().path() {
                "/neural_trader.interfaces.mlops.TrainingDataService/PrepareTrainingData" => {
                    #[allow(non_camel_case_types)]
                    struct PrepareTrainingDataSvc<T: TrainingDataService>(pub Arc<T>);
                    impl<
                        T: TrainingDataService,
                    > tonic::server::UnaryService<super::TrainingDataRequest>
                    for PrepareTrainingDataSvc<T> {
                        type Response = super::TrainingDataResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::TrainingDataRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TrainingDataService>::prepare_training_data(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = PrepareTrainingDataSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/neural_trader.interfaces.mlops.TrainingDataService/ValidateTrainingData" => {
                    #[allow(non_camel_case_types)]
                    struct ValidateTrainingDataSvc<T: TrainingDataService>(pub Arc<T>);
                    impl<
                        T: TrainingDataService,
                    > tonic::server::UnaryService<super::TrainingDataValidationRequest>
                    for ValidateTrainingDataSvc<T> {
                        type Response = super::TrainingDataValidationResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::TrainingDataValidationRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TrainingDataService>::validate_training_data(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = ValidateTrainingDataSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/neural_trader.interfaces.mlops.TrainingDataService/MonitorDataDrift" => {
                    #[allow(non_camel_case_types)]
                    struct MonitorDataDriftSvc<T: TrainingDataService>(pub Arc<T>);
                    impl<
                        T: TrainingDataService,
                    > tonic::server::UnaryService<super::DataDriftRequest>
                    for MonitorDataDriftSvc<T> {
                        type Response = super::DataDriftResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DataDriftRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TrainingDataService>::monitor_data_drift(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = MonitorDataDriftSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        Ok(
                            http::Response::builder()
                                .status(200)
                                .header("grpc-status", "12")
                                .header("content-type", "application/grpc")
                                .body(empty_body())
                                .unwrap(),
                        )
                    })
                }
            }
        }
    }
    impl<T: TrainingDataService> Clone for TrainingDataServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    impl<T: TrainingDataService> Clone for _Inner<T> {
        fn clone(&self) -> Self {
            Self(Arc::clone(&self.0))
        }
    }
    impl<T: std::fmt::Debug> std::fmt::Debug for _Inner<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{:?}", self.0)
        }
    }
    impl<T: TrainingDataService> tonic::server::NamedService
    for TrainingDataServiceServer<T> {
        const NAME: &'static str = "neural_trader.interfaces.mlops.TrainingDataService";
    }
}
