#!/bin/bash
# Install Git Hooks for Phase 3 Production Validation
# This script sets up git hooks to enforce validation before commits

set -euo pipefail

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
GIT_HOOKS_DIR="$PROJECT_ROOT/.git/hooks"

print_banner() {
    echo -e "${BLUE}${BOLD}"
    echo "=================================================================="
    echo "  Phase 3 Production Validation - Git Hooks Installation"
    echo "=================================================================="
    echo -e "${NC}"
}

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

check_git_repo() {
    if [ ! -d "$PROJECT_ROOT/.git" ]; then
        log_error "Not a git repository: $PROJECT_ROOT"
        exit 1
    fi
    
    if [ ! -d "$GIT_HOOKS_DIR" ]; then
        log_error "Git hooks directory not found: $GIT_HOOKS_DIR"
        exit 1
    fi
    
    log_success "Git repository found"
}

backup_existing_hooks() {
    log_info "Backing up existing git hooks..."
    
    local hooks=("pre-commit" "commit-msg" "pre-push")
    local backup_dir="$GIT_HOOKS_DIR/backup-$(date +%Y%m%d-%H%M%S)"
    
    for hook in "${hooks[@]}"; do
        if [ -f "$GIT_HOOKS_DIR/$hook" ]; then
            if [ ! -d "$backup_dir" ]; then
                mkdir -p "$backup_dir"
            fi
            cp "$GIT_HOOKS_DIR/$hook" "$backup_dir/$hook"
            log_info "Backed up existing $hook hook"
        fi
    done
    
    if [ -d "$backup_dir" ]; then
        log_success "Existing hooks backed up to: $backup_dir"
    fi
}

install_pre_commit_hook() {
    log_info "Installing pre-commit hook..."
    
    cat > "$GIT_HOOKS_DIR/pre-commit" << 'EOF'
#!/bin/bash
# Phase 3 Production Validation Pre-Commit Hook
# Auto-generated by install-hooks.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
VALIDATION_SCRIPT="$PROJECT_ROOT/scripts/validation/pre-commit-hook.sh"

if [ -x "$VALIDATION_SCRIPT" ]; then
    exec "$VALIDATION_SCRIPT" "$@"
else
    echo "❌ Validation script not found or not executable: $VALIDATION_SCRIPT"
    exit 1
fi
EOF
    
    chmod +x "$GIT_HOOKS_DIR/pre-commit"
    log_success "Pre-commit hook installed"
}

install_commit_msg_hook() {
    log_info "Installing commit-msg hook..."
    
    cat > "$GIT_HOOKS_DIR/commit-msg" << 'EOF'
#!/bin/bash
# Phase 3 Production Validation Commit Message Hook
# Auto-generated by install-hooks.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
VALIDATION_SCRIPT="$PROJECT_ROOT/scripts/validation/pre-commit-hook.sh"

if [ -x "$VALIDATION_SCRIPT" ]; then
    exec "$VALIDATION_SCRIPT" "commit-msg" "$1"
else
    echo "❌ Validation script not found or not executable: $VALIDATION_SCRIPT"
    exit 1
fi
EOF
    
    chmod +x "$GIT_HOOKS_DIR/commit-msg"
    log_success "Commit message hook installed"
}

install_pre_push_hook() {
    log_info "Installing pre-push hook..."
    
    cat > "$GIT_HOOKS_DIR/pre-push" << 'EOF'
#!/bin/bash
# Phase 3 Production Validation Pre-Push Hook
# Auto-generated by install-hooks.sh

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
VALIDATION_SCRIPT="$PROJECT_ROOT/scripts/validation/run-production-validation.sh"

echo -e "${BLUE}🔍 Running pre-push validation...${NC}"

# Check if we're pushing to protected branches
remote="$1"
remote_url="$2"

# Read from stdin to get the list of refs being pushed
while read local_ref local_sha remote_ref remote_sha; do
    if [ "$local_sha" = "0000000000000000000000000000000000000000" ]; then
        # Delete operation, skip validation
        continue
    fi
    
    # Extract branch name from ref
    branch_name=$(echo "$remote_ref" | sed 's/refs\/heads\///')
    
    echo -e "${BLUE}Validating push to branch: $branch_name${NC}"
    
    # Run different validation levels based on target branch
    if [[ "$branch_name" == "main" || "$branch_name" == "master" ]]; then
        echo -e "${YELLOW}⚠️  Pushing to main branch - running FULL validation${NC}"
        
        if [ -x "$VALIDATION_SCRIPT" ]; then
            "$VALIDATION_SCRIPT" --validator=all --mode=production --no-fail-fast
            if [ $? -ne 0 ]; then
                echo -e "${RED}❌ PUSH BLOCKED: Full validation failed${NC}"
                echo -e "${RED}🚨 Main branch requires ALL validation gates to pass${NC}"
                exit 1
            fi
        else
            echo -e "${YELLOW}⚠️  Validation script not found, allowing push${NC}"
        fi
        
    elif [[ "$branch_name" =~ ^release/ ]]; then
        echo -e "${YELLOW}⚠️  Pushing to release branch - running PRODUCTION validation${NC}"
        
        if [ -x "$VALIDATION_SCRIPT" ]; then
            "$VALIDATION_SCRIPT" --validator=all --mode=production
            if [ $? -ne 0 ]; then
                echo -e "${RED}❌ PUSH BLOCKED: Production validation failed${NC}"
                echo -e "${RED}🚨 Release branch requires production-ready code${NC}"
                exit 1
            fi
        fi
        
    elif [[ "$branch_name" =~ ^feature/ ]]; then
        echo -e "${BLUE}ℹ️  Feature branch - running basic validation${NC}"
        
        if [ -x "$VALIDATION_SCRIPT" ]; then
            "$VALIDATION_SCRIPT" --validator=code-completeness --mode=development
            if [ $? -ne 0 ]; then
                echo -e "${YELLOW}⚠️  Basic validation failed, but allowing push to feature branch${NC}"
                echo -e "${YELLOW}💡 Fix issues before merging to main${NC}"
            fi
        fi
        
    else
        echo -e "${BLUE}ℹ️  Development branch - minimal validation${NC}"
    fi
    
done

echo -e "${GREEN}✅ Pre-push validation completed${NC}"
exit 0
EOF
    
    chmod +x "$GIT_HOOKS_DIR/pre-push"
    log_success "Pre-push hook installed"
}

test_hooks() {
    log_info "Testing installed hooks..."
    
    # Test if hooks are executable
    local hooks=("pre-commit" "commit-msg" "pre-push")
    local test_failed=false
    
    for hook in "${hooks[@]}"; do
        if [ ! -x "$GIT_HOOKS_DIR/$hook" ]; then
            log_error "$hook hook is not executable"
            test_failed=true
        else
            log_success "$hook hook is executable"
        fi
    done
    
    if [ "$test_failed" = true ]; then
        log_error "Hook installation test failed"
        return 1
    fi
    
    log_success "All hooks are properly installed and executable"
    return 0
}

show_usage_info() {
    echo ""
    echo -e "${BLUE}${BOLD}📋 Git Hooks Installation Complete${NC}"
    echo ""
    echo -e "${GREEN}✅ Installed Hooks:${NC}"
    echo -e "   ${GREEN}•${NC} pre-commit    - Validates code before each commit"
    echo -e "   ${GREEN}•${NC} commit-msg    - Validates commit message format"
    echo -e "   ${GREEN}•${NC} pre-push      - Runs validation before push (branch-specific)"
    echo ""
    echo -e "${BLUE}🎯 Hook Behavior:${NC}"
    echo -e "   ${BLUE}•${NC} Feature branches: Basic validation (non-blocking)"
    echo -e "   ${BLUE}•${NC} Release branches: Production validation (blocking)"
    echo -e "   ${BLUE}•${NC} Main branch: Full validation suite (blocking)"
    echo ""
    echo -e "${YELLOW}💡 Tips:${NC}"
    echo -e "   ${YELLOW}•${NC} Skip hooks temporarily: git commit --no-verify"
    echo -e "   ${YELLOW}•${NC} Run full validation: ./scripts/validation/run-production-validation.sh --validator=all"
    echo -e "   ${YELLOW}•${NC} Test hooks: git commit --dry-run"
    echo ""
    echo -e "${GREEN}🚀 ZERO TOLERANCE enforcement is now active!${NC}"
}

uninstall_hooks() {
    log_info "Uninstalling validation hooks..."
    
    local hooks=("pre-commit" "commit-msg" "pre-push")
    
    for hook in "${hooks[@]}"; do
        if [ -f "$GIT_HOOKS_DIR/$hook" ]; then
            rm "$GIT_HOOKS_DIR/$hook"
            log_success "Removed $hook hook"
        fi
    done
    
    log_success "All validation hooks uninstalled"
}

print_usage() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "OPTIONS:"
    echo "  --install     Install git hooks (default)"
    echo "  --uninstall   Remove installed git hooks"
    echo "  --test        Test installed hooks"
    echo "  --help        Show this help message"
}

# Main execution
main() {
    local action="install"
    
    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case $1 in
            --install)
                action="install"
                shift
                ;;
            --uninstall)
                action="uninstall"
                shift
                ;;
            --test)
                action="test"
                shift
                ;;
            --help)
                print_usage
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                print_usage
                exit 1
                ;;
        esac
    done
    
    print_banner
    check_git_repo
    
    case $action in
        "install")
            backup_existing_hooks
            install_pre_commit_hook
            install_commit_msg_hook
            install_pre_push_hook
            test_hooks
            show_usage_info
            ;;
        "uninstall")
            uninstall_hooks
            ;;
        "test")
            test_hooks
            ;;
    esac
}

main "$@"