//! Continuous aggregate DDL generator
//!
//! Generates TimescaleDB continuous aggregate views from Gold ETL configuration.

use crate::gold::config::{
    Action, AggregatesConfig, GoldEtlConfig, RefreshPolicyConfig, StreamConfig, VALID_METRICS,
};
use crate::gold::error::{GoldDdlError, Result};
use crate::gold::validation::granularity_to_suffix;

/// Generator for continuous aggregate DDL
pub struct ContinuousAggregateGenerator {
    /// Stream ID being processed
    stream_id: String,
    /// Source table (from silver_etl.target_table)
    source_table: String,
    /// Timestamp column name
    timestamp_column: String,
    /// Entity column name
    entity_column: String,
}

impl ContinuousAggregateGenerator {
    /// Create a new generator from stream configuration
    pub fn from_stream_config(config: &StreamConfig) -> Result<Self> {
        let source_table = config
            .silver_etl
            .as_ref()
            .map(|s| s.target_table.clone())
            .ok_or_else(|| GoldDdlError::MissingRequiredField {
                field: "silver_etl.target_table".to_string(),
                context: format!("stream '{}'", config.stream_id),
            })?;

        let timestamp_column = config
            .silver_etl
            .as_ref()
            .and_then(|s| s.timestamp.as_ref())
            .map(|t| t.target_field.clone())
            .unwrap_or_else(|| "observation_time".to_string());

        Ok(Self {
            stream_id: config.stream_id.clone(),
            source_table,
            timestamp_column,
            entity_column: "ndp_id".to_string(),
        })
    }

    /// Generate complete DDL for all granularities
    pub fn generate(&self, gold_etl: &GoldEtlConfig, action: Action) -> Result<String> {
        let aggregates =
            gold_etl
                .aggregates
                .as_ref()
                .ok_or_else(|| GoldDdlError::MissingRequiredField {
                    field: "gold_etl.aggregates".to_string(),
                    context: format!("stream '{}'", self.stream_id),
                })?;

        let mut ddl_parts = Vec::new();

        // Schema creation
        ddl_parts.push("-- Gold layer DDL for stream: ".to_string() + &self.stream_id);
        ddl_parts.push("-- Generated by ndp-gold-ddl".to_string());
        ddl_parts.push(String::new());
        ddl_parts.push("CREATE SCHEMA IF NOT EXISTS gold;".to_string());
        ddl_parts.push(String::new());

        // Generate view for each granularity
        for granularity in &aggregates.granularities {
            let view_ddl = self.generate_for_granularity(aggregates, granularity, action)?;
            ddl_parts.push(view_ddl);
            ddl_parts.push(String::new());
        }

        // Generate refresh policies
        for granularity in &aggregates.granularities {
            let policy_ddl =
                self.generate_refresh_policy(granularity, gold_etl.refresh_policy.as_ref())?;
            ddl_parts.push(policy_ddl);
            ddl_parts.push(String::new());
        }

        Ok(ddl_parts.join("\n"))
    }

    /// Generate DDL for a single granularity
    fn generate_for_granularity(
        &self,
        aggregates: &AggregatesConfig,
        granularity: &str,
        action: Action,
    ) -> Result<String> {
        let suffix = granularity_to_suffix(granularity);
        let view_name = format!("gold.{}_{}", self.stream_id.replace('-', "_"), suffix);

        // Generate aggregate columns
        let columns = self.generate_aggregate_columns(aggregates)?;

        // Build CREATE MATERIALIZED VIEW
        let create_sql = format!(
            r#"CREATE MATERIALIZED VIEW {view_name}
WITH (timescaledb.continuous) AS
SELECT
    time_bucket('{granularity}', {timestamp_col}) AS bucket,
    {entity_col},
    {columns}
FROM {source_table}
GROUP BY bucket, {entity_col};"#,
            view_name = view_name,
            granularity = granularity,
            timestamp_col = self.timestamp_column,
            entity_col = self.entity_column,
            columns = columns.join(",\n    "),
            source_table = self.source_table,
        );

        // Wrap with idempotency based on action
        match action {
            Action::Sync => self.wrap_sync_mode(&view_name, &create_sql),
            Action::Recreate => self.wrap_recreate_mode(&view_name, &create_sql),
        }
    }

    /// Generate only the CREATE MATERIALIZED VIEW statement for a granularity
    ///
    /// Used by the SyncPlanner which handles idempotency externally via DB checks.
    /// Returns raw DDL without any wrapper (no DO block, no CA-SYNC-CHECK markers).
    pub fn generate_ca_ddl_only(
        &self,
        aggregates: &AggregatesConfig,
        granularity: &str,
    ) -> Result<String> {
        let suffix = granularity_to_suffix(granularity);
        let view_name = format!("gold.{}_{}", self.stream_id.replace('-', "_"), suffix);

        let columns = self.generate_aggregate_columns(aggregates)?;

        Ok(format!(
            r#"CREATE MATERIALIZED VIEW {view_name}
WITH (timescaledb.continuous) AS
SELECT
    time_bucket('{granularity}', {timestamp_col}) AS bucket,
    {entity_col},
    {columns}
FROM {source_table}
GROUP BY bucket, {entity_col};"#,
            view_name = view_name,
            granularity = granularity,
            timestamp_col = self.timestamp_column,
            entity_col = self.entity_column,
            columns = columns.join(",\n    "),
            source_table = self.source_table,
        ))
    }

    /// Generate only the refresh policy statement for a granularity
    ///
    /// Used by the SyncPlanner which handles policy existence checking externally.
    pub fn generate_policy_ddl_only(
        &self,
        granularity: &str,
        policy: Option<&RefreshPolicyConfig>,
    ) -> Result<String> {
        self.generate_refresh_policy(granularity, policy)
    }

    /// Generate aggregate column expressions
    fn generate_aggregate_columns(&self, aggregates: &AggregatesConfig) -> Result<Vec<String>> {
        let mut columns = Vec::new();

        for (field_name, field_config) in &aggregates.fields {
            for metric in &field_config.metrics {
                let expr = self.metric_to_sql(field_name, metric)?;
                columns.push(expr);
            }
        }

        if columns.is_empty() {
            return Err(GoldDdlError::MissingRequiredField {
                field: "aggregates.fields".to_string(),
                context: "at least one field with metrics is required".to_string(),
            });
        }

        // Always add sample_count for aligned view compatibility
        columns.push("COUNT(*) AS sample_count".to_string());

        Ok(columns)
    }

    /// Convert a metric name to SQL expression
    fn metric_to_sql(&self, field: &str, metric: &str) -> Result<String> {
        let alias = format!("{}_{}", field, metric);

        let sql = match metric {
            "mean" => format!("AVG({}) AS {}", field, alias),
            "std" => format!("STDDEV({}) AS {}", field, alias),
            "min" => format!("MIN({}) AS {}", field, alias),
            "max" => format!("MAX({}) AS {}", field, alias),
            "count" => format!("COUNT({}) AS {}", field, alias),
            "p95" => format!(
                "PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY {}) AS {}",
                field, alias
            ),
            "p99" => format!(
                "PERCENTILE_CONT(0.99) WITHIN GROUP (ORDER BY {}) AS {}",
                field, alias
            ),
            "first" => format!("FIRST({}, {}) AS {}", field, self.timestamp_column, alias),
            "last" => format!("LAST({}, {}) AS {}", field, self.timestamp_column, alias),
            _ => {
                return Err(GoldDdlError::InvalidMetric {
                    metric: metric.to_string(),
                    field: field.to_string(),
                    valid: VALID_METRICS.iter().map(|s| s.to_string()).collect(),
                })
            }
        };

        Ok(sql)
    }

    /// Wrap CREATE statement with sync mode (IF NOT EXISTS check)
    fn wrap_sync_mode(&self, view_name: &str, create_sql: &str) -> Result<String> {
        // Extract schema and view name for metadata comment
        let parts: Vec<&str> = view_name.split('.').collect();
        let (schema, name) = if parts.len() == 2 {
            (parts[0], parts[1])
        } else {
            ("public", view_name)
        };

        // TimescaleDB continuous aggregates cannot be created inside DO blocks or functions
        // because they require special transaction handling.
        //
        // Strategy for sync mode:
        // 1. Generate plain CREATE statement with metadata comments
        // 2. deploy.sh handles idempotency by checking if view exists before executing
        // 3. If view exists, deploy.sh skips this DDL block
        //
        // The --CA-SYNC-CHECK comment enables deploy.sh to parse and check existence
        Ok(format!(
            r#"-- Sync mode: Create if not exists
-- CA-SYNC-CHECK: schema={schema} name={name}
{create_sql}"#,
            schema = schema,
            name = name,
            create_sql = create_sql,
        ))
    }

    /// Wrap CREATE statement with recreate mode (DROP CASCADE first)
    fn wrap_recreate_mode(&self, view_name: &str, create_sql: &str) -> Result<String> {
        Ok(format!(
            r#"-- Recreate mode: Drop and recreate
DROP MATERIALIZED VIEW IF EXISTS {view_name} CASCADE;

{create_sql}"#,
            view_name = view_name,
            create_sql = create_sql,
        ))
    }

    /// Generate refresh policy SQL
    ///
    /// Uses granularity-aware defaults if no explicit policy is provided:
    /// - Hourly aggregates: 15 min schedule, 4 hour lookback
    /// - Daily aggregates: 1 hour schedule, 3 day lookback
    /// - Other: 30 min schedule, 4 hour lookback
    fn generate_refresh_policy(
        &self,
        granularity: &str,
        policy: Option<&RefreshPolicyConfig>,
    ) -> Result<String> {
        let suffix = granularity_to_suffix(granularity);
        let view_name = format!("gold.{}_{}", self.stream_id.replace('-', "_"), suffix);

        // Use granularity-aware defaults
        let effective_policy = RefreshPolicyConfig::for_granularity(granularity, policy);

        Ok(format!(
            r#"-- Refresh policy for {view_name}
SELECT add_continuous_aggregate_policy('{view_name}',
    start_offset => INTERVAL '{start_offset}',
    end_offset => INTERVAL '{end_offset}',
    schedule_interval => INTERVAL '{schedule_interval}',
    if_not_exists => TRUE
);"#,
            view_name = view_name,
            start_offset = effective_policy.start_offset,
            end_offset = effective_policy.end_offset,
            schedule_interval = effective_policy.schedule_interval,
        ))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::gold::config::{FieldMetricsConfig, SilverEtlConfig, TimestampConfig};
    use std::collections::HashMap;

    fn create_test_stream_config() -> StreamConfig {
        StreamConfig {
            stream_id: "air-quality".to_string(),
            stream_type: None,
            fields: vec![],
            silver_etl: Some(SilverEtlConfig {
                target_table: "silver.air_quality_observations".to_string(),
                timestamp: Some(TimestampConfig {
                    target_field: "observation_time".to_string(),
                }),
            }),
            gold_etl: Some(GoldEtlConfig {
                enabled: true,
                aggregates: Some(AggregatesConfig {
                    granularities: vec!["1 hour".to_string()],
                    fields: {
                        let mut map = HashMap::new();
                        map.insert(
                            "pm25".to_string(),
                            FieldMetricsConfig {
                                metrics: vec![
                                    "mean".to_string(),
                                    "std".to_string(),
                                    "max".to_string(),
                                ],
                            },
                        );
                        map
                    },
                }),
                features: None,
                refresh_policy: None,
            }),
        }
    }

    // =========================================================================
    // Basic DDL Generation Tests
    // =========================================================================

    #[test]
    fn test_generator_creates_from_stream_config() {
        let config = create_test_stream_config();
        let generator = ContinuousAggregateGenerator::from_stream_config(&config);
        assert!(generator.is_ok());
    }

    #[test]
    fn test_generator_requires_silver_etl() {
        let mut config = create_test_stream_config();
        config.silver_etl = None;

        let result = ContinuousAggregateGenerator::from_stream_config(&config);
        assert!(result.is_err());
    }

    #[test]
    fn test_generate_creates_materialized_view() {
        let config = create_test_stream_config();
        let generator = ContinuousAggregateGenerator::from_stream_config(&config).unwrap();
        let gold_etl = config.gold_etl.as_ref().unwrap();

        let ddl = generator.generate(gold_etl, Action::Recreate).unwrap();

        assert!(ddl.contains("CREATE MATERIALIZED VIEW"));
        assert!(ddl.contains("gold.air_quality_hourly"));
        assert!(ddl.contains("WITH (timescaledb.continuous)"));
    }

    #[test]
    fn test_generate_creates_time_bucket() {
        let config = create_test_stream_config();
        let generator = ContinuousAggregateGenerator::from_stream_config(&config).unwrap();
        let gold_etl = config.gold_etl.as_ref().unwrap();

        let ddl = generator.generate(gold_etl, Action::Recreate).unwrap();

        assert!(ddl.contains("time_bucket('1 hour'"));
    }

    #[test]
    fn test_generate_creates_schema() {
        let config = create_test_stream_config();
        let generator = ContinuousAggregateGenerator::from_stream_config(&config).unwrap();
        let gold_etl = config.gold_etl.as_ref().unwrap();

        let ddl = generator.generate(gold_etl, Action::Recreate).unwrap();

        assert!(ddl.contains("CREATE SCHEMA IF NOT EXISTS gold;"));
    }

    // =========================================================================
    // Metric SQL Tests
    // =========================================================================

    #[test]
    fn test_metric_mean_generates_avg() {
        let config = create_test_stream_config();
        let generator = ContinuousAggregateGenerator::from_stream_config(&config).unwrap();

        let sql = generator.metric_to_sql("pm25", "mean").unwrap();
        assert_eq!(sql, "AVG(pm25) AS pm25_mean");
    }

    #[test]
    fn test_metric_std_generates_stddev() {
        let config = create_test_stream_config();
        let generator = ContinuousAggregateGenerator::from_stream_config(&config).unwrap();

        let sql = generator.metric_to_sql("pm25", "std").unwrap();
        assert_eq!(sql, "STDDEV(pm25) AS pm25_std");
    }

    #[test]
    fn test_metric_p95_generates_percentile() {
        let config = create_test_stream_config();
        let generator = ContinuousAggregateGenerator::from_stream_config(&config).unwrap();

        let sql = generator.metric_to_sql("pm25", "p95").unwrap();
        assert!(sql.contains("PERCENTILE_CONT(0.95)"));
        assert!(sql.contains("pm25_p95"));
    }

    #[test]
    fn test_metric_first_generates_first_function() {
        let config = create_test_stream_config();
        let generator = ContinuousAggregateGenerator::from_stream_config(&config).unwrap();

        let sql = generator.metric_to_sql("pm25", "first").unwrap();
        assert!(sql.contains("FIRST(pm25, observation_time)"));
        assert!(sql.contains("pm25_first"));
    }

    #[test]
    fn test_metric_last_generates_last_function() {
        let config = create_test_stream_config();
        let generator = ContinuousAggregateGenerator::from_stream_config(&config).unwrap();

        let sql = generator.metric_to_sql("pm25", "last").unwrap();
        assert!(sql.contains("LAST(pm25, observation_time)"));
        assert!(sql.contains("pm25_last"));
    }

    #[test]
    fn test_invalid_metric_returns_error() {
        let config = create_test_stream_config();
        let generator = ContinuousAggregateGenerator::from_stream_config(&config).unwrap();

        let result = generator.metric_to_sql("pm25", "invalid");
        assert!(result.is_err());
    }

    // =========================================================================
    // Idempotency Tests
    // =========================================================================

    #[test]
    fn test_sync_mode_outputs_check_markers() {
        // In the new architecture, sync mode outputs CA-SYNC-CHECK markers.
        // Actual idempotency checking is done by the SyncPlanner via DB queries.
        // When used without DB URL, deploy.sh can use the markers for manual checks.
        let config = create_test_stream_config();
        let generator = ContinuousAggregateGenerator::from_stream_config(&config).unwrap();
        let gold_etl = config.gold_etl.as_ref().unwrap();

        let ddl = generator.generate(gold_etl, Action::Sync).unwrap();

        // Should contain sync mode marker and CA-SYNC-CHECK info
        assert!(ddl.contains("Sync mode"));
        assert!(ddl.contains("CA-SYNC-CHECK"));
        assert!(ddl.contains("schema=gold"));
        assert!(ddl.contains("name=air_quality_hourly"));
        // Should still contain the CREATE statement
        assert!(ddl.contains("CREATE MATERIALIZED VIEW"));
    }

    #[test]
    fn test_recreate_mode_drops_first() {
        let config = create_test_stream_config();
        let generator = ContinuousAggregateGenerator::from_stream_config(&config).unwrap();
        let gold_etl = config.gold_etl.as_ref().unwrap();

        let ddl = generator.generate(gold_etl, Action::Recreate).unwrap();

        assert!(ddl.contains("DROP MATERIALIZED VIEW IF EXISTS"));
        assert!(ddl.contains("CASCADE"));
    }

    // =========================================================================
    // Refresh Policy Tests
    // =========================================================================

    #[test]
    fn test_generate_includes_refresh_policy() {
        let config = create_test_stream_config();
        let generator = ContinuousAggregateGenerator::from_stream_config(&config).unwrap();
        let gold_etl = config.gold_etl.as_ref().unwrap();

        let ddl = generator.generate(gold_etl, Action::Recreate).unwrap();

        assert!(ddl.contains("add_continuous_aggregate_policy"));
        assert!(ddl.contains("start_offset"));
        assert!(ddl.contains("end_offset"));
        assert!(ddl.contains("schedule_interval"));
    }

    #[test]
    fn test_refresh_policy_uses_defaults() {
        let config = create_test_stream_config();
        let generator = ContinuousAggregateGenerator::from_stream_config(&config).unwrap();

        let policy_sql = generator.generate_refresh_policy("1 hour", None).unwrap();

        assert!(policy_sql.contains("4 hours")); // default start_offset
        assert!(policy_sql.contains("15 minutes")); // default end_offset
    }

    // =========================================================================
    // Multiple Granularity Tests
    // =========================================================================

    #[test]
    fn test_multiple_granularities_generate_multiple_views() {
        let mut config = create_test_stream_config();
        let gold_etl = config.gold_etl.as_mut().unwrap();
        let agg = gold_etl.aggregates.as_mut().unwrap();
        agg.granularities = vec!["1 hour".to_string(), "1 day".to_string()];

        let generator = ContinuousAggregateGenerator::from_stream_config(&config).unwrap();
        let ddl = generator
            .generate(config.gold_etl.as_ref().unwrap(), Action::Recreate)
            .unwrap();

        assert!(ddl.contains("gold.air_quality_hourly"));
        assert!(ddl.contains("gold.air_quality_daily"));
    }

    // =========================================================================
    // v11-004: Granularity-Aware Refresh Policy Tests
    // =========================================================================

    #[test]
    fn test_daily_aggregate_uses_daily_refresh_defaults() {
        let config = create_test_stream_config();
        let generator = ContinuousAggregateGenerator::from_stream_config(&config).unwrap();

        let policy_sql = generator.generate_refresh_policy("1 day", None).unwrap();

        // Daily should use 3 days start_offset and 1 hour schedule
        assert!(policy_sql.contains("3 days"));
        assert!(policy_sql.contains("schedule_interval => INTERVAL '1 hour'"));
        assert!(policy_sql.contains("gold.air_quality_daily"));
    }

    #[test]
    fn test_hourly_aggregate_uses_hourly_refresh_defaults() {
        let config = create_test_stream_config();
        let generator = ContinuousAggregateGenerator::from_stream_config(&config).unwrap();

        let policy_sql = generator.generate_refresh_policy("1 hour", None).unwrap();

        // Hourly should use 4 hours start_offset and 15 minutes schedule
        assert!(policy_sql.contains("start_offset => INTERVAL '4 hours'"));
        assert!(policy_sql.contains("schedule_interval => INTERVAL '15 minutes'"));
        assert!(policy_sql.contains("gold.air_quality_hourly"));
    }

    #[test]
    fn test_multi_granularity_generates_appropriate_policies() {
        let mut config = create_test_stream_config();
        let gold_etl = config.gold_etl.as_mut().unwrap();
        let agg = gold_etl.aggregates.as_mut().unwrap();
        agg.granularities = vec!["1 hour".to_string(), "1 day".to_string()];

        let generator = ContinuousAggregateGenerator::from_stream_config(&config).unwrap();
        let ddl = generator
            .generate(config.gold_etl.as_ref().unwrap(), Action::Recreate)
            .unwrap();

        // Both policies should be in the output
        assert!(ddl.contains("gold.air_quality_hourly"));
        assert!(ddl.contains("gold.air_quality_daily"));

        // Check that appropriate defaults are used
        // Note: order may vary, just ensure both patterns are present
        assert!(ddl.contains("schedule_interval => INTERVAL '15 minutes'")); // hourly
        assert!(ddl.contains("schedule_interval => INTERVAL '1 hour'")); // daily
    }

    #[test]
    fn test_explicit_policy_overrides_granularity_defaults() {
        let mut config = create_test_stream_config();
        let gold_etl = config.gold_etl.as_mut().unwrap();
        gold_etl.refresh_policy = Some(RefreshPolicyConfig {
            schedule_interval: "20 minutes".to_string(),
            start_offset: "2 hours".to_string(),
            end_offset: "10 minutes".to_string(),
        });

        let generator = ContinuousAggregateGenerator::from_stream_config(&config).unwrap();
        let ddl = generator
            .generate(config.gold_etl.as_ref().unwrap(), Action::Recreate)
            .unwrap();

        // Explicit policy should override defaults
        assert!(ddl.contains("20 minutes"));
        assert!(ddl.contains("2 hours"));
        assert!(ddl.contains("10 minutes"));
    }
}
