apiVersion: 1
datasources:
  - name: DuckDB
    type: frser-sqlite-datasource
    uid: duckdb-ndp
    access: proxy
    url: file:/data/duckdb/grafana.db
    isDefault: true
    editable: false
    jsonData:
      path: /data/duckdb/grafana.db
