apiVersion: 1

# Delete old datasource to allow UID change
deleteDatasources:
  - name: timescaledb-silver
    orgId: 1
  - name: NDP-TimescaleDB
    orgId: 1

datasources:
  - name: timescaledb-silver
    uid: timescaledb-silver
    type: postgres
    url: timescaledb:5432
    database: ndp
    user: grafana_reader
    secureJsonData:
      password: grafana_read_only
    jsonData:
      database: ndp
      sslmode: disable
      maxOpenConns: 10
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: true
    isDefault: false
    editable: false
