apiVersion: 1

datasources:
  - name: NDP-TimescaleDB
    type: postgres
    url: pi5-timescaledb:5432
    database: ndp
    user: grafana_reader
    secureJsonData:
      password: grafana_read_only
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: true
    isDefault: false
    editable: false
